-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-06-09
-- Description: Se crea la vista CVC_DESEMPENO_INDICADOR la cual es un insumo para el tablero Paneles y TBG's

-- Author:      Oscar Angel 
-- Update Date: 2022-11-04
-- Description: Se inserción para las diferentes reglas de validación con el campo PLAN_ACUMULADO_NORMALIZADO, PLAN_PERIODO_NORMALIZADO, META_ANNIO_NORMALIZADO

-- Author:      Oscar Angel 
-- Update Date: 2023-01-06
-- Description: Ajuste de Nulidad para sumatoria cuando los campos DESC_ESC_BAJO, DESC_ESC_MEDIOM DESC_ESC_ALTO se registran en vacio.

-- Author:      Oscar Angel 
-- Update Date: 2024-04-17
-- Description: Se adiciona el campo FK_TABLERO a la salida de la vista

-- Author:      Oscar Angel 
-- Update Date: 2024-06-18
-- Description: Se adiciona el cruce con el nuevo campo FK_INDICADOR

-- =============================================

CREATE VIEW ATOMO.CVC_DESEMPENO_INDICADOR AS  
 
SELECT SUBSTRING(C.DESC_PERIODO,1,4) AS DESC_ANNIO
	 ,C.FK_PARAM_INDICADOR
	 ,C.FK_INDICADOR
	 ,C.FK_PERIODO
	 ,C.FK_TABLERO
	 ,C.DESC_PERIODO
	 ,C.DESC_CAUSAS_DESEMPENO_PERIODO
	 ,C.DESC_CAUSAS_DESEMPENO_ACUM
	 ,C.DESC_PREMISAS_ESC_ALTO
	 ,C.DESC_PREMISAS_ESC_MEDIO
	 ,C.DESC_PREMISAS_ESC_BAJO
	 ,C.DESC_ACCIONES_DE_ASEGURAMIENTO
	 ,C.DESC_META_NORMALIZADA
	 ,C.DESC_SENTIDO
	 ,C.DESC_FRECUENCIA
	 ,C.REAL_PERIODO
	 ,C.REAL_ACUMULADO
	 ,C.PLAN_PERIODO
	 ,C.PLAN_ACUMULADO
	 ,C.PLAN_PERIODO_NORMALIZADO
	 ,C.PLAN_ACUMULADO_NORMALIZADO
	 ,C.META_ANNIO
	 ,C.META_ANNIO_NORMALIZADO
	 ,C.META_ANNIO_1
	 ,C.META_ANNIO_2
	 ,C.PROYECCION_PERIODO_1
	 ,C.PROYECCION_PERIODO_2
	 ,C.PROYECCION_PERIODO_3
	 ,CASE WHEN C.[DESC_ESC_BAJO] IS NULL OR C.[DESC_ESC_BAJO] = '' 
	         THEN NULL
		   ELSE C.VLR_PROYECCION_ANNIO_ESC_BAJO END AS VLR_PROYECCION_ANNIO_ESC_BAJO
	 ,CASE WHEN C.[DESC_ESC_MEDIO] IS NULL OR C.[DESC_ESC_MEDIO] = '' 
	         THEN NULL
		   ELSE C.VLR_PROYECCION_ANNIO_ESC_MEDIO END AS VLR_PROYECCION_ANNIO_ESC_MEDIO
	 ,CASE WHEN C.[DESC_ESC_ALTO] IS NULL OR C.[DESC_ESC_ALTO] = '' 
	         THEN NULL
		   ELSE C.VLR_PROYECCION_ANNIO_ESC_ALTO END AS VLR_PROYECCION_ANNIO_ESC_ALTO

     ,CASE WHEN C.PRC_CUMP_PERIODO < 0
			  THEN 0 	   
		   ELSE C.PRC_CUMP_PERIODO END AS PRC_CUMP_PERIODO
     ,CASE WHEN C.PRC_CUMP_ACUMULADO < 0 
			  THEN 0 
		   ELSE C.PRC_CUMP_ACUMULADO END AS PRC_CUMP_ACUMULADO
     ,CASE WHEN C.PRC_CUMP_ANNIO_ESC_BAJO < 0 
			  THEN 0 
		   ELSE C.PRC_CUMP_ANNIO_ESC_BAJO END AS PRC_CUMP_ANNIO_ESC_BAJO
     ,CASE WHEN C.PRC_CUMP_ANNIO_ESC_MEDIO < 0 
			  THEN 0 
		   ELSE C.PRC_CUMP_ANNIO_ESC_MEDIO END AS PRC_CUMP_ANNIO_ESC_MEDIO
     ,CASE WHEN C.PRC_CUMP_ANNIO_ESC_ALTO < 0 
			  THEN 0 
		   ELSE C.PRC_CUMP_ANNIO_ESC_ALTO END AS PRC_CUMP_ANNIO_ESC_ALTO
		   
     ,CASE WHEN C.PRC_CUMP_PERIODO < 0 
			  THEN 0 
		   ELSE CASE WHEN C.PRC_CUMP_PERIODO > 1.2 
					   THEN 1.2 
					 ELSE C.PRC_CUMP_PERIODO  END
      END AS PRC_DESEMPENO_PERIODO
    
     ,CASE WHEN C.PRC_CUMP_ACUMULADO < 0 
			  THEN 0 
		   ELSE CASE WHEN C.PRC_CUMP_ACUMULADO > 1.2 
					   THEN 1.2 
					 ELSE C.PRC_CUMP_ACUMULADO END
     END AS PRC_DESEMPENO_ACUMULADO
     
     ,CASE WHEN C.PRC_CUMP_ANNIO_ESC_BAJO < 0 
			  THEN 0 
		   ELSE CASE WHEN C.PRC_CUMP_ANNIO_ESC_BAJO > 1.2 
					   THEN 1.2 
					 ELSE C.PRC_CUMP_ANNIO_ESC_BAJO END
      END AS PRC_DESEMPENO_ANNIO_ESC_BAJO
       
     ,CASE WHEN C.PRC_CUMP_ANNIO_ESC_MEDIO < 0 
			  THEN 0 
		   ELSE CASE WHEN C.PRC_CUMP_ANNIO_ESC_MEDIO > 1.2 
					   THEN 1.2 
					 ELSE C.PRC_CUMP_ANNIO_ESC_MEDIO END
      END AS PRC_DESEMPENO_ANNIO_ESC_MEDIO
      
     ,CASE WHEN C.PRC_CUMP_ANNIO_ESC_ALTO < 0 
			  THEN 0 
		   ELSE CASE WHEN C.PRC_CUMP_ANNIO_ESC_ALTO > 1.2 
					   THEN 1.2 
					 ELSE C.PRC_CUMP_ANNIO_ESC_ALTO END
      END AS PRC_DESEMPENO_ANNIO_ESC_ALTO

	 ,C.FECHA_CARGA_SYNAPSE
	 ,C.FECHA_PROXIMA_ACTUALIZA_SYNAPSE
	  
FROM
(
      SELECT B.*,
            CASE WHEN REAL_PERIODO IS NULL 
					THEN NULL  
				 WHEN UPPER(DESC_SENTIDO) = 'POSITIVO' AND (ISNULL(PLAN_PERIODO_NORMALIZADO,PLAN_PERIODO) < 0 ) 
					THEN ((ISNULL(PLAN_PERIODO_NORMALIZADO,PLAN_PERIODO)-REAL_PERIODO) / ISNULL(PLAN_PERIODO_NORMALIZADO,PLAN_PERIODO)) + 1 
				 WHEN ((PLAN_PERIODO = 0 AND PLAN_PERIODO_NORMALIZADO = 0) OR (PLAN_PERIODO = 0 AND PLAN_PERIODO_NORMALIZADO is NULL) OR (PLAN_PERIODO is null AND PLAN_PERIODO_NORMALIZADO = 0)) 		AND REAL_PERIODO = 0 
					THEN 1 
				 WHEN (PLAN_PERIODO = 0 AND REAL_PERIODO = 0 AND (PLAN_PERIODO_NORMALIZADO IS NULL OR PLAN_PERIODO_NORMALIZADO = 0 )) OR (PLAN_PERIODO_NORMALIZADO = 0 AND REAL_PERIODO = 0)
					THEN 1 
				 WHEN (UPPER(DESC_SENTIDO) = 'NEGATIVO' AND ((PLAN_PERIODO = 0 AND PLAN_PERIODO_NORMALIZADO = 0) OR (PLAN_PERIODO = 0 AND PLAN_PERIODO_NORMALIZADO is NULL) OR (PLAN_PERIODO is 		null AND PLAN_PERIODO_NORMALIZADO = 0) OR (ISNULL(PLAN_PERIODO_NORMALIZADO,PLAN_PERIODO) = 0)) AND REAL_PERIODO > 0) OR (UPPER(DESC_SENTIDO) = 'POSITIVO' AND ( (		  PLAN_PERIODO = 0 AND PLAN_PERIODO_NORMALIZADO = 0) OR (PLAN_PERIODO = 0 AND PLAN_PERIODO_NORMALIZADO is NULL) OR (PLAN_PERIODO is null AND PLAN_PERIODO_NORMALIZADO = 0) 		   OR (ISNULL(PLAN_PERIODO_NORMALIZADO,PLAN_PERIODO) = 0)) AND REAL_PERIODO < 0) 
					THEN 0 
				 WHEN (UPPER(DESC_SENTIDO) = 'NEGATIVO' AND ( (PLAN_PERIODO = 0 AND PLAN_PERIODO_NORMALIZADO = 0) OR (PLAN_PERIODO = 0 AND PLAN_PERIODO_NORMALIZADO is NULL) OR (PLAN_PERIODO is 		null AND PLAN_PERIODO_NORMALIZADO = 0) OR (ISNULL(PLAN_PERIODO_NORMALIZADO,PLAN_PERIODO) = 0)) AND REAL_PERIODO < 0) OR (UPPER(DESC_SENTIDO) = 'POSITIVO' AND ((
						 PLAN_PERIODO = 0 AND PLAN_PERIODO_NORMALIZADO = 0) OR (PLAN_PERIODO = 0 AND PLAN_PERIODO_NORMALIZADO is NULL) OR (PLAN_PERIODO is null AND PLAN_PERIODO_NORMALIZADO = 0) OR (ISNULL(PLAN_PERIODO_NORMALIZADO,PLAN_PERIODO) = 0)) AND REAL_PERIODO  >  0) 
					THEN 1 
				WHEN (DESC_SENTIDO = 'Negativo' OR PLAN_PERIODO < 0) AND DESC_META_NORMALIZADA = 'No' 
					THEN CASE WHEN PLAN_PERIODO = 0 
								  THEN 0 
							   ELSE ((PLAN_PERIODO - REAL_PERIODO) / PLAN_PERIODO) + 1 END 
				WHEN (DESC_SENTIDO = 'Negativo' OR PLAN_PERIODO_NORMALIZADO < 0) AND DESC_META_NORMALIZADA = 'Si' 
					THEN CASE WHEN PLAN_PERIODO_NORMALIZADO = 0 
								  THEN 0 
							   ELSE CASE WHEN PLAN_PERIODO_NORMALIZADO IS NULL 
											THEN ((PLAN_PERIODO-REAL_PERIODO) / PLAN_PERIODO) + 1 
										  ELSE ((PLAN_PERIODO_NORMALIZADO-REAL_PERIODO) / PLAN_PERIODO_NORMALIZADO) + 1
									  END 
						  END
				WHEN DESC_META_NORMALIZADA = 'No' 
					THEN CASE WHEN PLAN_PERIODO = 0 
								  THEN 0 
							   ELSE (REAL_PERIODO / PLAN_PERIODO) END 
				WHEN DESC_META_NORMALIZADA = 'Si' 
					THEN CASE WHEN PLAN_PERIODO_NORMALIZADO = 0 
								  THEN 0 
							   ELSE CASE WHEN PLAN_PERIODO_NORMALIZADO IS NULL 
											 THEN CASE WHEN PLAN_PERIODO = 0 
															THEN 0 
														 ELSE (REAL_PERIODO / PLAN_PERIODO) END 
										  WHEN PLAN_PERIODO_NORMALIZADO = 0 
											 THEN 0 
										  ELSE (REAL_PERIODO / PLAN_PERIODO_NORMALIZADO) END 
						  END 
				
				ELSE NULL END AS PRC_CUMP_PERIODO,

             CASE WHEN REAL_ACUMULADO IS NULL 
					THEN NULL 
				 WHEN UPPER(DESC_SENTIDO) = 'POSITIVO' AND (ISNULL(PLAN_ACUMULADO_NORMALIZADO,PLAN_ACUMULADO)<0 ) 
					THEN ((ISNULL(PLAN_ACUMULADO_NORMALIZADO,PLAN_ACUMULADO)- REAL_ACUMULADO) / ISNULL(PLAN_ACUMULADO_NORMALIZADO,PLAN_ACUMULADO)) + 1 
				 WHEN ((PLAN_ACUMULADO = 0 AND PLAN_ACUMULADO_NORMALIZADO = 0) OR (PLAN_ACUMULADO IS NULL AND PLAN_ACUMULADO_NORMALIZADO = 0) OR (PLAN_ACUMULADO = 0 AND PLAN_ACUMULADO_NORMALIZADO IS NULL)) AND REAL_ACUMULADO = 0 
					THEN 1 
				 WHEN (PLAN_ACUMULADO = 0 AND REAL_ACUMULADO = 0 AND (PLAN_ACUMULADO_NORMALIZADO IS NULL OR PLAN_ACUMULADO_NORMALIZADO = 0 )) OR (PLAN_ACUMULADO_NORMALIZADO = 0 AND REAL_ACUMULADO = 0)
					THEN 1
                 WHEN (UPPER(DESC_SENTIDO) = 'NEGATIVO' AND ((PLAN_ACUMULADO = 0 AND PLAN_ACUMULADO_NORMALIZADO = 0) OR (PLAN_ACUMULADO IS NULL AND 
							PLAN_ACUMULADO_NORMALIZADO = 0) OR (PLAN_ACUMULADO = 0 AND PLAN_ACUMULADO_NORMALIZADO IS NULL) OR (ISNULL(PLAN_ACUMULADO_NORMALIZADO,PLAN_ACUMULADO)=0)) AND REAL_ACUMULADO > 0) OR (UPPER(DESC_SENTIDO) = 'POSITIVO' AND ((PLAN_ACUMULADO = 0 AND PLAN_ACUMULADO_NORMALIZADO = 0) OR (PLAN_ACUMULADO IS NULL AND PLAN_ACUMULADO_NORMALIZADO = 0) OR (PLAN_ACUMULADO = 0 AND PLAN_ACUMULADO_NORMALIZADO IS NULL) OR (ISNULL(PLAN_ACUMULADO_NORMALIZADO,PLAN_ACUMULADO)=0)) AND REAL_ACUMULADO < 0) 
					THEN 0 
				 WHEN (UPPER(DESC_SENTIDO) = 'NEGATIVO' AND ((PLAN_ACUMULADO = 0 AND PLAN_ACUMULADO_NORMALIZADO = 0) OR (PLAN_ACUMULADO IS NULL AND PLAN_ACUMULADO_NORMALIZADO = 0) 	  OR (PLAN_ACUMULADO = 0 AND PLAN_ACUMULADO_NORMALIZADO IS NULL) OR (ISNULL(PLAN_ACUMULADO_NORMALIZADO,PLAN_ACUMULADO)=0)) AND REAL_ACUMULADO < 0) 
						OR (UPPER(DESC_SENTIDO) = 'POSITIVO' AND ((PLAN_ACUMULADO = 0 AND PLAN_ACUMULADO_NORMALIZADO = 0) OR (PLAN_ACUMULADO IS NULL AND 
						PLAN_ACUMULADO_NORMALIZADO = 0) OR (PLAN_ACUMULADO = 0 AND PLAN_ACUMULADO_NORMALIZADO IS NULL) OR (ISNULL(PLAN_ACUMULADO_NORMALIZADO,PLAN_ACUMULADO)=0)) 
						AND REAL_ACUMULADO > 0) 
					THEN 1 
				 WHEN (DESC_SENTIDO = 'Negativo' OR PLAN_ACUMULADO < 0) AND DESC_META_NORMALIZADA = 'No' 
					THEN CASE WHEN PLAN_ACUMULADO = 0 
								 THEN 0 
							  ELSE ((PLAN_ACUMULADO - REAL_ACUMULADO) / PLAN_ACUMULADO) + 1 END 
				 WHEN (DESC_SENTIDO = 'Negativo' OR PLAN_ACUMULADO_NORMALIZADO < 0) AND DESC_META_NORMALIZADA = 'Si' 
					THEN CASE WHEN PLAN_ACUMULADO_NORMALIZADO = 0 
								THEN 0 
							  ELSE CASE WHEN PLAN_ACUMULADO_NORMALIZADO IS NULL AND PLAN_ACUMULADO <> 0 
										   THEN ((PLAN_ACUMULADO-REAL_ACUMULADO) / PLAN_ACUMULADO) + 1 
										ELSE ((PLAN_ACUMULADO_NORMALIZADO-REAL_ACUMULADO) / PLAN_ACUMULADO_NORMALIZADO) + 1 
									END 
						 END 
                 WHEN DESC_META_NORMALIZADA = 'No' 
					THEN CASE WHEN PLAN_ACUMULADO = 0 
								 THEN 0 
						 ELSE (REAL_ACUMULADO / PLAN_ACUMULADO) END
				 WHEN DESC_META_NORMALIZADA = 'Si' 
					THEN CASE WHEN PLAN_ACUMULADO_NORMALIZADO = 0 
								 THEN 0 
							  ELSE CASE WHEN PLAN_ACUMULADO_NORMALIZADO IS NULL AND PLAN_ACUMULADO <> 0 
										   THEN (REAL_ACUMULADO / PLAN_ACUMULADO) 
										ELSE CASE WHEN PLAN_ACUMULADO_NORMALIZADO = 0 
													THEN 0 
											      ELSE (REAL_ACUMULADO / PLAN_ACUMULADO_NORMALIZADO) 
											 END 
								   END
                         END 
				 ELSE NULL END  AS PRC_CUMP_ACUMULADO, 

            CASE WHEN B.VLR_PROYECCION_ANNIO_ESC_BAJO IS NULL 
					THEN NULL
				 WHEN (META_ANNIO = 0 AND B.VLR_PROYECCION_ANNIO_ESC_BAJO = 0 AND (META_ANNIO_NORMALIZADO IS NULL OR META_ANNIO_NORMALIZADO = 0 )) OR (META_ANNIO_NORMALIZADO = 0 AND B.VLR_PROYECCION_ANNIO_ESC_BAJO = 0)
					THEN 1  
				 WHEN META_ANNIO = 0 AND B.VLR_PROYECCION_ANNIO_ESC_BAJO IS NULL 
					THEN NULL 
				 WHEN (UPPER(DESC_SENTIDO) = 'NEGATIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0)) AND B.VLR_PROYECCION_ANNIO_ESC_BAJO > 0) OR 
					  (UPPER(DESC_SENTIDO) = 'POSITIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0)) AND B.VLR_PROYECCION_ANNIO_ESC_BAJO < 0) 
					THEN 0 
				 WHEN (UPPER(DESC_SENTIDO) = 'NEGATIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0)) AND B.VLR_PROYECCION_ANNIO_ESC_BAJO < 0) OR 
					  (UPPER(DESC_SENTIDO) = 'POSITIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0)) AND B.VLR_PROYECCION_ANNIO_ESC_BAJO > 0) 
					THEN 1 
				 WHEN (DESC_SENTIDO = 'Negativo' OR META_ANNIO < 0) AND DESC_META_NORMALIZADA = 'No' 
					THEN CASE WHEN META_ANNIO = 0 
								THEN 0 
						 ELSE ((META_ANNIO-B.VLR_PROYECCION_ANNIO_ESC_BAJO) / META_ANNIO) + 1 END 
				 WHEN (DESC_SENTIDO = 'Negativo' OR ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) < 0) AND DESC_META_NORMALIZADA = 'Si' 
					THEN CASE WHEN ISNULL(META_ANNIO_NORMALIZADO, META_ANNIO)= 0 
								THEN 0 
						 ELSE CASE WHEN META_ANNIO_NORMALIZADO IS NULL AND META_ANNIO <> 0 
									  THEN ((META_ANNIO-B.VLR_PROYECCION_ANNIO_ESC_BAJO) / META_ANNIO) + 1 
								   ELSE ((META_ANNIO_NORMALIZADO-B.VLR_PROYECCION_ANNIO_ESC_BAJO) / META_ANNIO_NORMALIZADO) + 1 
							  END 
						 END 
				 ELSE CASE WHEN DESC_META_NORMALIZADA = 'No' 
							 THEN CASE WHEN META_ANNIO = 0 
										 THEN 0 
								  ELSE (B.VLR_PROYECCION_ANNIO_ESC_BAJO / META_ANNIO) 
								  END 
						   ELSE CASE WHEN DESC_META_NORMALIZADA = 'Si' 
									   THEN CASE WHEN ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0 
												   THEN 0 
												 ELSE CASE WHEN META_ANNIO_NORMALIZADO IS NULL AND META_ANNIO <> 0  
															 THEN (B.VLR_PROYECCION_ANNIO_ESC_BAJO / META_ANNIO) 
													       ELSE CASE WHEN META_ANNIO_NORMALIZADO = 0 
																	   THEN 0 
																     ELSE (B.VLR_PROYECCION_ANNIO_ESC_BAJO / META_ANNIO_NORMALIZADO) 
															    END 
													  END
                                             END 
									 ELSE NULL
								END 
				      END 
		 END AS PRC_CUMP_ANNIO_ESC_BAJO,
            
            CASE WHEN B.VLR_PROYECCION_ANNIO_ESC_MEDIO IS NULL 
					THEN NULL
				 WHEN (META_ANNIO = 0 AND B.VLR_PROYECCION_ANNIO_ESC_MEDIO = 0 AND (META_ANNIO_NORMALIZADO IS NULL OR META_ANNIO_NORMALIZADO = 0 )) OR (META_ANNIO_NORMALIZADO = 0 AND B.VLR_PROYECCION_ANNIO_ESC_MEDIO = 0) 
					THEN 1 
				 WHEN META_ANNIO = 0 AND B.VLR_PROYECCION_ANNIO_ESC_MEDIO IS NULL 
					THEN NULL 
				 WHEN (UPPER(DESC_SENTIDO) = 'NEGATIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0)) AND B.VLR_PROYECCION_ANNIO_ESC_MEDIO > 0) OR 
					  (UPPER(DESC_SENTIDO) = 'POSITIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0)) AND B.VLR_PROYECCION_ANNIO_ESC_MEDIO < 0) 
					THEN 0 
				 WHEN (UPPER(DESC_SENTIDO) = 'NEGATIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0) ) AND B.VLR_PROYECCION_ANNIO_ESC_MEDIO < 0) OR 
					  (UPPER(DESC_SENTIDO) = 'POSITIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0) ) AND B.VLR_PROYECCION_ANNIO_ESC_MEDIO > 0) 
					THEN 1 
				 WHEN (DESC_SENTIDO = 'Negativo' OR META_ANNIO < 0) AND DESC_META_NORMALIZADA = 'No' 
					THEN CASE WHEN META_ANNIO = 0 
								 THEN 0 
						      ELSE ((META_ANNIO-B.VLR_PROYECCION_ANNIO_ESC_MEDIO) / META_ANNIO) + 1 
						 END
                 WHEN (DESC_SENTIDO = 'Negativo' OR ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) < 0) AND DESC_META_NORMALIZADA = 'Si' 
					THEN CASE WHEN ISNULL(META_ANNIO_NORMALIZADO, META_ANNIO) = 0 
								 THEN 0 
							  ELSE CASE WHEN META_ANNIO_NORMALIZADO IS NULL 
										   THEN ((META_ANNIO-B.VLR_PROYECCION_ANNIO_ESC_MEDIO) / META_ANNIO) + 1 
										ELSE ((META_ANNIO_NORMALIZADO-B.VLR_PROYECCION_ANNIO_ESC_MEDIO) / META_ANNIO_NORMALIZADO) + 1 
								   END 
						 END 
				 WHEN DESC_META_NORMALIZADA = 'No' 
					THEN CASE WHEN META_ANNIO = 0 
								 THEN 0 
						      ELSE (B.VLR_PROYECCION_ANNIO_ESC_MEDIO / META_ANNIO) 
						 END 
				 WHEN DESC_META_NORMALIZADA = 'Si' 
					THEN CASE WHEN ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0 
								 THEN 0 
							  ELSE CASE WHEN META_ANNIO_NORMALIZADO IS NULL
							               THEN CASE WHEN META_ANNIO = 0 
													   THEN 0 
											    ELSE (B.VLR_PROYECCION_ANNIO_ESC_MEDIO / META_ANNIO) 
												END 
										ELSE CASE WHEN META_ANNIO_NORMALIZADO = 0 
													THEN 0 
											 ELSE (B.VLR_PROYECCION_ANNIO_ESC_MEDIO / META_ANNIO_NORMALIZADO) 
								             END 
								   END
						 END 
				 ELSE NULL END AS PRC_CUMP_ANNIO_ESC_MEDIO,
      
            CASE WHEN B.VLR_PROYECCION_ANNIO_ESC_ALTO IS NULL 
					THEN NULL
                 WHEN (META_ANNIO = 0 AND B.VLR_PROYECCION_ANNIO_ESC_ALTO = 0AND (META_ANNIO_NORMALIZADO IS NULL OR META_ANNIO_NORMALIZADO = 0 )) OR (META_ANNIO_NORMALIZADO = 0 AND B.VLR_PROYECCION_ANNIO_ESC_ALTO = 0)
					THEN 1
                 WHEN META_ANNIO = 0 AND B.VLR_PROYECCION_ANNIO_ESC_ALTO IS NULL 
					THEN NULL 
				 WHEN (UPPER(DESC_SENTIDO) = 'NEGATIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0)) AND B.VLR_PROYECCION_ANNIO_ESC_ALTO > 0) OR 
					  (UPPER(DESC_SENTIDO) = 'POSITIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0)) AND B.VLR_PROYECCION_ANNIO_ESC_ALTO < 0) 
					THEN 0 
				 WHEN (UPPER(DESC_SENTIDO) = 'NEGATIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0)) AND B.VLR_PROYECCION_ANNIO_ESC_ALTO < 0) OR 
				      (UPPER(DESC_SENTIDO) = 'POSITIVO' AND ((ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0)) AND B.VLR_PROYECCION_ANNIO_ESC_ALTO > 0) 
					THEN 1 
				 WHEN (DESC_SENTIDO = 'Negativo' OR META_ANNIO < 0) AND DESC_META_NORMALIZADA = 'No' 
					THEN CASE WHEN META_ANNIO = 0 
								 THEN 0 
							  ELSE ((META_ANNIO-B.VLR_PROYECCION_ANNIO_ESC_ALTO) / META_ANNIO) + 1 
						 END 
                 WHEN (DESC_SENTIDO = 'Negativo' OR ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) < 0) AND DESC_META_NORMALIZADA = 'Si' 
					THEN CASE WHEN ISNULL(META_ANNIO_NORMALIZADO, META_ANNIO) = 0 
								 THEN 0 
						      ELSE CASE WHEN META_ANNIO_NORMALIZADO IS NULL 
										   THEN ((META_ANNIO - B.VLR_PROYECCION_ANNIO_ESC_ALTO) / META_ANNIO) + 1 
										ELSE  ((META_ANNIO_NORMALIZADO-B.VLR_PROYECCION_ANNIO_ESC_ALTO) / META_ANNIO_NORMALIZADO) + 1 
								   END 
						 END 
				 WHEN DESC_META_NORMALIZADA = 'No' 
					THEN CASE WHEN META_ANNIO = 0 
								 THEN 0 
						      ELSE (B.VLR_PROYECCION_ANNIO_ESC_ALTO / META_ANNIO) 
						 END
                 WHEN DESC_META_NORMALIZADA = 'Si' 
					THEN CASE WHEN ISNULL(META_ANNIO_NORMALIZADO,META_ANNIO) = 0 
								 THEN 0 
							  ELSE CASE WHEN META_ANNIO_NORMALIZADO IS NULL 
										   THEN CASE WHEN META_ANNIO = 0 
													    THEN 0 
												     ELSE (B.VLR_PROYECCION_ANNIO_ESC_ALTO / META_ANNIO) 
												END 
										ELSE CASE WHEN META_ANNIO_NORMALIZADO = 0 
													 THEN 0 
												  ELSE (B.VLR_PROYECCION_ANNIO_ESC_ALTO / META_ANNIO_NORMALIZADO)
										     END 
								   END 
						 END 
				 ELSE NULL END AS PRC_CUMP_ANNIO_ESC_ALTO

            FROM
            (
			  SELECT A.*
			        ,CASE WHEN A.[DESC_ESC_BAJO] IS NULL OR A.[DESC_ESC_BAJO] = ''
					       THEN NULL 
						 ELSE A.VLR_PROYECCION_ANNIO_ESC_BAJO_VLD END AS VLR_PROYECCION_ANNIO_ESC_BAJO
				    ,CASE WHEN A.[DESC_ESC_MEDIO] IS NULL OR A.[DESC_ESC_MEDIO] = ''
					       THEN NULL 
						 ELSE A.VLR_PROYECCION_ANNIO_ESC_MEDIO_VLD END AS VLR_PROYECCION_ANNIO_ESC_MEDIO
					,CASE WHEN A.[DESC_ESC_ALTO] IS NULL OR A.[DESC_ESC_ALTO] = ''
					       THEN NULL 
						 ELSE A.VLR_PROYECCION_ANNIO_ESC_ALTO_VLD END AS VLR_PROYECCION_ANNIO_ESC_ALTO
			FROM (
            SELECT
                  A.FK_PARAM_INDICADOR,
                  B.FK_INDICADOR,
                  CAST(A.FK_PERIODO AS VARCHAR) AS FK_PERIODO,
                  A.DESC_PERIODO,
				  FCT.FK_TABLERO,
                  D.[DESC_CAUSA_PERIODO] AS DESC_CAUSAS_DESEMPENO_PERIODO,
                  D.[DESC_CAUSA_ACUMULADO] AS DESC_CAUSAS_DESEMPENO_ACUM,
                  D.[DESC_ESCEN_ALTO] AS DESC_PREMISAS_ESC_ALTO,
                  D.[DESC_ESCEN_MEDIO] AS DESC_PREMISAS_ESC_MEDIO,
                  D.[DESC_ESCEN_BAJO] AS DESC_PREMISAS_ESC_BAJO,
                  D.[DESCR_ACCION] AS DESC_ACCIONES_DE_ASEGURAMIENTO,
                  CASE WHEN C.DESC_META_NORMALIZADA IS NULL 
					      THEN 'No' 
					   ELSE C.DESC_META_NORMALIZADA END AS DESC_META_NORMALIZADA,
                  C.DESC_SENTIDO,     
                  C.DESC_FRECUENCIA,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_REAL_PERIODO) 
					   ELSE ROUND(SUM(A.VLR_REAL_PERIODO),C.CANT_DECIMALES_REPORTE) END AS REAL_PERIODO,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_REAL_ACUM) 
					   ELSE ROUND(SUM(A.VLR_REAL_ACUM),C.CANT_DECIMALES_REPORTE) END AS REAL_ACUMULADO,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_PLAN_PERIODO) 
					   ELSE ROUND(SUM(A.VLR_PLAN_PERIODO),C.CANT_DECIMALES_REPORTE) END AS PLAN_PERIODO,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_PLAN_ACUM) 
					   ELSE ROUND(SUM(A.VLR_PLAN_ACUM),C.CANT_DECIMALES_REPORTE) END AS PLAN_ACUMULADO,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_PLAN_SENSIB_NORM) 
					   ELSE ROUND(SUM(A.VLR_PLAN_SENSIB_NORM),C.CANT_DECIMALES_REPORTE) END AS PLAN_PERIODO_NORMALIZADO,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_PLAN_SENSIB_NORM_ACUM) 
					   ELSE ROUND(SUM(A.VLR_PLAN_SENSIB_NORM_ACUM),C.CANT_DECIMALES_REPORTE) END AS PLAN_ACUMULADO_NORMALIZADO,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_META_ANNIO) 
					   ELSE ROUND(SUM(A.VLR_META_ANNIO),C.CANT_DECIMALES_REPORTE) END AS META_ANNIO,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_PLAN_SENSIB_NORM_ANNIO) 
					   ELSE ROUND(SUM(A.VLR_PLAN_SENSIB_NORM_ANNIO),C.CANT_DECIMALES_REPORTE) END AS META_ANNIO_NORMALIZADO,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_META_ANNIO_1) 
					   ELSE ROUND(SUM(A.VLR_META_ANNIO_1),C.CANT_DECIMALES_REPORTE) END AS META_ANNIO_1,               
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_META_ANNIO_2) 
					   ELSE ROUND(SUM(A.VLR_META_ANNIO_2),C.CANT_DECIMALES_REPORTE) END AS META_ANNIO_2,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_PROYECCION_PERIODO_1) 
					   ELSE ROUND(SUM(A.VLR_PROYECCION_PERIODO_1),C.CANT_DECIMALES_REPORTE) END AS PROYECCION_PERIODO_1,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_PROYECCION_PERIODO_2) 
					   ELSE ROUND(SUM(A.VLR_PROYECCION_PERIODO_2),C.CANT_DECIMALES_REPORTE) END AS PROYECCION_PERIODO_2,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(A.VLR_PROYECCION_PERIODO_3) 
					   ELSE ROUND(SUM(A.VLR_PROYECCION_PERIODO_3),C.CANT_DECIMALES_REPORTE) END AS PROYECCION_PERIODO_3,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(CAST(D.[DESC_ESC_BAJO] AS real)) 
					   ELSE ROUND(SUM(CAST(D.[DESC_ESC_BAJO] AS real)),C.CANT_DECIMALES_REPORTE) END AS VLR_PROYECCION_ANNIO_ESC_BAJO_VLD,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(CAST(D.[DESC_ESC_MEDIO] AS real)) 
					   ELSE ROUND(SUM(CAST(D.[DESC_ESC_MEDIO] AS real)),C.CANT_DECIMALES_REPORTE) END AS VLR_PROYECCION_ANNIO_ESC_MEDIO_VLD,
                  CASE WHEN C.CANT_DECIMALES_REPORTE IS NULL 
					      THEN SUM(CAST(D.[DESC_ESC_ALTO] AS real))   
					   ELSE ROUND(SUM(CAST(D.[DESC_ESC_ALTO] AS real)),C.CANT_DECIMALES_REPORTE) END AS VLR_PROYECCION_ANNIO_ESC_ALTO_VLD,
				 
				  A.FECHA_CARGA_SYNAPSE,
				  A.FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
				  D.[DESC_ESC_MEDIO],
				  D.[DESC_ESC_BAJO],
				  D.[DESC_ESC_ALTO]
                  
                  FROM [ATOMO].[DWH.FACT_DESEMPENO_INDICADOR] AS A
					INNER JOIN [ATOMO].[DWH.DIM_PARAM_INDICADOR] AS B
						ON A.FK_PARAM_INDICADOR = B.GK_PARAM_INDICADOR 
						AND DESC_CONTROL_CARGA <> 'INACTIVO' 
					LEFT JOIN [ATOMO].[DWH.DIM_INDICADOR] AS C
						ON B.FK_INDICADOR = C.GK_INDICADOR 
					LEFT JOIN [ATOMO].[DWH.DIM_ESCENARIOSANALISIS_UX] D
					    ON B.FK_INDICADOR = D.FK_INDICADOR
						AND A.[FK_PERIODO] = D.[NUM_PERIODO]
						AND B.DESC_DETALLE_INDICADOR = D.DESC_DETALLE_INDICADOR
					LEFT JOIN [ATOMO].[DWH.FACT_CONFIGURACION_TABLERO] FCT 
						ON A.FK_PARAM_INDICADOR = FCT.FK_PARAM_INDICADOR
						AND B.FK_INDICADOR = FCT.FK_INDICADOR

                  GROUP BY C.CANT_DECIMALES_REPORTE,
						  A.FK_PARAM_INDICADOR,
						  B.FK_INDICADOR,
						  CAST(A.FK_PERIODO AS VARCHAR),
						  FCT.FK_TABLERO,
						  A.DESC_PERIODO,
						  D.[DESC_CAUSA_PERIODO],
						  D.[DESC_CAUSA_ACUMULADO],
						  D.[DESC_ESCEN_ALTO],
						  D.[DESC_ESCEN_MEDIO],
						  D.[DESC_ESCEN_BAJO],
						  D.[DESCR_ACCION],
						  C.DESC_META_NORMALIZADA,
						  C.DESC_SENTIDO,     
						  C.DESC_FRECUENCIA,
						  A.FECHA_CARGA_SYNAPSE,
						  A.FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
						  D.[DESC_ESC_BAJO],
				          D.[DESC_ESC_MEDIO],
				          D.[DESC_ESC_ALTO]

            ) A
	    ) B
) C