
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-13
-- Description: Se crea la vista CVD_PARAMETRIZACION_INDICADOR la cual es un insumo para el tablero Paneles y TBG's
-- =============================================

CREATE VIEW ATOMO.CVD_PARAMETRIZACION_INDICADOR AS  

SELECT A.GK_PARAM_INDICADOR,
	 A.FK_INDICADOR,
	 B.DESC_NOMBRE_INDICADOR,
	 CAST(CONVERT(VARCHAR(8),A.DTM_FECHA_REGISTRO, 112) AS BIGINT) AS FK_TIEMPO,
	 A.DTM_FECHA_REGISTRO,
	 A.DESC_RESPONSABLE_MEDICION,
	 A.DESC_CARGO_RESPONSABLE_MEDICION,
	 A.DESC_CORREO_RESPONSABLE_MEDICION,
	 A.DESC_AREA_RESPONSABLE_MEDICION,
	 A.ID_UNIDAD_ORGANIZATIVA,
	 A.DESC_RESPONSABLE_MEDICION_2,
	 A.DESC_CARGO_RESPONSABLE_MEDICION_2,
	 A.DESC_CORREO_RESPONSABLE_MEDICION_2,
	 A.DESC_AREA_RESPONSABLE_MEDICION_2,
	 A.ID_UNIDAD_ORGANIZATIVA_2,
	 A.DESC_SIGLA_AREA,
	 A.DESC_DETALLE_INDICADOR,
	 A.DESC_CONTROL_CARGA,
	 B.DESC_INDICADOR_HITO,
	 A.DTM_FECHACARGA 

FROM [ATOMO].[DWH.DIM_PARAM_INDICADOR] A
	LEFT JOIN [ATOMO].[CVD_INDICADOR] B
		ON A.FK_INDICADOR = B.GK_INDICADOR
		
WHERE A.DESC_CONTROL_CARGA NOT IN ('INACTIVO')

