
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-16
-- Description: Se crea la vista CVD_ACTIVIDADES_ENTREGABLES_HITO la cual es un insumo para el tablero Paneles y TBG's
-- =============================================

CREATE VIEW ATOMO.CVD_ACTIVIDADES_ENTREGABLES_HITO AS 

SELECT A.ID_ACTIVIDAD,
	 A.FK_ENTREGABLE_HITO,
	 B.DESC_ENTREGABLE,
	 B.DESC_NOMBRE_INDICADOR,
	 A.DESC_ACTIVIDAD,
	 A.DESC_CUMPLE_PENDIENTE,
	 A.DESC_COMENTARIOS_ACTIVIDAD,
	 A.DTM_FECHA_ACTIVIDAD,
	 A.DTM_FECHACARGA,
	 A.DTM_FECHA_EJECUCION_ACTIVIDAD,
	 A.GK_ACTIVIDAD_ENTREGABLE_HITO 

FROM [ATOMO].[DWH.DIM_ACTIVIDADES_ENTREGABLE_HITO] A
	LEFT JOIN [ATOMO].[CVC_ENTREGABLES_HITO] B
		ON A.[FK_ENTREGABLE_HITO] = B.[GK_ENTREGABLE_HITO]

WHERE A.ID_ACTIVIDAD <> '-999'
