
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-16
-- Description: Se crea la vista CVC_TH_ENTREGABLE_HITO la cual es un insumo para el tablero Paneles y TBG's
-- =============================================

CREATE VIEW ATOMO.CVC_TH_ENTREGABLE_HITO AS 

SELECT C.FK_INDICADOR AS FK_HITO,
	C.FK_PARAM_INDICADOR,
	C.GK_ENTREGABLE_HITO AS FK_ENTREGABLE,
	C.FK_PERIODO,
	D.DTM_FECHA_EJECUCION_REAL,
	D.DESC_CAUSAS,
	D.DESC_ACCIONES,
	D.DESC_PREMISA_ESC_BAJO_ENTREGABLE,
	D.DESC_PREMISA_ESC_MEDIO_ENTREGABLE,
	D.DESC_PREMISA_ESC_ALTO_ENTREGABLE,
	D.DESC_CORREO_USUARIO,
	D.DTM_FECHA_EVENTO_REGISTRO,
	D.DTM_FECHACARGA,
	D.VLR_PLAN_ENTREGABLE,
	D.VLR_REAL_ENTREGABLE,
	D.PRC_CUMP_ENTREGABLE,
	D.VLR_REAL_FINAL_ENTREGABLE,
	D.VLR_PROY_ESC_BAJO_ENTREGABLE,
	D.VLR_PROY_ESC_MEDIO_ENTREGABLE,
	D.VLR_PROY_ESC_ALTO_ENTREGABLE,
	D.VLR_CUMP_ESC_BAJO_ENTREGABLE,
	D.VLR_CUMP_ESC_MEDIO_ENTREGABLE,
	D.VLR_CUMP_ESC_ALTO_ENTREGABLE
 FROM
( 
 	SELECT * FROM
	(	SELECT CAST(COD_PERIODO AS INT) AS FK_PERIODO
		FROM [ATOMO].[CVD_AUX_TIEMPO_CARGA]) AS A
	INNER JOIN
	(
	SELECT 
		GK_ENTREGABLE_HITO,
		FK_INDICADOR,
		FK_PARAM_INDICADOR,
		DTM_FECHA_USAR
	 FROM [ATOMO].[DWH.DIM_ENTREGABLES_HITO]
	) AS B 
  ON  LEFT(A.FK_PERIODO, 4) = YEAR(B.DTM_FECHA_USAR)
) AS C
LEFT JOIN  (SELECT FK_HITO,
			FK_PARAM_INDICADOR,
			FK_ENTREGABLE,
			FK_PERIODO,
			DTM_FECHA_EJECUCION_REAL,
			DESC_CAUSAS,
			DESC_ACCIONES,
			DESC_PREMISA_ESC_BAJO_ENTREGABLE,
			DESC_PREMISA_ESC_MEDIO_ENTREGABLE,
			DESC_PREMISA_ESC_ALTO_ENTREGABLE,
			DESC_CORREO_USUARIO,
			DTM_FECHA_EVENTO_REGISTRO,
			DTM_FECHACARGA,
			VLR_PLAN_ENTREGABLE,
			VLR_REAL_ENTREGABLE,
			PRC_CUMP_ENTREGABLE,
			VLR_REAL_FINAL_ENTREGABLE,
			VLR_PROY_ESC_BAJO_ENTREGABLE,
			VLR_PROY_ESC_MEDIO_ENTREGABLE,
			VLR_PROY_ESC_ALTO_ENTREGABLE,
			VLR_CUMP_ESC_BAJO_ENTREGABLE,
			VLR_CUMP_ESC_MEDIO_ENTREGABLE,
			VLR_CUMP_ESC_ALTO_ENTREGABLE

		 FROM [ATOMO].[DWH.FACT_ENTREGABLE_HITO]
        ) AS D
	ON C.GK_ENTREGABLE_HITO = D.FK_ENTREGABLE 
	AND C.FK_INDICADOR = D.FK_HITO 
	AND C.FK_PARAM_INDICADOR = D.FK_PARAM_INDICADOR 
	AND C.FK_PERIODO = D.FK_PERIODO
