
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-16
-- Description: Se crea la vista CVC_TH_HITO la cual es un insumo para el tablero Paneles y TBG's

-- Updated by:   Oscar Angel
-- Updated Date: 2022-09-02
-- Description: Se adiciona el campo CM_RESUMEN por combinación de las iniciativas ILP y UX
-- =============================================

CREATE VIEW ATOMO.CVC_TH_HITO
AS SELECT
	C.FK_INDICADOR AS FK_HITO,
	C.FK_PARAM_INDICADOR,
	C.FK_TABLERO,
	C.DESC_TABLERO_CVR,
	C.FK_PERIODO,
	D.DESC_CORREO_USUARIO,
	D.DTM_FECHACARGA,
	D.DTM_FECHA_EVENTO_REGISTRO,
	D.VLR_PLAN_HITO,
	D.VLR_REAL_HITO,
	D.PRC_CUMP_HITO,
	D.VLR_PROY_ESC_BAJO,
	D.VLR_PROY_ESC_MEDIO,
	D.VLR_PROY_ESC_ALTO,
	D.FECHA_CARGA_SYNAPSE,
	D.FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
	CM_RESUMEN

 FROM
(
	SELECT B.FK_INDICADOR ,
	B.FK_PARAM_INDICADOR,
	B.FK_TABLERO,
	B.DESC_TABLERO_CVR,
	A.FK_PERIODO,
	B.DESC_ANNIO_REGISTRO FROM
	(
		SELECT CAST(COD_PERIODO AS INT) AS FK_PERIODO
		FROM [ATOMO].[CVD_AUX_TIEMPO_CARGA]) as A
		INNER JOIN
	(
		SELECT
		Z.FK_PARAM_INDICADOR,
		Z.FK_TABLERO,
		Y.FK_INDICADOR,
		Z.DESC_ANNIO_REGISTRO,
		CASE WHEN (Z.DESC_TABLERO_CVR IS NULL) THEN 'No'
			ELSE Z.DESC_TABLERO_CVR END AS DESC_TABLERO_CVR
		FROM [ATOMO].[CVD_CONFIGURACION_TABLERO] AS Z
			INNER JOIN [ATOMO].[CVD_PARAMETRIZACION_INDICADOR] AS Y
				ON Z.FK_PARAM_INDICADOR=Y.GK_PARAM_INDICADOR
		WHERE UPPER(Z.DESC_HITO_INDICADOR) = 'HITO' 
		) AS B ON LEFT(A.FK_PERIODO,4) = B.DESC_ANNIO_REGISTRO
	) AS C
	LEFT JOIN 
	(
	SELECT FK_HITO,
	 	FK_PARAM_INDICADOR,
	 	FK_PERIODO,
	 	DESC_CORREO_USUARIO,
	 	DTM_FECHACARGA,
	 	DTM_FECHA_EVENTO_REGISTRO,
	 	VLR_PLAN_HITO,
		VLR_REAL_HITO,
		PRC_CUMP_HITO,
		VLR_PROY_ESC_BAJO,
		VLR_PROY_ESC_MEDIO,
		VLR_PROY_ESC_ALTO,
		FECHA_CARGA_SYNAPSE,
		FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
		CM_RESUMEN 
	FROM [ATOMO].[DWH.FACT_HITO]
	) AS D
ON C.FK_PARAM_INDICADOR=D.FK_PARAM_INDICADOR 
AND C.FK_PERIODO = D.FK_PERIODO 
AND C.FK_INDICADOR = D.FK_HITO;
