
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-16
-- Description: Se crea la vista CVD_CONTEXTO_HITO la cual es un insumo para el tablero Paneles y TBG's
-- =============================================

CREATE VIEW ATOMO.CVD_CONTEXTO_HITO AS  

SELECT A.FK_INDICADOR AS FK_HITO,
	 C.GK_PARAM_INDICADOR AS FK_PARAM_INDICADOR,
	 D.FK_TABLERO,
	 A.DESC_SPONSOR,
	 B.DESC_NOMBRE_INDICADOR,
	 A.DESC_CONTEXTO_MOTIVACION,
	 A.DESC_OBJETIVO,
	 A.DESC_IMPACTO,
	 A.DESC_MITIGANTES_RIESGO,
	 A.DESC_INTERDEPENDENCIAS,
	 A.DESC_RIESGOS_PRINCIPALES,
	 D.DESC_SIGLA_AREA,
	 A.DTM_FECHA_REGISTRO_CONTEXTO,
	 A.DTM_FECHACARGA,
	 C.FK_TIEMPO,
	 A.VLR_PLAN_HITO 

FROM [ATOMO].[DWH.DIM_CONTEXTO_HITO] A
	LEFT JOIN [ATOMO].[CVD_INDICADOR] B
		ON A.FK_INDICADOR = B.GK_INDICADOR
	LEFT JOIN [ATOMO].[CVD_PARAMETRIZACION_INDICADOR] C
		ON A.FK_INDICADOR = C.[FK_INDICADOR]
	LEFT JOIN [ATOMO].[CVD_CONFIGURACION_TABLERO] D
		ON C.GK_PARAM_INDICADOR = D.FK_PARAM_INDICADOR
