
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-16
-- Description: Se crea la vista CVC_HITO_INDICADOR la cual es un insumo para el tablero Paneles y TBG's

-- Update by:    Oscar Angel
-- Updated Date: 2022-06-30
-- Description:  Se realiza la adición de los campos VLR_LIMITE_SUPERIOR_PERIODO y VLR_LIMITE_INFERIOR_PERIODO los cuales son necesario para visualizar el semaforo "_CC Semaforo TBG Per" de manera correcta en el tablero Paneles y TBG's

-- Update by:   Oscar Angel
-- Updated Date: 2022-09-02
-- Description:  Se realiza la adición de los campos DESC_ESTANDAR, DESC_VERSION, DTM_VIGENCIA_DESDE, CM_RESUMEN por combinación de las iniciativas ILP y UX

-- Update by:   Oscar Angel
-- Updated Date: 2022-09-02
-- Description:  Se realiza ajuste en la manera de calculo del campo PRC_CUMP_ACUMULADO

-- Author:      Oscar Angel
-- Update Date: 2023-06-28
-- Description: Se adiciona los campo Num_Orden_Palanca y Num_Orden_Objetivo

-- =============================================

CREATE VIEW ATOMO.CVC_HITO_INDICADOR

AS SELECT A.FK_TABLERO,
	   A.DESC_TABLERO_CVR,
	   A.DESC_TABLERO,
	   A.DESC_VERSION,
	   A.DESC_GRUPO,
	   A.DESC_EMPRESA,
	   A.DESC_VP_EJECUTIVA,
	   A.DESC_GRUPO_SEGMENTO,
	   A.DESC_SEGMENTO,
	   A.DESC_UNIDAD_NEGOCIO_NVL_2,
	   A.DESC_UNIDAD_NEGOCIO_NVL_3,
	   A.DESC_GERENCIA,
	   A.DESC_RUTINA,
	   A.DESC_SIGLA_AREA,
	   A.DESC_NIVEL,
	   A.DESC_EJE_PALANCA,
	   A.NUM_ORDEN_PALANCA,
	   A.NUM_ORDEN_OBJETIVO,
	   A.DESC_OBJETIVO,
	   B.GK_INDICADOR AS FK_INDICADOR,
	   A.ID_INDICADOR,
	   A.DESC_NOMBRE_INDICADOR,
	   A.FK_PARAM_INDICADOR,
	   A.DESC_DETALLE_INDICADOR,
	   A.DESC_HITO_INDICADOR,
	   A.DESC_FRECUENCIA,
	   A.VLR_PESO_INDICADOR,
	   A.DESC_TIPO_TABLERO,
	   A.DESC_CORTO_LARGO_PLAZO,	 	 
	   B.VLR_LIMITE_INFERIOR,
	   B.VLR_LIMITE_SUPERIOR, 
	   A.DESC_SECUENCIA_ORDEN,
	   A.DESC_REFERENTE,	 
	   A.DESC_RESPONSABLE_MEDICION,
	   A.DESC_CARGO_RESPONSABLE_MEDICION,
	   A.DESC_CORREO_RESPONSABLE_MEDICION,
	   A.DESC_RESPONSABLE_MEDICION_2,
	   A.DESC_CARGO_RESPONSABLE_MEDICION_2,
	   A.DESC_CORREO_RESPONSABLE_MEDICION_2,
	   A.DTM_FECHACARGA, 
	   A.DESC_TBG,
	   B.DESC_ANNIO,			 
	   B.FK_PERIODO,	 
	   B.DESC_PERIODO,
	   B.MES,
	   B.DESC_CAUSAS_DESEMPENO_PERIODO,
	   B.DESC_CAUSAS_DESEMPENO_ACUM,
	   B.DESC_PREMISAS_ESC_ALTO,
	   B.DESC_PREMISAS_ESC_MEDIO,
	   B.DESC_PREMISAS_ESC_BAJO,
	   B.DESC_ACCIONES_DE_ASEGURAMIENTO,
	   B.DESC_META_NORMALIZADA,
	   B.DESC_SENTIDO,
	   B.CANT_DECIMALES_CALCULO,
	   B.CANT_DECIMALES_REPORTE,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.REAL_PERIODO 
			ELSE ROUND(B.REAL_PERIODO,CANT_DECIMALES_REPORTE) END AS REAL_PERIODO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.REAL_ACUMULADO 
			ELSE ROUND(B.REAL_ACUMULADO,CANT_DECIMALES_REPORTE) END AS REAL_ACUMULADO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PLAN_PERIODO 
			ELSE ROUND(B.PLAN_PERIODO,CANT_DECIMALES_REPORTE) END AS PLAN_PERIODO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PLAN_ACUMULADO 
			ELSE ROUND(B.PLAN_ACUMULADO,CANT_DECIMALES_REPORTE) END AS PLAN_ACUMULADO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PLAN_PERIODO_NORMALIZADO 
			ELSE ROUND(B.PLAN_PERIODO_NORMALIZADO,CANT_DECIMALES_REPORTE) END AS PLAN_PERIODO_NORMALIZADO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PLAN_ACUMULADO_NORMALIZADO 
			ELSE ROUND(B.PLAN_ACUMULADO_NORMALIZADO,CANT_DECIMALES_REPORTE) END AS PLAN_ACUMULADO_NORMALIZADO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.META_ANNIO 
			ELSE ROUND(B.META_ANNIO,CANT_DECIMALES_REPORTE) END AS META_ANNIO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.META_ANNIO_NORMALIZADO 
			ELSE ROUND(B.META_ANNIO_NORMALIZADO,CANT_DECIMALES_REPORTE) END AS META_ANNIO_NORMALIZADO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.META_ANNIO_1 
			ELSE ROUND(B.META_ANNIO_1,CANT_DECIMALES_REPORTE) END AS META_ANNIO_1,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.META_ANNIO_2 
			ELSE ROUND(B.META_ANNIO_2,CANT_DECIMALES_REPORTE) END AS META_ANNIO_2,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PROYECCION_PERIODO_1 
			ELSE ROUND(B.PROYECCION_PERIODO_1,CANT_DECIMALES_REPORTE) END AS PROYECCION_PERIODO_1,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PROYECCION_PERIODO_2 
			ELSE ROUND(B.PROYECCION_PERIODO_2,CANT_DECIMALES_REPORTE) END AS PROYECCION_PERIODO_2,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PROYECCION_PERIODO_3 
			ELSE ROUND(B.PROYECCION_PERIODO_3,CANT_DECIMALES_REPORTE) END AS PROYECCION_PERIODO_3,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.VLR_PROYECCION_ANNIO_ESC_BAJO 
			ELSE ROUND(B.VLR_PROYECCION_ANNIO_ESC_BAJO,CANT_DECIMALES_REPORTE) END AS VLR_PROYECCION_ANNIO_ESC_BAJO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.VLR_PROYECCION_ANNIO_ESC_MEDIO 
			ELSE ROUND(B.VLR_PROYECCION_ANNIO_ESC_MEDIO,CANT_DECIMALES_REPORTE) END AS VLR_PROYECCION_ANNIO_ESC_MEDIO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.VLR_PROYECCION_ANNIO_ESC_ALTO 
			ELSE ROUND(B.VLR_PROYECCION_ANNIO_ESC_ALTO,CANT_DECIMALES_REPORTE) END AS VLR_PROYECCION_ANNIO_ESC_ALTO,
 	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PRC_CUMP_PERIODO 
			ELSE ROUND(B.PRC_CUMP_PERIODO*100,CANT_DECIMALES_REPORTE)/100 END AS PRC_CUMP_PERIODO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PRC_CUMP_ACUMULADO 
			ELSE ROUND(B.PRC_CUMP_ACUMULADO*100,CANT_DECIMALES_REPORTE)/100 END AS PRC_CUMP_ACUMULADO,
 	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PRC_CUMP_ANNIO_ESC_BAJO 
			ELSE ROUND(B.PRC_CUMP_ANNIO_ESC_BAJO*100,CANT_DECIMALES_REPORTE)/100 END AS PRC_CUMP_ANNIO_ESC_BAJO,
 	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PRC_CUMP_ANNIO_ESC_MEDIO 
			ELSE ROUND(B.PRC_CUMP_ANNIO_ESC_MEDIO*100,CANT_DECIMALES_REPORTE)/100 END AS PRC_CUMP_ANNIO_ESC_MEDIO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PRC_CUMP_ANNIO_ESC_ALTO 
			ELSE ROUND(B.PRC_CUMP_ANNIO_ESC_ALTO*100,CANT_DECIMALES_REPORTE)/100 END AS PRC_CUMP_ANNIO_ESC_ALTO,
	   B.PRC_DESEMPENO_PERIODO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PRC_DESEMPENO_ACUMULADO 
			ELSE ROUND(B.PRC_DESEMPENO_ACUMULADO*100,CANT_DECIMALES_REPORTE)/100 END AS PRC_DESEMPENO_ACUMULADO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PRC_DESEMPENO_ANNIO_ESC_BAJO 
			ELSE ROUND(B.PRC_DESEMPENO_ANNIO_ESC_BAJO*100,CANT_DECIMALES_REPORTE)/100 END AS PRC_DESEMPENO_ANNIO_ESC_BAJO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PRC_DESEMPENO_ANNIO_ESC_MEDIO 
			ELSE ROUND(B.PRC_DESEMPENO_ANNIO_ESC_MEDIO*100,CANT_DECIMALES_REPORTE)/100 END AS PRC_DESEMPENO_ANNIO_ESC_MEDIO,
	   CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL 
			THEN B.PRC_DESEMPENO_ANNIO_ESC_ALTO 
			ELSE ROUND(B.PRC_DESEMPENO_ANNIO_ESC_ALTO*100,CANT_DECIMALES_REPORTE)/100 END AS PRC_DESEMPENO_ANNIO_ESC_ALTO,
	   C.PRC_LIMITE_INFERIOR_CVR,
	   C.PRC_LIMITE_SUPERIOR_CVR,
	   C.PRC_META_CVR,	 
	   C.DESC_ESTANDAR ,
	   C.DESC_VERSION AS DESC_VERSION_CVR,
	   C.DTM_VIGENCIA_DESDE AS VIGENCIA_CVR,
	   (B.VLR_LIMITE_INFERIOR * B.META_ANNIO) AS VLR_LIMITE_INFERIOR_ANNIO,
	   (B.VLR_LIMITE_SUPERIOR * B.META_ANNIO) AS VLR_LIMITE_SUPERIOR_ANNIO,
	   (B.VLR_LIMITE_INFERIOR * B.PLAN_ACUMULADO) AS VLR_LIMITE_INFERIOR_ACUMULADO,
	   (B.VLR_LIMITE_SUPERIOR * B.PLAN_ACUMULADO) AS VLR_LIMITE_SUPERIOR_ACUMULADO,
       (B.VLR_LIMITE_INFERIOR * B.PLAN_PERIODO) AS VLR_LIMITE_INFERIOR_PERIODO,
	   (B.VLR_LIMITE_SUPERIOR * B.PLAN_PERIODO) AS VLR_LIMITE_SUPERIOR_PERIODO,	   
	   B.META_ANNIO AS META_ANNIO_FINAL,
	   B.FECHA_CARGA_SYNAPSE,
	   B.FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
	   B.CM_RESUMEN

FROM [ATOMO].[CVD_CONFIGURACION_TABLERO]  A
		INNER JOIN
		( 
		   SELECT SUBSTRING(CAST(Z.FK_PERIODO AS VARCHAR(500)),1,4) AS DESC_ANNIO,
			      Z.FK_PARAM_INDICADOR,
			      Z.FK_TABLERO,
			      Z.DESC_TABLERO_CVR,
			      Y.GK_INDICADOR,
			      Z.FK_PERIODO,
			      CAST(Z.FK_PERIODO AS VARCHAR(500)) AS DESC_PERIODO,
			      RIGHT(CAST(Z.FK_PERIODO AS VARCHAR(500)),2) AS MES,		
			      CAST(NULL AS VARCHAR(4000)) AS DESC_CAUSAS_DESEMPENO_PERIODO,
			      CAST(NULL AS VARCHAR(4000)) AS DESC_CAUSAS_DESEMPENO_ACUM,
			      CAST(NULL AS VARCHAR(4000)) AS DESC_PREMISAS_ESC_ALTO,
			      CAST(NULL AS VARCHAR(4000)) AS DESC_PREMISAS_ESC_MEDIO,
			      CAST(NULL AS VARCHAR(4000)) AS DESC_PREMISAS_ESC_BAJO,
			      CAST(NULL AS VARCHAR(4000)) AS DESC_ACCIONES_DE_ASEGURAMIENTO,
			      CASE WHEN Y.DESC_META_NORMALIZADA IS NULL THEN 'No' 
					   ELSE Y.DESC_META_NORMALIZADA END AS DESC_META_NORMALIZADA,
			      Y.DESC_SENTIDO,
			      Y.CANT_DECIMALES_CALCULO,
			      Y.CANT_DECIMALES_REPORTE,
			      CAST(NULL AS DECIMAL(25,10)) AS REAL_PERIODO,
			      CASE WHEN Z.VLR_REAL_HITO IS NULL THEN NULL 
				       ELSE Z.VLR_REAL_HITO * 100 END AS REAL_ACUMULADO,
			      CAST(NULL AS DECIMAL(25,10)) AS PLAN_PERIODO,
			      CASE WHEN Z.VLR_REAL_HITO IS NULL AND right(Z.FK_PERIODO,2)<>12 THEN NULL 
				       ELSE CASE WHEN Z.VLR_PLAN_HITO IS NULL 
					             THEN CASE WHEN W.VLR_PLAN_HITO IS NULL 
								           THEN NULL
								      ELSE W.VLR_PLAN_HITO
							          END
						         ELSE Z.VLR_PLAN_HITO 
							END 
				   END AS PLAN_ACUMULADO,
				  CAST(NULL AS DECIMAL(25,10)) AS PLAN_PERIODO_NORMALIZADO,
				  CAST(NULL AS DECIMAL(25,10)) AS PLAN_ACUMULADO_NORMALIZADO,
				  CASE WHEN W.VLR_PLAN_HITO IS NULL 
				       THEN NULL ELSE W.VLR_PLAN_HITO END AS META_ANNIO,
				  CAST(NULL AS DECIMAL(25,10)) AS META_ANNIO_NORMALIZADO,
				  CAST(NULL AS DECIMAL(25,10)) AS META_ANNIO_1,
				  CAST(NULL AS DECIMAL(25,10)) AS META_ANNIO_2,
				  CAST(NULL AS DECIMAL(25,10)) AS PROYECCION_PERIODO_1,
				  CAST(NULL AS DECIMAL(25,10)) AS PROYECCION_PERIODO_2,
				  CAST(NULL AS DECIMAL(25,10)) AS PROYECCION_PERIODO_3,					
				  CASE WHEN Z.VLR_PROY_ESC_BAJO IS NULL 
					   THEN NULL ELSE Z.VLR_PROY_ESC_BAJO * 100 END AS VLR_PROYECCION_ANNIO_ESC_BAJO,					
				  CASE WHEN Z.VLR_PROY_ESC_MEDIO IS NULL 
					   THEN NULL ELSE Z.VLR_PROY_ESC_MEDIO * 100 END AS VLR_PROYECCION_ANNIO_ESC_MEDIO,										
				  CASE WHEN Z.VLR_PROY_ESC_ALTO IS NULL 
					   THEN NULL ELSE Z.VLR_PROY_ESC_ALTO * 100 END AS VLR_PROYECCION_ANNIO_ESC_ALTO,															
				  CAST(NULL AS DECIMAL(25,10)) AS PRC_CUMP_PERIODO,
				  CASE WHEN Z.PRC_CUMP_HITO IS NULL AND Z.VLR_REAL_HITO IS NULL
					   THEN NULL 
					   WHEN Z.PRC_CUMP_HITO IS NULL AND Z.VLR_REAL_HITO IS NOT NULL
					   THEN Z.VLR_REAL_HITO 
					   ELSE Z.PRC_CUMP_HITO END AS PRC_CUMP_ACUMULADO,
				  CASE WHEN Z.VLR_PROY_ESC_BAJO IS NULL 
					   THEN NULL ELSE Z.VLR_PROY_ESC_BAJO END AS PRC_CUMP_ANNIO_ESC_BAJO,
				  CASE WHEN Z.VLR_PROY_ESC_MEDIO IS NULL 
					   THEN NULL ELSE Z.VLR_PROY_ESC_MEDIO END AS PRC_CUMP_ANNIO_ESC_MEDIO,
				  CASE WHEN Z.VLR_PROY_ESC_ALTO IS NULL 
					   THEN NULL ELSE Z.VLR_PROY_ESC_ALTO END AS PRC_CUMP_ANNIO_ESC_ALTO,
				  CAST(NULL AS DECIMAL(25,10)) AS PRC_DESEMPENO_PERIODO,
				 CASE WHEN Z.PRC_CUMP_HITO IS NULL AND Z.VLR_REAL_HITO IS NOT NULL
					   THEN Z.VLR_REAL_HITO
					   ELSE CASE WHEN Z.PRC_CUMP_HITO > 1.2 
					   THEN 1.2 ELSE Z.PRC_CUMP_HITO END END AS PRC_DESEMPENO_ACUMULADO,
				  CASE WHEN Z.VLR_PROY_ESC_BAJO IS NULL 
					   THEN NULL ELSE CASE WHEN Z.VLR_PROY_ESC_BAJO > 1.2 
					   THEN 1.2 ELSE Z.VLR_PROY_ESC_BAJO END END AS PRC_DESEMPENO_ANNIO_ESC_BAJO,
				  CASE WHEN Z.VLR_PROY_ESC_MEDIO IS NULL 
					   THEN NULL ELSE CASE WHEN Z.VLR_PROY_ESC_MEDIO > 1.2 
					   THEN 1.2 ELSE Z.VLR_PROY_ESC_MEDIO END END AS PRC_DESEMPENO_ANNIO_ESC_MEDIO,
				  CASE WHEN Z.VLR_PROY_ESC_ALTO IS NULL 
					   THEN NULL ELSE CASE WHEN Z.VLR_PROY_ESC_ALTO > 1.2 
					   THEN 1.2 ELSE Z.VLR_PROY_ESC_ALTO END END AS PRC_DESEMPENO_ANNIO_ESC_ALTO,
				  Y.VLR_LIMITE_INFERIOR,
	     		  Y.VLR_LIMITE_SUPERIOR,
				  Z.FECHA_CARGA_SYNAPSE,
	              Z.FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
				  Z.CM_RESUMEN
				  
		   FROM [ATOMO].[CVC_TH_HITO] AS Z
			   INNER JOIN [ATOMO].[DWH.DIM_INDICADOR] Y
					ON Z.FK_HITO=Y.GK_INDICADOR				
			   LEFT JOIN [ATOMO].[CVD_CONTEXTO_HITO] W
					ON Z.FK_PARAM_INDICADOR = W.FK_PARAM_INDICADOR 
					AND Z.FK_TABLERO = W.FK_TABLERO 
		) B
			ON A.FK_PARAM_INDICADOR=B.FK_PARAM_INDICADOR AND A.FK_TABLERO=B.FK_TABLERO
			
		INNER JOIN [ATOMO].[CVD_PARAMETRIZACION_CVR] AS C
			ON LEFT(A.DESC_VERSION,1) = C.DESC_VERSION
			AND A.DESC_ANNIO = CAST(C.DTM_VIGENCIA_DESDE AS VARCHAR(4))
			