
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-23
-- Description: Se crea la vista CVC_HITO_TABLERO la cual es un insumo para el tablero Paneles y TBG's 

-- Updated by:   Oscar Angel
-- Updated Date: 2022-06-30
-- Description: Se realiza la adición de los campos VLR_LIMITE_SUPERIOR_PERIODO y VLR_LIMITE_INFERIOR_PERIODO los cuales son necesario para visualizar el semaforo "_CC Semaforo TBG Per" de manera correcta en el tablero Paneles y TBG's

-- Updated by:   Oscar Angel
-- Updated Date: 2022-09-02
-- Description: Se realiza la adición de los campos CM_RESUMEN, DESC_ESTANDAR, DESC_VERSION_CVR, VIGENCIA_CVR por combinación de las iniciativas ILP y UX

-- Author:      Oscar Angel
-- Update Date: 2023-06-28
-- Description: Se adiciona los campo Num_Orden_Palanca y Num_Orden_Objetivo

-- =============================================

CREATE VIEW ATOMO.CVC_HITO_TABLERO AS 

WITH  SUBNIVEL1

  AS ( SELECT FK_TABLERO
			,DESC_TABLERO_CVR
			,DESC_TABLERO
			,DESC_VERSION
			,DESC_GRUPO
			,DESC_EMPRESA
			,DESC_VP_EJECUTIVA
			,DESC_GRUPO_SEGMENTO
			,DESC_SEGMENTO
			,DESC_UNIDAD_NEGOCIO_NVL_2
			,DESC_UNIDAD_NEGOCIO_NVL_3
			,DESC_GERENCIA
			,DESC_RUTINA
			,DESC_SIGLA_AREA
			,DESC_NIVEL
			,DESC_EJE_PALANCA
			,NUM_ORDEN_PALANCA
	        ,NUM_ORDEN_OBJETIVO
			,DESC_OBJETIVO
			,FK_INDICADOR
			,ID_INDICADOR
			,DESC_NOMBRE_INDICADOR
			,FK_PARAM_INDICADOR
			,DESC_DETALLE_INDICADOR
			,DESC_HITO_INDICADOR
			,DESC_FRECUENCIA
			,VLR_PESO_INDICADOR
			,DESC_TIPO_TABLERO
			,DESC_CORTO_LARGO_PLAZO
			,VLR_LIMITE_INFERIOR
			,VLR_LIMITE_SUPERIOR
			,DESC_SECUENCIA_ORDEN
			,DESC_REFERENTE
			,DESC_RESPONSABLE_MEDICION
			,DESC_CARGO_RESPONSABLE_MEDICION
			,DESC_CORREO_RESPONSABLE_MEDICION
			,DESC_RESPONSABLE_MEDICION_2
			,DESC_CARGO_RESPONSABLE_MEDICION_2
			,DESC_CORREO_RESPONSABLE_MEDICION_2
			,DTM_FECHACARGA
			,DESC_TBG
			,DESC_ANNIO
			,FK_PERIODO
			,DESC_PERIODO
			,MES
			,DESC_CAUSAS_DESEMPENO_PERIODO
			,DESC_CAUSAS_DESEMPENO_ACUM
			,DESC_PREMISAS_ESC_ALTO
			,DESC_PREMISAS_ESC_MEDIO
			,DESC_PREMISAS_ESC_BAJO
			,DESC_ACCIONES_DE_ASEGURAMIENTO
			,DESC_META_NORMALIZADA
			,ISNULL(DESC_SENTIDO,'Positivo') AS DESC_SENTIDO
			,CANT_DECIMALES_CALCULO
			,CANT_DECIMALES_REPORTE
			,REAL_PERIODO
			,REAL_ACUMULADO
			,PLAN_PERIODO
			,PLAN_ACUMULADO
			,PLAN_PERIODO_NORMALIZADO
			,PLAN_ACUMULADO_NORMALIZADO
			,META_ANNIO
			,META_ANNIO_NORMALIZADO
			,META_ANNIO_1
			,META_ANNIO_2
			,PROYECCION_PERIODO_1
			,PROYECCION_PERIODO_2
			,PROYECCION_PERIODO_3
			,VLR_PROYECCION_ANNIO_ESC_BAJO
			,VLR_PROYECCION_ANNIO_ESC_MEDIO
			,VLR_PROYECCION_ANNIO_ESC_ALTO
			,PRC_CUMP_PERIODO
			,PRC_CUMP_ACUMULADO
			,PRC_CUMP_ANNIO_ESC_BAJO
			,PRC_CUMP_ANNIO_ESC_MEDIO
			,PRC_CUMP_ANNIO_ESC_ALTO
			,PRC_DESEMPENO_PERIODO
			,PRC_DESEMPENO_ACUMULADO
			,PRC_DESEMPENO_ANNIO_ESC_BAJO
			,PRC_DESEMPENO_ANNIO_ESC_MEDIO
			,PRC_DESEMPENO_ANNIO_ESC_ALTO
			,PRC_LIMITE_INFERIOR_CVR
			,PRC_LIMITE_SUPERIOR_CVR
			,PRC_META_CVR
			,VLR_LIMITE_INFERIOR_ANNIO
			,VLR_LIMITE_SUPERIOR_ANNIO
			,VLR_LIMITE_INFERIOR_ACUMULADO
			,VLR_LIMITE_SUPERIOR_ACUMULADO
			,VLR_LIMITE_INFERIOR_PERIODO
			,VLR_LIMITE_SUPERIOR_PERIODO			
			,META_ANNIO_FINAL
			,FECHA_CARGA_SYNAPSE
			,FECHA_PROXIMA_ACTUALIZA_SYNAPSE
			,CM_RESUMEN
			,DESC_ESTANDAR
	        ,DESC_VERSION_CVR
	        ,VIGENCIA_CVR
			
		   ,CASE WHEN ((REAL_ACUMULADO = 0 AND VLR_LIMITE_INFERIOR_ANNIO = 0 AND VLR_LIMITE_SUPERIOR_ANNIO = 0)
				    OR (REAL_ACUMULADO IS NULL OR VLR_LIMITE_INFERIOR_ANNIO IS NULL OR VLR_LIMITE_SUPERIOR_ANNIO IS NULL))
				    THEN 3 
				 WHEN (REAL_ACUMULADO > VLR_LIMITE_INFERIOR_ANNIO AND REAL_ACUMULADO < META_ANNIO_FINAL )
					THEN 1
				 WHEN (REAL_ACUMULADO > META_ANNIO_FINAL AND REAL_ACUMULADO < VLR_LIMITE_SUPERIOR_ANNIO)
					THEN 2
				 WHEN (REAL_ACUMULADO < VLR_LIMITE_INFERIOR_ANNIO)
					THEN 3
				 WHEN (REAL_ACUMULADO > VLR_LIMITE_SUPERIOR_ANNIO)
					THEN 4
				 ELSE NULL END AS RECTA_ANNIO
			
		   ,CASE WHEN ((VLR_PROYECCION_ANNIO_ESC_BAJO = 0 AND VLR_LIMITE_INFERIOR_ANNIO = 0 AND VLR_LIMITE_SUPERIOR_ANNIO = 0) 
				    OR (VLR_PROYECCION_ANNIO_ESC_BAJO IS NULL OR VLR_LIMITE_INFERIOR_ANNIO IS NULL )OR (VLR_LIMITE_SUPERIOR_ANNIO IS NULL ))
					THEN 3
				 WHEN (VLR_PROYECCION_ANNIO_ESC_BAJO > VLR_LIMITE_INFERIOR_ANNIO AND VLR_PROYECCION_ANNIO_ESC_BAJO < META_ANNIO_FINAL)
					THEN 1
				 WHEN (VLR_PROYECCION_ANNIO_ESC_BAJO > META_ANNIO_FINAL AND VLR_PROYECCION_ANNIO_ESC_BAJO < VLR_LIMITE_SUPERIOR_ANNIO)
					THEN 2
				 WHEN (VLR_PROYECCION_ANNIO_ESC_BAJO < VLR_LIMITE_INFERIOR_ANNIO)
					THEN 3
				 WHEN (VLR_PROYECCION_ANNIO_ESC_BAJO > VLR_LIMITE_SUPERIOR_ANNIO)
					THEN 4
				 ELSE NULL END AS RECTA_ANNIO_ESC_BAJO
			
			
		   ,CASE WHEN ((VLR_PROYECCION_ANNIO_ESC_MEDIO = 0 AND VLR_LIMITE_INFERIOR_ANNIO = 0 AND VLR_LIMITE_SUPERIOR_ANNIO = 0) 
				    OR (VLR_PROYECCION_ANNIO_ESC_MEDIO IS NULL OR VLR_LIMITE_INFERIOR_ANNIO IS NULL) OR (VLR_LIMITE_SUPERIOR_ANNIO IS NULL))
					THEN 3
				 WHEN (VLR_PROYECCION_ANNIO_ESC_MEDIO > VLR_LIMITE_INFERIOR_ANNIO AND VLR_PROYECCION_ANNIO_ESC_MEDIO < META_ANNIO_FINAL)
					THEN 1
				 WHEN (VLR_PROYECCION_ANNIO_ESC_MEDIO > META_ANNIO_FINAL AND VLR_PROYECCION_ANNIO_ESC_MEDIO < VLR_LIMITE_SUPERIOR_ANNIO)
					THEN 2
				 WHEN (VLR_PROYECCION_ANNIO_ESC_MEDIO < VLR_LIMITE_INFERIOR_ANNIO)
					THEN 3
				 WHEN (VLR_PROYECCION_ANNIO_ESC_MEDIO > VLR_LIMITE_SUPERIOR_ANNIO)
					THEN 4
				 ELSE NULL END AS RECTA_ANNIO_ESC_MEDIO
			
			
		   ,CASE WHEN ((VLR_PROYECCION_ANNIO_ESC_ALTO = 0 AND VLR_LIMITE_INFERIOR_ANNIO = 0 AND VLR_LIMITE_SUPERIOR_ANNIO = 0 ) 
				    OR (VLR_PROYECCION_ANNIO_ESC_ALTO IS NULL OR VLR_LIMITE_INFERIOR_ANNIO  IS NULL) OR (VLR_LIMITE_SUPERIOR_ANNIO IS NULL))
					THEN 3
				 WHEN (VLR_PROYECCION_ANNIO_ESC_ALTO > VLR_LIMITE_INFERIOR_ANNIO AND VLR_PROYECCION_ANNIO_ESC_ALTO < META_ANNIO_FINAL)
					THEN 1
				 WHEN (VLR_PROYECCION_ANNIO_ESC_ALTO > META_ANNIO_FINAL AND VLR_PROYECCION_ANNIO_ESC_ALTO < VLR_LIMITE_SUPERIOR_ANNIO)
					THEN 2
				 WHEN (VLR_PROYECCION_ANNIO_ESC_ALTO < VLR_LIMITE_INFERIOR_ANNIO)
					THEN 3
				 WHEN (VLR_PROYECCION_ANNIO_ESC_ALTO > VLR_LIMITE_SUPERIOR_ANNIO)
					THEN 4
				 ELSE NULL END AS RECTA_ANNIO_ESC_ALTO
							  
		FROM [ATOMO].[CVC_HITO_INDICADOR]),  
 
  SUBNIVEL2   
  AS ( SELECT A.FK_TABLERO
			   ,A.DESC_TABLERO_CVR
			   ,A.DESC_TABLERO
			   ,A.DESC_VERSION
			   ,A.DESC_GRUPO
			   ,A.DESC_EMPRESA
			   ,A.DESC_VP_EJECUTIVA
			   ,A.DESC_GRUPO_SEGMENTO
			   ,A.DESC_SEGMENTO
			   ,A.DESC_UNIDAD_NEGOCIO_NVL_2
			   ,A.DESC_UNIDAD_NEGOCIO_NVL_3
			   ,A.DESC_GERENCIA
			   ,A.DESC_RUTINA
			   ,A.DESC_SIGLA_AREA
			   ,A.DESC_NIVEL
			   ,A.DESC_EJE_PALANCA
			   ,A.NUM_ORDEN_PALANCA
	           ,A.NUM_ORDEN_OBJETIVO
			   ,A.DESC_OBJETIVO
			   ,A.FK_INDICADOR
			   ,A.ID_INDICADOR
			   ,A.DESC_NOMBRE_INDICADOR
			   ,A.FK_PARAM_INDICADOR
			   ,A.DESC_DETALLE_INDICADOR
			   ,A.DESC_HITO_INDICADOR
			   ,A.DESC_FRECUENCIA
			   ,A.VLR_PESO_INDICADOR
			   ,A.DESC_TIPO_TABLERO
			   ,A.DESC_CORTO_LARGO_PLAZO
			   ,A.VLR_LIMITE_INFERIOR
			   ,A.VLR_LIMITE_SUPERIOR
			   ,A.DESC_SECUENCIA_ORDEN
			   ,A.DESC_REFERENTE
			   ,A.DESC_RESPONSABLE_MEDICION
			   ,A.DESC_CARGO_RESPONSABLE_MEDICION
			   ,A.DESC_CORREO_RESPONSABLE_MEDICION
			   ,A.DESC_RESPONSABLE_MEDICION_2
			   ,A.DESC_CARGO_RESPONSABLE_MEDICION_2
			   ,A.DESC_CORREO_RESPONSABLE_MEDICION_2
			   ,A.DTM_FECHACARGA
			   ,A.DESC_TBG
			   ,A.DESC_ANNIO
			   ,A.FK_PERIODO
			   ,A.DESC_PERIODO
			   ,A.MES
			   ,A.DESC_CAUSAS_DESEMPENO_PERIODO
			   ,A.DESC_CAUSAS_DESEMPENO_ACUM
			   ,A.DESC_PREMISAS_ESC_ALTO
			   ,A.DESC_PREMISAS_ESC_MEDIO
			   ,A.DESC_PREMISAS_ESC_BAJO
			   ,A.DESC_ACCIONES_DE_ASEGURAMIENTO
			   ,A.DESC_META_NORMALIZADA
			   ,A.DESC_SENTIDO
			   ,A.CANT_DECIMALES_CALCULO
			   ,A.CANT_DECIMALES_REPORTE
			   ,A.REAL_PERIODO
			   ,A.REAL_ACUMULADO
			   ,A.PLAN_PERIODO
			   ,A.PLAN_ACUMULADO
			   ,A.PLAN_PERIODO_NORMALIZADO
			   ,A.PLAN_ACUMULADO_NORMALIZADO
			   ,A.META_ANNIO
			   ,A.META_ANNIO_NORMALIZADO
			   ,A.META_ANNIO_1
			   ,A.META_ANNIO_2
			   ,A.PROYECCION_PERIODO_1
			   ,A.PROYECCION_PERIODO_2
			   ,A.PROYECCION_PERIODO_3
			   ,A.VLR_PROYECCION_ANNIO_ESC_BAJO
			   ,A.VLR_PROYECCION_ANNIO_ESC_MEDIO
			   ,A.VLR_PROYECCION_ANNIO_ESC_ALTO
			   ,A.PRC_CUMP_PERIODO
			   ,A.PRC_CUMP_ACUMULADO
			   ,A.PRC_CUMP_ANNIO_ESC_BAJO
			   ,A.PRC_CUMP_ANNIO_ESC_MEDIO
			   ,A.PRC_CUMP_ANNIO_ESC_ALTO
			   ,A.PRC_DESEMPENO_PERIODO
			   ,A.PRC_DESEMPENO_ACUMULADO
			   ,A.PRC_DESEMPENO_ANNIO_ESC_BAJO
			   ,A.PRC_DESEMPENO_ANNIO_ESC_MEDIO
			   ,A.PRC_DESEMPENO_ANNIO_ESC_ALTO
			   ,A.PRC_LIMITE_INFERIOR_CVR
			   ,A.PRC_LIMITE_SUPERIOR_CVR
			   ,A.PRC_META_CVR
			   ,A.VLR_LIMITE_INFERIOR_ANNIO
			   ,A.VLR_LIMITE_SUPERIOR_ANNIO
			   ,A.VLR_LIMITE_INFERIOR_ACUMULADO
			   ,A.VLR_LIMITE_SUPERIOR_ACUMULADO
			   ,A.VLR_LIMITE_INFERIOR_PERIODO
			   ,A.VLR_LIMITE_SUPERIOR_PERIODO
			   ,A.META_ANNIO_FINAL
			   ,A.FECHA_CARGA_SYNAPSE
			   ,A.FECHA_PROXIMA_ACTUALIZA_SYNAPSE
			   ,A.CM_RESUMEN
			   ,A.DESC_ESTANDAR
	           ,A.DESC_VERSION_CVR
	           ,A.VIGENCIA_CVR			   
			   ,A.RECTA_ANNIO
			   ,A.RECTA_ANNIO_ESC_BAJO
			   ,A.RECTA_ANNIO_ESC_MEDIO
			   ,A.RECTA_ANNIO_ESC_ALTO
			   
		 	   ,CASE WHEN (A.MES <> 12)
					    THEN NULL
				     WHEN A.RECTA_ANNIO = 1 AND NOT(A.PRC_LIMITE_INFERIOR_CVR IS NULL)
					    THEN (A.PRC_META_CVR - A.PRC_LIMITE_INFERIOR_CVR) / (A.META_ANNIO_FINAL - A.VLR_LIMITE_INFERIOR_ANNIO)
				     WHEN (A.RECTA_ANNIO = 2 AND NOT(A.PRC_LIMITE_SUPERIOR_CVR IS NULL))
					    THEN (A.PRC_LIMITE_SUPERIOR_CVR - A.PRC_META_CVR) / (A.VLR_LIMITE_SUPERIOR_ANNIO - A.META_ANNIO_FINAL)
				 ELSE NULL END AS P_ANNIO,

				CASE WHEN (A.RECTA_ANNIO_ESC_BAJO = 1 AND NOT(A.PRC_LIMITE_INFERIOR_CVR IS NULL))
						THEN (A.PRC_META_CVR - A.PRC_LIMITE_INFERIOR_CVR) / (A.META_ANNIO_FINAL - A.VLR_LIMITE_INFERIOR_ANNIO)
				     WHEN A.RECTA_ANNIO_ESC_BAJO = 2 AND NOT(A.PRC_LIMITE_SUPERIOR_CVR IS NULL)
						THEN (A.PRC_LIMITE_SUPERIOR_CVR - A.PRC_META_CVR) / (A.VLR_LIMITE_SUPERIOR_ANNIO - A.META_ANNIO_FINAL)
				     ELSE NULL END AS P_ESC_BAJO,				


				CASE WHEN (A.RECTA_ANNIO_ESC_MEDIO = 1 AND NOT (A.PRC_LIMITE_INFERIOR_CVR IS NULL))
						THEN (A.PRC_META_CVR - A.PRC_LIMITE_INFERIOR_CVR) / (A.META_ANNIO_FINAL - A.VLR_LIMITE_INFERIOR_ANNIO)
					 WHEN A.RECTA_ANNIO_ESC_MEDIO = 2 AND NOT (A.PRC_LIMITE_SUPERIOR_CVR IS NULL)
						THEN (A.PRC_LIMITE_SUPERIOR_CVR - A.PRC_META_CVR) / (A.VLR_LIMITE_SUPERIOR_ANNIO - A.META_ANNIO_FINAL)
					 ELSE NULL END AS P_ESC_MEDIO,	

				CASE WHEN (A.RECTA_ANNIO_ESC_ALTO = 1 AND NOT(A.PRC_LIMITE_INFERIOR_CVR IS NULL))
						THEN (A.PRC_META_CVR - A.PRC_LIMITE_INFERIOR_CVR) / (A.META_ANNIO_FINAL - A.VLR_LIMITE_INFERIOR_ANNIO)
					 WHEN (A.RECTA_ANNIO_ESC_ALTO = 2 AND NOT(A.PRC_LIMITE_SUPERIOR_CVR IS NULL))
						THEN ((A.PRC_LIMITE_SUPERIOR_CVR - A.PRC_META_CVR) / (A.VLR_LIMITE_SUPERIOR_ANNIO - A.META_ANNIO_FINAL))
					 ELSE NULL END AS P_ESC_ALTO  
								
       FROM SUBNIVEL1 A ),

  SUBNIVEL3
  AS ( SELECT B.FK_TABLERO
		,B.DESC_TABLERO_CVR
		,B.DESC_TABLERO
		,B.DESC_VERSION
		,B.DESC_GRUPO
		,B.DESC_EMPRESA
		,B.DESC_VP_EJECUTIVA
		,B.DESC_GRUPO_SEGMENTO
		,B.DESC_SEGMENTO
		,B.DESC_UNIDAD_NEGOCIO_NVL_2
		,B.DESC_UNIDAD_NEGOCIO_NVL_3
		,B.DESC_GERENCIA
		,B.DESC_RUTINA
		,B.DESC_SIGLA_AREA
		,B.DESC_NIVEL
		,B.DESC_EJE_PALANCA
		,B.NUM_ORDEN_PALANCA
	    ,B.NUM_ORDEN_OBJETIVO
		,B.DESC_OBJETIVO
		,B.FK_INDICADOR
		,B.ID_INDICADOR
		,B.DESC_NOMBRE_INDICADOR
		,B.FK_PARAM_INDICADOR
		,B.DESC_DETALLE_INDICADOR
		,B.DESC_HITO_INDICADOR
		,B.DESC_FRECUENCIA
		,B.VLR_PESO_INDICADOR
		,B.DESC_TIPO_TABLERO
		,B.DESC_CORTO_LARGO_PLAZO
		,B.VLR_LIMITE_INFERIOR
		,B.VLR_LIMITE_SUPERIOR
		,B.DESC_SECUENCIA_ORDEN
		,B.DESC_REFERENTE
		,B.DESC_RESPONSABLE_MEDICION
		,B.DESC_CARGO_RESPONSABLE_MEDICION
		,B.DESC_CORREO_RESPONSABLE_MEDICION
		,B.DESC_RESPONSABLE_MEDICION_2
		,B.DESC_CARGO_RESPONSABLE_MEDICION_2
		,B.DESC_CORREO_RESPONSABLE_MEDICION_2
		,B.DTM_FECHACARGA
		,B.DESC_TBG
		,B.DESC_ANNIO
		,B.FK_PERIODO
		,B.DESC_PERIODO
		,B.MES
		,B.DESC_CAUSAS_DESEMPENO_PERIODO
		,B.DESC_CAUSAS_DESEMPENO_ACUM
		,B.DESC_PREMISAS_ESC_ALTO
		,B.DESC_PREMISAS_ESC_MEDIO
		,B.DESC_PREMISAS_ESC_BAJO
		,B.DESC_ACCIONES_DE_ASEGURAMIENTO
		,B.DESC_META_NORMALIZADA
		,B.DESC_SENTIDO
		,B.CANT_DECIMALES_CALCULO
		,B.CANT_DECIMALES_REPORTE
		,B.REAL_PERIODO
		,B.REAL_ACUMULADO
		,B.PLAN_PERIODO
		,B.PLAN_ACUMULADO
		,B.PLAN_PERIODO_NORMALIZADO
		,B.PLAN_ACUMULADO_NORMALIZADO
		,B.META_ANNIO
		,B.META_ANNIO_NORMALIZADO
		,B.META_ANNIO_1
		,B.META_ANNIO_2
		,B.PROYECCION_PERIODO_1
		,B.PROYECCION_PERIODO_2
		,B.PROYECCION_PERIODO_3
		,B.VLR_PROYECCION_ANNIO_ESC_BAJO
		,B.VLR_PROYECCION_ANNIO_ESC_MEDIO
		,B.VLR_PROYECCION_ANNIO_ESC_ALTO
		,B.PRC_CUMP_PERIODO
		,B.PRC_CUMP_ACUMULADO
		,B.PRC_CUMP_ANNIO_ESC_BAJO
		,B.PRC_CUMP_ANNIO_ESC_MEDIO
		,B.PRC_CUMP_ANNIO_ESC_ALTO
		,B.PRC_DESEMPENO_PERIODO
		,B.PRC_DESEMPENO_ACUMULADO
		,B.PRC_DESEMPENO_ANNIO_ESC_BAJO
		,B.PRC_DESEMPENO_ANNIO_ESC_MEDIO
		,B.PRC_DESEMPENO_ANNIO_ESC_ALTO
		,B.PRC_LIMITE_INFERIOR_CVR
		,B.PRC_LIMITE_SUPERIOR_CVR
		,B.PRC_META_CVR
		,B.VLR_LIMITE_INFERIOR_ANNIO
		,B.VLR_LIMITE_SUPERIOR_ANNIO
		,B.VLR_LIMITE_INFERIOR_ACUMULADO
		,B.VLR_LIMITE_SUPERIOR_ACUMULADO
		,B.VLR_LIMITE_INFERIOR_PERIODO
		,B.VLR_LIMITE_SUPERIOR_PERIODO
		,B.META_ANNIO_FINAL
		,B.FECHA_CARGA_SYNAPSE
		,B.FECHA_PROXIMA_ACTUALIZA_SYNAPSE
		,B.CM_RESUMEN
		,B.DESC_ESTANDAR
	    ,B.DESC_VERSION_CVR
	    ,B.VIGENCIA_CVR	
		,B.RECTA_ANNIO
		,B.RECTA_ANNIO_ESC_BAJO
		,B.RECTA_ANNIO_ESC_MEDIO
		,B.RECTA_ANNIO_ESC_ALTO
		,B.P_ANNIO
		,B.P_ESC_BAJO
		,B.P_ESC_MEDIO
		,B.P_ESC_ALTO 
		
	    ,CASE WHEN (B.P_ANNIO IS NULL)
				THEN NULL 
			  ELSE (B.P_ANNIO * META_ANNIO_FINAL) END AS PX_ANNIO
			  
		,CASE WHEN (B.P_ESC_BAJO IS NULL)
				THEN NULL 
			  ELSE (B.P_ESC_BAJO * B.META_ANNIO_FINAL) END AS PX_ESC_BAJO
			  
		,CASE WHEN (B.P_ESC_MEDIO IS NULL)
				THEN NULL 
			  ELSE (B.P_ESC_MEDIO * B.META_ANNIO_FINAL) END AS PX_ESC_MEDIO
			  
		,CASE WHEN (B.P_ESC_ALTO IS NULL)
				THEN NULL 
			  ELSE (B.P_ESC_ALTO * B.META_ANNIO_FINAL) END AS PX_ESC_ALTO

		FROM  SUBNIVEL2 B ),

 SUBNIVEL4  
  AS (  SELECT B.FK_TABLERO
		,B.DESC_TABLERO_CVR
		,B.DESC_TABLERO
		,B.DESC_VERSION
		,B.DESC_GRUPO
		,B.DESC_EMPRESA
		,B.DESC_VP_EJECUTIVA
		,B.DESC_GRUPO_SEGMENTO
		,B.DESC_SEGMENTO
		,B.DESC_UNIDAD_NEGOCIO_NVL_2
		,B.DESC_UNIDAD_NEGOCIO_NVL_3
		,B.DESC_GERENCIA
		,B.DESC_RUTINA
		,B.DESC_SIGLA_AREA
		,B.DESC_NIVEL
		,B.DESC_EJE_PALANCA
		,B.NUM_ORDEN_PALANCA
	    ,B.NUM_ORDEN_OBJETIVO
		,B.DESC_OBJETIVO
		,B.FK_INDICADOR
		,B.ID_INDICADOR
		,B.DESC_NOMBRE_INDICADOR
		,B.FK_PARAM_INDICADOR
		,B.DESC_DETALLE_INDICADOR
		,B.DESC_HITO_INDICADOR
		,B.DESC_FRECUENCIA
		,B.VLR_PESO_INDICADOR
		,B.DESC_TIPO_TABLERO
		,B.DESC_CORTO_LARGO_PLAZO
		,B.VLR_LIMITE_INFERIOR
		,B.VLR_LIMITE_SUPERIOR
		,B.DESC_SECUENCIA_ORDEN
		,B.DESC_REFERENTE
		,B.DESC_RESPONSABLE_MEDICION
		,B.DESC_CARGO_RESPONSABLE_MEDICION
		,B.DESC_CORREO_RESPONSABLE_MEDICION
		,B.DESC_RESPONSABLE_MEDICION_2
		,B.DESC_CARGO_RESPONSABLE_MEDICION_2
		,B.DESC_CORREO_RESPONSABLE_MEDICION_2
		,B.DTM_FECHACARGA
		,B.DESC_TBG
		,B.DESC_ANNIO
		,B.FK_PERIODO
		,B.DESC_PERIODO
		,B.MES
		,B.DESC_CAUSAS_DESEMPENO_PERIODO
		,B.DESC_CAUSAS_DESEMPENO_ACUM
		,B.DESC_PREMISAS_ESC_ALTO
		,B.DESC_PREMISAS_ESC_MEDIO
		,B.DESC_PREMISAS_ESC_BAJO
		,B.DESC_ACCIONES_DE_ASEGURAMIENTO
		,B.DESC_META_NORMALIZADA
		,B.DESC_SENTIDO
		,B.CANT_DECIMALES_CALCULO
		,B.CANT_DECIMALES_REPORTE
		,B.REAL_PERIODO
		,B.REAL_ACUMULADO
		,B.PLAN_PERIODO
		,B.PLAN_ACUMULADO
		,B.PLAN_PERIODO_NORMALIZADO
		,B.PLAN_ACUMULADO_NORMALIZADO
		,B.META_ANNIO
		,B.META_ANNIO_NORMALIZADO
		,B.META_ANNIO_1
		,B.META_ANNIO_2
		,B.PROYECCION_PERIODO_1
		,B.PROYECCION_PERIODO_2
		,B.PROYECCION_PERIODO_3
		,B.VLR_PROYECCION_ANNIO_ESC_BAJO
		,B.VLR_PROYECCION_ANNIO_ESC_MEDIO
		,B.VLR_PROYECCION_ANNIO_ESC_ALTO
		,B.PRC_CUMP_PERIODO
		,B.PRC_CUMP_ACUMULADO
		,B.PRC_CUMP_ANNIO_ESC_BAJO
		,B.PRC_CUMP_ANNIO_ESC_MEDIO
		,B.PRC_CUMP_ANNIO_ESC_ALTO
		,B.PRC_DESEMPENO_PERIODO
		,B.PRC_DESEMPENO_ACUMULADO
		,B.PRC_DESEMPENO_ANNIO_ESC_BAJO
		,B.PRC_DESEMPENO_ANNIO_ESC_MEDIO
		,B.PRC_DESEMPENO_ANNIO_ESC_ALTO
		,B.PRC_LIMITE_INFERIOR_CVR
		,B.PRC_LIMITE_SUPERIOR_CVR
		,B.PRC_META_CVR
		,B.VLR_LIMITE_INFERIOR_ANNIO
		,B.VLR_LIMITE_SUPERIOR_ANNIO
		,B.VLR_LIMITE_INFERIOR_ACUMULADO
		,B.VLR_LIMITE_SUPERIOR_ACUMULADO
		,B.VLR_LIMITE_INFERIOR_PERIODO
		,B.VLR_LIMITE_SUPERIOR_PERIODO
		,B.META_ANNIO_FINAL
	    ,B.FECHA_CARGA_SYNAPSE
	    ,B.FECHA_PROXIMA_ACTUALIZA_SYNAPSE
		,B.CM_RESUMEN
		,B.DESC_ESTANDAR
	    ,B.DESC_VERSION_CVR
	    ,B.VIGENCIA_CVR	
		,B.RECTA_ANNIO
		,B.RECTA_ANNIO_ESC_BAJO
		,B.RECTA_ANNIO_ESC_MEDIO
		,B.RECTA_ANNIO_ESC_ALTO
		,B.P_ANNIO
		,B.P_ESC_BAJO
		,B.P_ESC_MEDIO
		,B.P_ESC_ALTO 
		,PX_ANNIO
		,PX_ESC_BAJO
		,PX_ESC_MEDIO
		,PX_ESC_ALTO
  
        ,(B.PRC_META_CVR - B.PX_ANNIO) AS B_ANNIO		
        ,(B.PRC_META_CVR - B.PX_ESC_BAJO) AS B_ESC_BAJO
		,(B.PRC_META_CVR - B.PX_ESC_MEDIO) AS B_ESC_MEDIO
		,(B.PRC_META_CVR - B.PX_ESC_ALTO) AS B_ESC_ALTO
 
 		FROM  SUBNIVEL3 B ),
	 
  SUBNIVEL5  
  AS (  SELECT B.FK_TABLERO
		,B.DESC_TABLERO_CVR
		,B.DESC_TABLERO
		,B.DESC_VERSION
		,B.DESC_GRUPO
		,B.DESC_EMPRESA
		,B.DESC_VP_EJECUTIVA
		,B.DESC_GRUPO_SEGMENTO
		,B.DESC_SEGMENTO
		,B.DESC_UNIDAD_NEGOCIO_NVL_2
		,B.DESC_UNIDAD_NEGOCIO_NVL_3
		,B.DESC_GERENCIA
		,B.DESC_RUTINA
		,B.DESC_SIGLA_AREA
		,B.DESC_NIVEL
		,B.DESC_EJE_PALANCA
		,B.NUM_ORDEN_PALANCA
	    ,B.NUM_ORDEN_OBJETIVO
		,B.DESC_OBJETIVO
		,B.FK_INDICADOR
		,B.ID_INDICADOR
		,B.DESC_NOMBRE_INDICADOR
		,B.FK_PARAM_INDICADOR
		,B.DESC_DETALLE_INDICADOR
		,B.DESC_HITO_INDICADOR
		,B.DESC_FRECUENCIA
		,B.VLR_PESO_INDICADOR
		,B.DESC_TIPO_TABLERO
		,B.DESC_CORTO_LARGO_PLAZO
		,B.VLR_LIMITE_INFERIOR
		,B.VLR_LIMITE_SUPERIOR
		,B.DESC_SECUENCIA_ORDEN
		,B.DESC_REFERENTE
		,B.DESC_RESPONSABLE_MEDICION
		,B.DESC_CARGO_RESPONSABLE_MEDICION
		,B.DESC_CORREO_RESPONSABLE_MEDICION
		,B.DESC_RESPONSABLE_MEDICION_2
		,B.DESC_CARGO_RESPONSABLE_MEDICION_2
		,B.DESC_CORREO_RESPONSABLE_MEDICION_2
		,B.DTM_FECHACARGA
		,B.DESC_TBG
		,B.DESC_ANNIO
		,B.FK_PERIODO
		,B.DESC_PERIODO
		,B.MES
		,B.DESC_CAUSAS_DESEMPENO_PERIODO
		,B.DESC_CAUSAS_DESEMPENO_ACUM
		,B.DESC_PREMISAS_ESC_ALTO
		,B.DESC_PREMISAS_ESC_MEDIO
		,B.DESC_PREMISAS_ESC_BAJO
		,B.DESC_ACCIONES_DE_ASEGURAMIENTO
		,B.DESC_META_NORMALIZADA
		,B.DESC_SENTIDO
		,B.CANT_DECIMALES_CALCULO
		,B.CANT_DECIMALES_REPORTE
		,B.REAL_PERIODO
		,B.REAL_ACUMULADO
		,B.PLAN_PERIODO
		,B.PLAN_ACUMULADO
		,B.PLAN_PERIODO_NORMALIZADO
		,B.PLAN_ACUMULADO_NORMALIZADO
		,B.META_ANNIO
		,B.META_ANNIO_NORMALIZADO
		,B.META_ANNIO_1
		,B.META_ANNIO_2
		,B.PROYECCION_PERIODO_1
		,B.PROYECCION_PERIODO_2
		,B.PROYECCION_PERIODO_3
		,B.VLR_PROYECCION_ANNIO_ESC_BAJO
		,B.VLR_PROYECCION_ANNIO_ESC_MEDIO
		,B.VLR_PROYECCION_ANNIO_ESC_ALTO
		,B.PRC_CUMP_PERIODO
		,B.PRC_CUMP_ACUMULADO
		,B.PRC_CUMP_ANNIO_ESC_BAJO
		,B.PRC_CUMP_ANNIO_ESC_MEDIO
		,B.PRC_CUMP_ANNIO_ESC_ALTO
		,B.PRC_DESEMPENO_PERIODO
		,B.PRC_DESEMPENO_ACUMULADO
		,B.PRC_DESEMPENO_ANNIO_ESC_BAJO
		,B.PRC_DESEMPENO_ANNIO_ESC_MEDIO
		,B.PRC_DESEMPENO_ANNIO_ESC_ALTO
		,B.PRC_LIMITE_INFERIOR_CVR
		,B.PRC_LIMITE_SUPERIOR_CVR
		,B.PRC_META_CVR
		,B.VLR_LIMITE_INFERIOR_ANNIO
		,B.VLR_LIMITE_SUPERIOR_ANNIO
		,B.VLR_LIMITE_INFERIOR_ACUMULADO
		,B.VLR_LIMITE_SUPERIOR_ACUMULADO
		,B.VLR_LIMITE_INFERIOR_PERIODO
		,B.VLR_LIMITE_SUPERIOR_PERIODO
		,B.META_ANNIO_FINAL
	    ,B.FECHA_CARGA_SYNAPSE
	    ,B.FECHA_PROXIMA_ACTUALIZA_SYNAPSE
		,B.CM_RESUMEN
		,B.DESC_ESTANDAR
	    ,B.DESC_VERSION_CVR
	    ,B.VIGENCIA_CVR	
		,B.RECTA_ANNIO
		,B.RECTA_ANNIO_ESC_BAJO
		,B.RECTA_ANNIO_ESC_MEDIO
		,B.RECTA_ANNIO_ESC_ALTO
		,B.P_ANNIO
		,B.P_ESC_BAJO
		,B.P_ESC_MEDIO
		,B.P_ESC_ALTO 
		,PX_ANNIO
		,PX_ESC_BAJO
		,PX_ESC_MEDIO
		,PX_ESC_ALTO
        ,B_ANNIO		
        ,B_ESC_BAJO
		,B_ESC_MEDIO
		,B_ESC_ALTO
		
		,CASE WHEN (B.MES <> 12) OR (B.REAL_ACUMULADO IS NULL)
				 THEN NULL
			  WHEN (B.REAL_ACUMULADO = 0 AND B.META_ANNIO_FINAL = 0)
				  THEN 1
			  WHEN ((B.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND (B.REAL_ACUMULADO > B.META_ANNIO_FINAL))
				 THEN B.PRC_META_CVR
			  WHEN ((B.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND (B.REAL_ACUMULADO < B.META_ANNIO_FINAL))
				 THEN 0
			  WHEN ((B.REAL_ACUMULADO = 0 AND B.VLR_LIMITE_INFERIOR_ANNIO = 0 AND B.VLR_LIMITE_SUPERIOR_ANNIO = 0)
			      OR ((B.REAL_ACUMULADO IS NULL) OR (B.VLR_LIMITE_INFERIOR_ANNIO IS NULL) OR (B.VLR_LIMITE_SUPERIOR_ANNIO IS NULL)))
				 THEN 0
			  WHEN (B.REAL_ACUMULADO >= B.VLR_LIMITE_SUPERIOR_ANNIO)
				 THEN B.PRC_LIMITE_SUPERIOR_CVR
			  WHEN (B.REAL_ACUMULADO < B.VLR_LIMITE_INFERIOR_ANNIO)
				 THEN 0
			  WHEN (B.REAL_ACUMULADO = B.VLR_LIMITE_INFERIOR_ANNIO)
				 THEN B.PRC_LIMITE_INFERIOR_CVR
			  WHEN (B.REAL_ACUMULADO = B.META_ANNIO_FINAL)
				 THEN B.PRC_META_CVR 	 
			  ELSE ((B.P_ANNIO * B.REAL_ACUMULADO) + B.B_ANNIO) END AS CVR_ANNIO
	
		,CASE WHEN (B.VLR_PROYECCION_ANNIO_ESC_BAJO IS NULL) 
		         THEN NULL
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_BAJO = 0 AND B.META_ANNIO_FINAL = 0)
		         THEN 1
			  WHEN ((B.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND B.VLR_PROYECCION_ANNIO_ESC_BAJO > B.META_ANNIO_FINAL)
		         THEN B.PRC_META_CVR
			  WHEN ((B.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND B.VLR_PROYECCION_ANNIO_ESC_BAJO < B.META_ANNIO_FINAL)
		         THEN 0
			  WHEN ((B.VLR_PROYECCION_ANNIO_ESC_BAJO = 0 AND B.VLR_LIMITE_INFERIOR_ANNIO = 0 AND B.VLR_LIMITE_SUPERIOR_ANNIO = 0) 
			      OR ((B.VLR_PROYECCION_ANNIO_ESC_BAJO IS NULL) OR (B.VLR_LIMITE_INFERIOR_ANNIO IS NULL) OR (B.VLR_LIMITE_SUPERIOR_ANNIO IS NULL)))			   
			     THEN 0
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_BAJO >= B.VLR_LIMITE_SUPERIOR_ANNIO)
		         THEN B.PRC_LIMITE_SUPERIOR_CVR
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_BAJO < B.VLR_LIMITE_INFERIOR_ANNIO)
		         THEN 0
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_BAJO = B.VLR_LIMITE_INFERIOR_ANNIO)
		         THEN B.PRC_LIMITE_INFERIOR_CVR
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_BAJO = B.META_ANNIO_FINAL)
		         THEN B.PRC_META_CVR
		      ELSE ((B.P_ESC_BAJO * B.VLR_PROYECCION_ANNIO_ESC_BAJO) + B.B_ESC_BAJO) END AS CVR_ESC_BAJO

		,CASE WHEN (B.VLR_PROYECCION_ANNIO_ESC_MEDIO IS NULL) 
				 THEN NULL
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_MEDIO = 0 AND B.META_ANNIO_FINAL = 0)
		         THEN 1
			  WHEN ((B.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND (B.VLR_PROYECCION_ANNIO_ESC_MEDIO > B.META_ANNIO_FINAL))
		         THEN B.PRC_META_CVR
			  WHEN ((B.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND (B.VLR_PROYECCION_ANNIO_ESC_MEDIO < B.META_ANNIO_FINAL))
		         THEN 0
			  WHEN ((B.VLR_PROYECCION_ANNIO_ESC_MEDIO = 0 AND B.VLR_LIMITE_INFERIOR_ANNIO = 0 AND B.VLR_LIMITE_SUPERIOR_ANNIO = 0)
		          OR ((B.VLR_PROYECCION_ANNIO_ESC_MEDIO IS NULL) OR (B.VLR_LIMITE_INFERIOR_ANNIO IS NULL) OR (B.VLR_LIMITE_SUPERIOR_ANNIO IS NULL)))			   
			     THEN 0
			  WHEN(B.VLR_PROYECCION_ANNIO_ESC_MEDIO >= B.VLR_LIMITE_SUPERIOR_ANNIO)
		         THEN B.PRC_LIMITE_SUPERIOR_CVR
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_MEDIO < B.VLR_LIMITE_INFERIOR_ANNIO)
		         THEN 0
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_MEDIO = B.VLR_LIMITE_INFERIOR_ANNIO)
		         THEN  B.PRC_LIMITE_INFERIOR_CVR
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_MEDIO = B.META_ANNIO_FINAL)
		         THEN B.PRC_META_CVR
			  ELSE ((B.P_ESC_MEDIO * B.VLR_PROYECCION_ANNIO_ESC_MEDIO) + B.B_ESC_MEDIO) END AS CVR_ESC_MEDIO
			  
		,CASE WHEN (B.VLR_PROYECCION_ANNIO_ESC_ALTO IS NULL) 
				 THEN NULL
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_ALTO = 0 AND B.META_ANNIO_FINAL = 0)
		         THEN 1
			  WHEN ((B.VLR_LIMITE_SUPERIOR_ANNIO IS NULL ) AND (B.VLR_PROYECCION_ANNIO_ESC_ALTO > B.META_ANNIO_FINAL))
		         THEN B.PRC_META_CVR
			  WHEN ((B.VLR_LIMITE_INFERIOR_ANNIO IS NULL ) AND (B.VLR_PROYECCION_ANNIO_ESC_ALTO < B.META_ANNIO_FINAL))
		         THEN 0
			  WHEN ((B.VLR_PROYECCION_ANNIO_ESC_ALTO = 0 AND B.VLR_LIMITE_INFERIOR_ANNIO = 0 AND B.VLR_LIMITE_SUPERIOR_ANNIO=0) 
		         OR ((B.VLR_PROYECCION_ANNIO_ESC_ALTO IS NULL ) OR (B.VLR_LIMITE_INFERIOR_ANNIO IS NULL )OR (B.VLR_LIMITE_SUPERIOR_ANNIO IS NULL )))		  
		         THEN 0
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_ALTO >= B.VLR_LIMITE_SUPERIOR_ANNIO)
		         THEN B.PRC_LIMITE_SUPERIOR_CVR
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_ALTO < B.VLR_LIMITE_INFERIOR_ANNIO)
		         THEN 0
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_ALTO = B.VLR_LIMITE_INFERIOR_ANNIO)
		         THEN B.PRC_LIMITE_INFERIOR_CVR
			  WHEN (B.VLR_PROYECCION_ANNIO_ESC_ALTO = B.META_ANNIO_FINAL)
		         THEN B.PRC_META_CVR 
			  ELSE ((B.P_ESC_ALTO * B.VLR_PROYECCION_ANNIO_ESC_ALTO) + B.B_ESC_ALTO) END AS CVR_ESC_ALTO

 		FROM  SUBNIVEL4 B
        LEFT JOIN ATOMO.CVD_PARAMETRIZACION_CVR C
			   ON CAST(B.DESC_VERSION AS REAL) = CAST(C.DESC_VERSION AS REAL)
			   AND B.DESC_ANNIO = CAST(C.DTM_VIGENCIA_DESDE AS VARCHAR(4)) ),
 FINAL 
  AS (  SELECT B.FK_PARAM_INDICADOR,
	 B.FK_INDICADOR,
	 B.FK_TABLERO,
	 B.FK_PERIODO,
	 B.DESC_PERIODO,
	 B.DESC_SENTIDO,
	 B.DESC_META_NORMALIZADA,
	 B.DESC_ACCIONES_DE_ASEGURAMIENTO,
	 B.DESC_PREMISAS_ESC_BAJO,
	 B.DESC_PREMISAS_ESC_MEDIO,
	 B.DESC_PREMISAS_ESC_ALTO,
	 B.DESC_CAUSAS_DESEMPENO_ACUM,
	 B.DESC_CAUSAS_DESEMPENO_PERIODO,
	 B.DESC_TBG,
	 B.DTM_FECHACARGA,
	 B.DESC_RESPONSABLE_MEDICION,
	 B.DESC_CARGO_RESPONSABLE_MEDICION,
	 B.DESC_CORREO_RESPONSABLE_MEDICION,
	 B.DESC_RESPONSABLE_MEDICION_2,
	 B.DESC_CARGO_RESPONSABLE_MEDICION_2,
	 B.DESC_CORREO_RESPONSABLE_MEDICION_2,
	 B.DESC_REFERENTE,
	 B.DESC_SECUENCIA_ORDEN,
	 B.DESC_CORTO_LARGO_PLAZO,
	 B.DESC_TIPO_TABLERO,
	 B.DESC_FRECUENCIA,
	 B.DESC_HITO_INDICADOR,
	 B.DESC_DETALLE_INDICADOR,
	 B.DESC_NOMBRE_INDICADOR,
	 B.DESC_OBJETIVO,
	 B.ID_INDICADOR,
	 B.DESC_VERSION,
	 B.DESC_EJE_PALANCA,
	 B.NUM_ORDEN_PALANCA,
	 B.NUM_ORDEN_OBJETIVO,
	 B.DESC_NIVEL,
	 B.DESC_SIGLA_AREA,
	 B.DESC_RUTINA,
	 B.DESC_GERENCIA,
	 B.DESC_UNIDAD_NEGOCIO_NVL_2,
	 B.DESC_UNIDAD_NEGOCIO_NVL_3,
	 B.DESC_SEGMENTO,
	 B.DESC_GRUPO_SEGMENTO,
	 B.DESC_VP_EJECUTIVA,
	 B.DESC_EMPRESA,
	 B.DESC_GRUPO,
	 B.DESC_TABLERO,
	 B.CANT_DECIMALES_CALCULO,
	 B.CANT_DECIMALES_REPORTE,
	 B.PRC_META_CVR,
	 B.PRC_LIMITE_SUPERIOR_CVR,
	 B.PRC_LIMITE_INFERIOR_CVR,
	 B.VLR_PESO_INDICADOR,
	 B.VLR_LIMITE_INFERIOR,
	 B.VLR_LIMITE_SUPERIOR,
	 B.DESC_ANNIO,
	 B.MES,
	 B.DESC_TABLERO_CVR,
	 B.FECHA_CARGA_SYNAPSE,
	 B.FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
	 B.CM_RESUMEN,
	 B.DESC_ESTANDAR,
	 B.DESC_VERSION_CVR,
	 B.VIGENCIA_CVR,
	 SUM(B.REAL_PERIODO) AS REAL_PERIODO,
	 SUM(B.REAL_ACUMULADO) AS REAL_ACUMULADO,
	 SUM(B.PLAN_PERIODO) AS PLAN_PERIODO,
	 SUM(B.PLAN_ACUMULADO) AS PLAN_ACUMULADO,
	 SUM(B.PLAN_PERIODO_NORMALIZADO) AS PLAN_PERIODO_NORMALIZADO,
	 SUM(B.PLAN_ACUMULADO_NORMALIZADO) AS PLAN_ACUMULADO_NORMALIZADO,
	 SUM(B.META_ANNIO) AS META_ANNIO,
	 SUM(B.META_ANNIO_NORMALIZADO) AS META_ANNIO_NORMALIZADO,
	 SUM(B.META_ANNIO_1) AS META_ANNIO_1,
	 SUM(B.META_ANNIO_2) AS META_ANNIO_2,
	 SUM(B.PROYECCION_PERIODO_1) AS PROYECCION_PERIODO_1,
	 SUM(B.PROYECCION_PERIODO_2) AS PROYECCION_PERIODO_2,
	 SUM(B.PROYECCION_PERIODO_3) AS PROYECCION_PERIODO_3,
	 SUM(B.VLR_PROYECCION_ANNIO_ESC_BAJO) AS VLR_PROYECCION_ANNIO_ESC_BAJO,
	 SUM(B.VLR_PROYECCION_ANNIO_ESC_MEDIO) AS VLR_PROYECCION_ANNIO_ESC_MEDIO,
	 SUM(B.VLR_PROYECCION_ANNIO_ESC_ALTO) AS VLR_PROYECCION_ANNIO_ESC_ALTO,
	 SUM(B.PRC_CUMP_PERIODO) AS PRC_CUMP_PERIODO,
	 SUM(B.PRC_CUMP_ACUMULADO) AS PRC_CUMP_ACUMULADO,
	 SUM(B.PRC_CUMP_ANNIO_ESC_BAJO) AS PRC_CUMP_ANNIO_ESC_BAJO,
	 SUM(B.PRC_CUMP_ANNIO_ESC_MEDIO) AS PRC_CUMP_ANNIO_ESC_MEDIO,
	 SUM(B.PRC_CUMP_ANNIO_ESC_ALTO) AS PRC_CUMP_ANNIO_ESC_ALTO,
	 SUM(B.PRC_DESEMPENO_PERIODO) AS PRC_DESEMPENO_PERIODO,
	 SUM(B.PRC_DESEMPENO_ACUMULADO) AS PRC_DESEMPENO_ACUMULADO,
	 SUM(B.PRC_DESEMPENO_ANNIO_ESC_BAJO) AS PRC_DESEMPENO_ANNIO_ESC_BAJO,
	 SUM(B.PRC_DESEMPENO_ANNIO_ESC_MEDIO) AS PRC_DESEMPENO_ANNIO_ESC_MEDIO,
	 SUM(B.PRC_DESEMPENO_ANNIO_ESC_ALTO) AS PRC_DESEMPENO_ANNIO_ESC_ALTO,
	 SUM(B.VLR_LIMITE_INFERIOR_ANNIO) AS VLR_LIMITE_INFERIOR_ANNIO,
	 SUM(B.VLR_LIMITE_SUPERIOR_ANNIO) AS VLR_LIMITE_SUPERIOR_ANNIO,
	 SUM(B.VLR_LIMITE_INFERIOR_ACUMULADO) AS VLR_LIMITE_INFERIOR_ACUMULADO,
	 SUM(B.VLR_LIMITE_SUPERIOR_ACUMULADO) AS VLR_LIMITE_SUPERIOR_ACUMULADO,
	 SUM(B.VLR_LIMITE_INFERIOR_PERIODO) AS VLR_LIMITE_INFERIOR_PERIODO,
	 SUM(B.VLR_LIMITE_SUPERIOR_PERIODO) AS VLR_LIMITE_SUPERIOR_PERIODO,
	 SUM(B.META_ANNIO_FINAL) AS META_ANNIO_FINAL,
	 SUM(B.RECTA_ANNIO) AS RECTA_ANNIO,
	 SUM(B.RECTA_ANNIO_ESC_BAJO) AS RECTA_ANNIO_ESC_BAJO,
	 SUM(B.RECTA_ANNIO_ESC_MEDIO) AS RECTA_ANNIO_ESC_MEDIO,
	 SUM(B.RECTA_ANNIO_ESC_ALTO) AS RECTA_ANNIO_ESC_ALTO,
	 SUM(B.P_ANNIO) AS P_ANNIO,
	 SUM(B.PX_ANNIO) AS PX_ANNIO,
	 SUM(B.B_ANNIO) AS B_ANNIO,
	 SUM(B.CVR_ANNIO) AS CVR_ANNIO,
	 SUM(B.P_ESC_BAJO) AS P_ESC_BAJO,
	 SUM(B.PX_ESC_BAJO) AS PX_ESC_BAJO,
	 SUM(B.B_ESC_BAJO) AS B_ESC_BAJO,
	 SUM(B.CVR_ESC_BAJO) AS CVR_ESC_BAJO,
	 SUM(B.P_ESC_MEDIO) AS P_ESC_MEDIO,
	 SUM(B.PX_ESC_MEDIO) AS PX_ESC_MEDIO,
	 SUM(B.B_ESC_MEDIO) AS B_ESC_MEDIO,
	 SUM(B.CVR_ESC_MEDIO) AS CVR_ESC_MEDIO,
	 SUM(B.P_ESC_ALTO) AS P_ESC_ALTO,
	 SUM(B.PX_ESC_ALTO) AS PX_ESC_ALTO,
	 SUM(B.B_ESC_ALTO) AS B_ESC_ALTO,
	 SUM(B.CVR_ESC_ALTO) AS CVR_ESC_ALTO 
	 
FROM SUBNIVEL5 B 

GROUP BY B.FK_PARAM_INDICADOR,
	 B.FK_INDICADOR,
	 B.FK_TABLERO,
	 B.FK_PERIODO,
	 B.DESC_PERIODO,
	 B.DESC_SENTIDO,
	 B.DESC_META_NORMALIZADA,
	 B.DESC_ACCIONES_DE_ASEGURAMIENTO,
	 B.DESC_PREMISAS_ESC_BAJO,
	 B.DESC_PREMISAS_ESC_MEDIO,
	 B.DESC_PREMISAS_ESC_ALTO,
	 B.DESC_CAUSAS_DESEMPENO_ACUM,
	 B.DESC_CAUSAS_DESEMPENO_PERIODO,
	 B.DESC_TBG,
	 B.DTM_FECHACARGA,
	 B.DESC_RESPONSABLE_MEDICION,
	 B.DESC_CARGO_RESPONSABLE_MEDICION,
	 B.DESC_CORREO_RESPONSABLE_MEDICION,
	 B.DESC_RESPONSABLE_MEDICION_2,
	 B.DESC_CARGO_RESPONSABLE_MEDICION_2,
	 B.DESC_CORREO_RESPONSABLE_MEDICION_2,
	 B.DESC_REFERENTE,
	 B.DESC_SECUENCIA_ORDEN,
	 B.DESC_CORTO_LARGO_PLAZO,
	 B.DESC_TIPO_TABLERO,
	 B.DESC_FRECUENCIA,
	 B.DESC_HITO_INDICADOR,
	 B.DESC_DETALLE_INDICADOR,
	 B.DESC_NOMBRE_INDICADOR,
	 B.DESC_OBJETIVO,
	 B.ID_INDICADOR,
	 B.DESC_VERSION,
	 B.DESC_EJE_PALANCA,
	 B.NUM_ORDEN_PALANCA,
	 B.NUM_ORDEN_OBJETIVO,
	 B.DESC_NIVEL,
	 B.DESC_SIGLA_AREA,
	 B.DESC_RUTINA,
	 B.DESC_GERENCIA,
	 B.DESC_UNIDAD_NEGOCIO_NVL_2,
	 B.DESC_UNIDAD_NEGOCIO_NVL_3,
	 B.DESC_SEGMENTO,
	 B.DESC_GRUPO_SEGMENTO,
	 B.DESC_VP_EJECUTIVA,
	 B.DESC_EMPRESA,
	 B.DESC_GRUPO,
	 B.DESC_TABLERO,
	 B.CANT_DECIMALES_CALCULO,
	 B.CANT_DECIMALES_REPORTE,
	 B.PRC_META_CVR,
	 B.PRC_LIMITE_SUPERIOR_CVR,
	 B.PRC_LIMITE_INFERIOR_CVR,
	 B.VLR_PESO_INDICADOR,
	 B.VLR_LIMITE_INFERIOR,
	 B.VLR_LIMITE_SUPERIOR,
	 B.DESC_ANNIO,
	 B.MES,
	 B.DESC_TABLERO_CVR,
	 B.FECHA_CARGA_SYNAPSE,
	 B.FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
	 B.CM_RESUMEN,
	 B.DESC_ESTANDAR,
	 B.DESC_VERSION_CVR,
	 B.VIGENCIA_CVR)

	 SELECT * FROM FINAL;