
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-16
-- Description: Se crea la vista CVC_ENTREGABLES_HITO la cual es un insumo para el tablero Paneles y TBG's

-- Updated Date: 2022-06-06
-- Updated by:   Diego Rangel
-- Description: Se crea el campo .Peso Entregable, el cual se encontraba como calculo en el tablero de Paneles y TBGs

-- Updated Date: 2022-08-25
-- Updated by :  Oscar Angel
-- Description: Se crea el campo DESC_CORREO_RESPONSABLE_ENTREGABLE, el cual se necesita en los tableros finales.
-- =============================================

CREATE VIEW [ATOMO].[CVC_ENTREGABLES_HITO] AS
SELECT A.GK_ENTREGABLE_HITO,
		A.ID_ENTREGABLE,
		A.FK_PARAM_INDICADOR,
		B.DESC_NOMBRE_INDICADOR,
		A.DESC_ENTREGABLE,
		A.DESC_RESPONSABLE_ENTREGABLE,
		A.[DESC_CORREO_RESPONSABLE_ENTREGABLE],
		A.DESC_COMENTARIOS_ENTREGABLE,
		A.DESC_UNIDAD_MEDIDA,
		A.DTM_FECHA_ENTREGABLE,
		A.DTM_FECHACARGA,
		CASE WHEN (A.DTM_FECHA_EJECUCION_ENTREGABLE= '1900-01-01')
			THEN NULL
		ELSE A.DTM_FECHA_EJECUCION_ENTREGABLE END AS DTM_FECHA_EJECUCION_ENTREGABLE,
		SUM(A.VLR_PESO_ENTREGABLE) AS VLR_PESO_ENTREGABLE,
		SUM(A.VLR_PLAN_ENTREGABLE) AS VLR_PLAN_ENTREGABLE,
		SUM(A.PRC_CUMPLIMIENTO_ENTREGABLE) AS PRC_CUMPLIMIENTO_ENTREGABLE,
		SUM(A.PRC_CUMPLIMIENTO_ENTREGABLE * A.VLR_PESO_ENTREGABLE) AS PRC_CUMP_ACTUAL_HITO,
		SUM(A.VLR_PESO_ENTREGABLE)*100 AS ".Peso Entregable"

FROM [ATOMO].[DWH.DIM_ENTREGABLES_HITO] A
	LEFT JOIN [ATOMO].[DWH.DIM_INDICADOR] B
		ON A.FK_INDICADOR = B.GK_INDICADOR

GROUP BY A.GK_ENTREGABLE_HITO,
		A.ID_ENTREGABLE,
		A.FK_PARAM_INDICADOR,
		B.DESC_NOMBRE_INDICADOR,
		A.DESC_ENTREGABLE,
		A.DESC_RESPONSABLE_ENTREGABLE,
		A.[DESC_CORREO_RESPONSABLE_ENTREGABLE],
		A.DESC_COMENTARIOS_ENTREGABLE,
		A.DESC_UNIDAD_MEDIDA,
		A.DTM_FECHA_ENTREGABLE,
		A.DTM_FECHACARGA,
		A.DTM_FECHA_EJECUCION_ENTREGABLE;
 
