
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-16
-- Description: Se crea la vista CVC_RESUMEN_TENDENCIA_DETALLE_KRI_TD la cual es un insumo para el tablero Paneles y TBG's
-- =============================================

CREATE VIEW ATOMO.CVC_RESUMEN_TENDENCIA_DETALLE_KRI_TD AS 

SELECT FK_FECHA_CORTE,
	 FECHA,
	 PERIODO,
	 ANIO,
	 MES,
	 ID_OBJETIVO,
	 DESC_OBJETIVO,
	 FK_RIESGO,
	 DESC_NOMBRE_CORTO_CONSEC_RIESGO,
	 FK_KRI,
	 ULT_MEDICION_KRI,
	 DESC_NOMBRE_CORTO_KRI,
	 DESC_FRECUENCIA,
	 DESC_TENDENCIA_ABREVIADO,
	 ESTADO_DEL_KRI,
	 SUM(VLR_KRI) AS VLR_KRI,
	 SUM(VLR_LIMITE_KRI) AS VLR_LIMITE_KRI 

FROM [ATOMO].[DWH.FACT_RESUMEN_TENDENCIA_DETALLE]

GROUP BY FK_FECHA_CORTE,
	 FECHA,
	 PERIODO,
	 ANIO,
	 MES,
	 ID_OBJETIVO,
	 DESC_OBJETIVO,
	 FK_RIESGO,
	 DESC_NOMBRE_CORTO_CONSEC_RIESGO,
	 FK_KRI,
	 ULT_MEDICION_KRI,
	 DESC_NOMBRE_CORTO_KRI,
	 DESC_FRECUENCIA,
	 DESC_TENDENCIA_ABREVIADO,
	 ESTADO_DEL_KRI
	  