
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-13
-- Description: Se crea la vista CVD_AUX_TIEMPO_CARGA la cual es un insumo para el tablero Paneles y TBG's
-- =============================================

CREATE VIEW ATOMO.CVD_AUX_TIEMPO_CARGA AS

SELECT CONCAT(A.FECHA,B.MES) AS COD_PERIODO, 1 AS CANT FROM

(
		SELECT
		 DISTINCT SUBSTRING(CAST(DESC_PERIODO_CARGA AS VARCHAR(50)),1,4) AS FECHA
		FROM [ATOMO].[DWH.DIM_TIEMPO_CARGA]
		WHERE DESC_PERIODO_CARGA >= '202001') AS A
		
CROSS  JOIN 
(SELECT '01' AS MES 
UNION ALL
SELECT '02' AS MES 
UNION ALL
SELECT '03' AS MES 
UNION ALL
SELECT '04' AS MES 
UNION ALL
SELECT '05' AS MES 
UNION ALL
SELECT '06' AS MES 
UNION ALL
SELECT '07' AS MES 
UNION ALL
SELECT '08' AS MES 
UNION ALL
SELECT '09' AS MES 
UNION ALL
SELECT '10' AS MES 
UNION ALL
SELECT '11' AS MES 
UNION ALL
SELECT '12' AS MES) AS B
