
-- =============================================
-- Author:      Oscar Angel
-- Create Date: 2022-05-13
-- Description: Se crea la vista CVD_INDICADOR la cual es un insumo para el tablero Paneles y TBG's
-- =============================================

CREATE VIEW ATOMO.CVD_INDICADOR AS

SELECT GK_INDICADOR,
	 ID_INDICADOR,
	 DESC_NOMBRE_INDICADOR,
	 DESC_INDICADOR AS DESC_DESCRIPCION_INDICADOR,
	 DESC_FORMULA,
	 DESC_UNIDAD_MEDIDA,
	 DESC_SENTIDO,
	 DESC_FRECUENCIA,
	 VLR_LIMITE_INFERIOR,
	 VLR_LIMITE_SUPERIOR,
	 VLR_CUMP_SATISFACCION,
	 DESC_FUENTE_PROYECTADA,
	 DESC_FUENTE_REAL,
	 DESC_VERSION,
	 'ACTIVO' AS DESC_ESTADO_REG,
	 DTM_VIGENCIA_DESDE AS DTM_FECHA_INI_VIGENCIA_INDICADOR,
	 DTM_VIGENCIA_HASTA AS DTM_FECHA_FIN_VIGENCIA_INDICADOR,
	 DESC_USUARIO_RESP_CALCULO,
	 DESC_META_NORMALIZADA,
	 CANT_COMPONENTES AS CANTIDAD_COMPONENTES,
	 DESC_REFERENTE,
	 ID_HOJA_VIDA AS COD_HOJA_VIDA,
	 DESC_CALCULABLE_AUTOMATIZABLE,
	 CANT_DECIMALES_CALCULO,
	 CANT_DECIMALES_REPORTE,
	 DESC_VISUALIZA_PERIODO,
	 DESC_VISUALIZA_ACUMULADO,
	 DESC_VISUALIZA_ANNIO_CORRIDO,
	 DESC_RESPONSABLE_META,
	 DESC_RESPONSABLE_SEGUIMIENTO AS DESC_RESPONSABLE_CONSOLIDACION,
	 DESC_RESPONSABLE_REPORTE_RES,
	 DESC_APROBADOR,
	 DESC_APROBADOR_CARGO,
	 DESC_INDICADOR_HITO,
	 DTM_FECHACARGA,
	 DESC_PROCESO,
	 DESCNOMBRERESPONSABLEDOCUMENTARHV,
	 DESCCORREORESPONSABLEDOCUMENTARHV

FROM [ATOMO].[DWH.DIM_INDICADOR]
