-- =============================================
-- Author:      Victor Guerra
-- Create Date: 2022-07-29
-- Description: Se crea la Dimension STG.DIM_COMPONENTE la cual es un insumo para las cargas DWH
-- =============================================

CREATE TABLE [ATOMO].[STG.DIM_COMPONENTE]
(
     GK_COMPONENTE BIGINT NOT NULL ,
	 ID_COMPONENTE BIGINT  NOT NULL ,
	 DESC_NOMBRE_COMPONENTE VARCHAR(500) ,
	 DESC_DETALLE_COMPONENTE VARCHAR(500) ,
	 DESC_COMPONENTE VARCHAR(4000) ,
	 DESC_RESPONSABLE VARCHAR(500) ,
	 DESC_UNIDAD_MEDIDA VARCHAR(500) ,
	 DESC_VISUALIZA_PERIODO VARCHAR(500) ,
	 DESC_FRECUENCIA VARCHAR(500) ,
	 CANT_DECIMALES_CALCULO INTEGER ,
	 CANT_DECIMALES_REPORTE INTEGER ,
	 DESC_FUENTE_PROYECTADA VARCHAR(500) ,
	 DESC_FUENTE_REAL VARCHAR(500) ,
	 DESC_VERSION VARCHAR(500) ,
	 DTM_VIGENCIA_DESDE DATETIME ,
	 DTM_VIGENCIA_HASTA DATETIME ,
	 DTM_FECHACARGA DATETIME ,
	 DESC_ORIGEN VARCHAR(80),
	 FK_TIPOSINCONSISTENCIA VARCHAR(250),
	 DESC_TIPO_COMPONENTE VARCHAR(50) 
)