-- =============================================
-- Author:      Oscar Angel 
-- Create Date: 2022-05-23
-- Description: Se crea el Store Procedure SP_DESEMPENO_TABLERO para la creación de la vista ATOMO.CVC_DESEMPENO_TABLERO la cual es insumo para el tablero Paneles y TBG's

-- Author:      Oscar Angel
-- Update Date: 2022-06-30
-- Description: Se realiza la adición de los campos VLR_LIMITE_SUPERIOR_PERIODO y VLR_LIMITE_INFERIOR_PERIODO los cuales son necesario para visualizar el semaforo "_CC Semaforo TBG Per" de manera correcta en el tablero Paneles y TBG's

-- Author:      Oscar Angel 
-- Update Date: 2022-07-05
-- Description: Se realiza ajuste en los condicionales para los campos RECTA_ANNIO, RECTA_ANNIO_ESC_BAJO, RECTA_ANNIO_ESC_MEDIO, RECTA_ANNIO_ESC_ALTO

-- Author:      Oscar Angel 
-- Update Date: 2022-11-09 
-- Description: Se realiza ajuste en query por limpieza de columnas en la tabla DimConfiguracion_CVR en TD.

-- Author:      Oscar Angel 
-- Update Date: 2022-12-28 
-- Description: Se realiza ajuste en las validaciones de lo querys para el calculo de los campos CVR_ANNIO. CVR_ESC_BAJO, CVR_ESC_MEDIO, CVR_ESC_ALTO.

-- Author:      Alejandro Vargas
-- Update Date: 2023-04-18 
-- Description: Se realiza ajuste en las validaciones de lo querys para el calculo de los campos VLR_PROYECCION_ANNIO_ESC_BAJO, VLR_PROYECCION_ANNIO_ESC_MEDIO, VLR_PROYECCION_ANNIO_ESC_ALTO

-- Author:      Oscar Angel 
-- Update Date: 2023-06-28
-- Description: Se adiciona los campo Num_Orden_Palanca y Num_Orden_Objetivo

-- Author:      Oscar Angel 
-- Update Date: 2024-04-17
-- Description: Se adiciona el cruce con el nuevo campo FK_TABLERO

-- Author:      Oscar Angel 
-- Update Date: 2024-06-18
-- Description: Se adiciona el cruce con el nuevo campo FK_INDICADOR

-- =============================================

CREATE PROC [ATOMO].[SP_DESEMPENO_TABLERO] AS 
 SET NOCOUNT ON;
 
 DECLARE @sql nvarchar(1000);

IF OBJECT_ID('tempdb..#TEMPCVC_DESEMPENO_TABLERO') IS NOT NULL
    BEGIN
        DROP TABLE #TEMPCVC_DESEMPENO_TABLERO
    END;

IF EXISTS(SELECT [name] FROM sys.tables WHERE [name] like '%TMP2CVC_DESEMPENO_TABLERO%') 
BEGIN
   TRUNCATE TABLE [ATOMO].[TMP2CVC_DESEMPENO_TABLERO];
END;

DROP VIEW IF EXISTS [ATOMO].[CVC_DESEMPENO_TABLERO];

WITH  SUBNIVEL1
  AS (SELECT A.FK_PARAM_INDICADOR,
	  B.FK_INDICADOR,
	  A.FK_TABLERO,
	  B.FK_PERIODO,
	  B.DESC_PERIODO,
	  B.DESC_SENTIDO,
	  B.DESC_META_NORMALIZADA,
	  B.DESC_ACCIONES_DE_ASEGURAMIENTO,
	  B.DESC_PREMISAS_ESC_BAJO,
	  B.DESC_PREMISAS_ESC_MEDIO,
	  B.DESC_PREMISAS_ESC_ALTO,
	  B.DESC_CAUSAS_DESEMPENO_ACUM,
	  B.DESC_CAUSAS_DESEMPENO_PERIODO,
	  A.DESC_TBG,
	  A.DTM_FECHACARGA,
	  A.DESC_RESPONSABLE_MEDICION,
	  A.DESC_CARGO_RESPONSABLE_MEDICION,
	  A.DESC_CORREO_RESPONSABLE_MEDICION,
	  A.DESC_RESPONSABLE_MEDICION_2,
	  A.DESC_CARGO_RESPONSABLE_MEDICION_2,
	  A.DESC_CORREO_RESPONSABLE_MEDICION_2,
	  A.DESC_REFERENTE,
	  A.DESC_SECUENCIA_ORDEN,
	  A.DESC_CORTO_LARGO_PLAZO,
	  A.DESC_TIPO_TABLERO,
	  A.DESC_FRECUENCIA,
	  A.DESC_HITO_INDICADOR,
	  A.DESC_DETALLE_INDICADOR,
	  A.DESC_NOMBRE_INDICADOR,
	  A.DESC_OBJETIVO,
	  A.ID_INDICADOR,
	  A.DESC_VERSION,
	  A.DESC_EJE_PALANCA,
	  A.NUM_ORDEN_PALANCA,
	  A.NUM_ORDEN_OBJETIVO,
	  A.DESC_NIVEL,
	  A.DESC_SIGLA_AREA,
	  A.DESC_RUTINA,
	  A.DESC_GERENCIA,
	  A.DESC_UNIDAD_NEGOCIO_NVL_2,
	  A.DESC_UNIDAD_NEGOCIO_NVL_3,
	  A.DESC_SEGMENTO,
	  A.DESC_GRUPO_SEGMENTO,
	  A.DESC_VP_EJECUTIVA,
	  A.DESC_EMPRESA,
	  A.DESC_GRUPO,
	  A.DESC_TABLERO,
	  C.CANT_DECIMALES_CALCULO,
	  C.CANT_DECIMALES_REPORTE,
	  D.PRC_META_CVR,
	  D.PRC_LIMITE_SUPERIOR_CVR,
	  D.PRC_LIMITE_INFERIOR_CVR,
	  D.DESC_ESTANDAR ,
	  A.VLR_PESO_INDICADOR,
	  C.VLR_LIMITE_INFERIOR,
	  C.VLR_LIMITE_SUPERIOR,
	  B.DESC_ANNIO,
	  A.DESC_TABLERO_CVR,
	  B.REAL_PERIODO,
	  B.REAL_ACUMULADO,
	  B.PLAN_PERIODO,
	  B.PLAN_ACUMULADO,
	  B.PLAN_PERIODO_NORMALIZADO,
	  B.PLAN_ACUMULADO_NORMALIZADO,
	  B.META_ANNIO,
	  B.META_ANNIO_NORMALIZADO,
	  B.META_ANNIO_1,
	  B.META_ANNIO_2,
	  B.PROYECCION_PERIODO_1,
	  B.PROYECCION_PERIODO_2,
	  B.PROYECCION_PERIODO_3,
	  B.VLR_PROYECCION_ANNIO_ESC_BAJO,
	  B.VLR_PROYECCION_ANNIO_ESC_MEDIO,
	  B.VLR_PROYECCION_ANNIO_ESC_ALTO,
	  B.PRC_CUMP_PERIODO,
	  B.PRC_CUMP_ACUMULADO,
	  B.PRC_CUMP_ANNIO_ESC_BAJO,
	  B.PRC_CUMP_ANNIO_ESC_MEDIO,
	  B.PRC_CUMP_ANNIO_ESC_ALTO,
	  B.PRC_DESEMPENO_PERIODO,
	  B.PRC_DESEMPENO_ACUMULADO,
	  B.PRC_DESEMPENO_ANNIO_ESC_BAJO,
	  B.PRC_DESEMPENO_ANNIO_ESC_MEDIO,
	  B.PRC_DESEMPENO_ANNIO_ESC_ALTO,
	  B.FECHA_CARGA_SYNAPSE,
	  B.FECHA_PROXIMA_ACTUALIZA_SYNAPSE
  
FROM [ATOMO].[CVD_CONFIGURACION_TABLERO] A
	INNER JOIN [ATOMO].[CVC_DESEMPENO_INDICADOR] B
		ON A.FK_PARAM_INDICADOR = B.FK_PARAM_INDICADOR
		AND A.FK_INDICADOR = B.FK_INDICADOR
		AND A.FK_TABLERO = B.FK_TABLERO
		AND A.DESC_ANNIO = B.DESC_ANNIO
	LEFT JOIN [ATOMO].[CVD_INDICADOR] C
		ON B.FK_INDICADOR = C.GK_INDICADOR
	LEFT JOIN [ATOMO].[CVD_PARAMETRIZACION_CVR] D
		ON REPLACE(A.DESC_VERSION,'.0','') = D.DESC_VERSION
		AND A.DESC_ANNIO = CAST(D.DTM_VIGENCIA_DESDE AS VARCHAR(4))),


  SUBNIVEL2   
  AS ( SELECT A.*
			  , RIGHT(A.DESC_PERIODO,2) AS MES
			  
			  , CASE WHEN (A.DESC_META_NORMALIZADA = 'Si')
						THEN (CASE WHEN (A.META_ANNIO_NORMALIZADO IS NULL)
									  THEN A.META_ANNIO
								   ELSE A.META_ANNIO_NORMALIZADO END)
				     ELSE A.META_ANNIO END AS META_ANNIO_FINAL
			
			  , CASE WHEN A.VLR_LIMITE_INFERIOR IS NULL 
						THEN NULL
					WHEN COALESCE(A.PLAN_ACUMULADO_NORMALIZADO, A.PLAN_ACUMULADO) = 0 
						THEN NULL
					WHEN A.DESC_META_NORMALIZADA = 'No' AND (A.DESC_SENTIDO = 'Negativo' OR A.PLAN_ACUMULADO < 0) 
						THEN (A.PLAN_ACUMULADO + (1 - A.VLR_LIMITE_INFERIOR) * A.PLAN_ACUMULADO)
					WHEN A.DESC_META_NORMALIZADA = 'Si' AND (A.DESC_SENTIDO = 'Negativo' OR COALESCE(A.PLAN_ACUMULADO_NORMALIZADO, A.PLAN_ACUMULADO) < 0) 
						THEN (COALESCE(A.PLAN_ACUMULADO_NORMALIZADO, A.PLAN_ACUMULADO) + (1 - A.VLR_LIMITE_INFERIOR) * COALESCE(A.PLAN_ACUMULADO_NORMALIZADO, A.PLAN_ACUMULADO))
					WHEN A.DESC_META_NORMALIZADA = 'No' 
						THEN A.VLR_LIMITE_INFERIOR * A.PLAN_ACUMULADO
					WHEN A.DESC_META_NORMALIZADA = 'Si' 
						THEN A.VLR_LIMITE_INFERIOR * COALESCE(A.PLAN_ACUMULADO_NORMALIZADO, A.PLAN_ACUMULADO)
					END AS VLR_LIMITE_INFERIOR_ACUMULADO

			  , CASE WHEN A.VLR_LIMITE_SUPERIOR IS NULL
						THEN NULL 
					WHEN COALESCE(A.PLAN_ACUMULADO_NORMALIZADO,A.PLAN_ACUMULADO) = 0
						THEN NULL
					WHEN (A.DESC_SENTIDO = 'Positivo' AND (A.DESC_META_NORMALIZADA = 'No' AND A.PLAN_ACUMULADO < 0))
						THEN (A.PLAN_ACUMULADO + (1 - A.VLR_LIMITE_SUPERIOR) * A.PLAN_ACUMULADO)
					WHEN (A.DESC_SENTIDO = 'Positivo' AND (A.DESC_META_NORMALIZADA = 'Si' 
						    AND COALESCE(A.PLAN_ACUMULADO_NORMALIZADO,A.PLAN_ACUMULADO) < 0))
						THEN (COALESCE(A.PLAN_ACUMULADO_NORMALIZADO,A.PLAN_ACUMULADO) + (1 - A.VLR_LIMITE_SUPERIOR) * COALESCE(A.PLAN_ACUMULADO_NORMALIZADO,A.PLAN_ACUMULADO))
					WHEN A.DESC_META_NORMALIZADA = 'No' AND (A.DESC_SENTIDO = 'Negativo' OR A.PLAN_ACUMULADO < 0)
						THEN (A.PLAN_ACUMULADO + ((1 - A.VLR_LIMITE_SUPERIOR) * A.PLAN_ACUMULADO))
					WHEN A.DESC_META_NORMALIZADA = 'Si' AND (A.DESC_SENTIDO = 'Negativo' OR 
						 COALESCE(A.PLAN_ACUMULADO_NORMALIZADO, A.PLAN_ACUMULADO) < 0)
						THEN (COALESCE(A.PLAN_ACUMULADO_NORMALIZADO, A.PLAN_ACUMULADO) + ((1 - A.VLR_LIMITE_SUPERIOR) * COALESCE(A.PLAN_ACUMULADO_NORMALIZADO, A.PLAN_ACUMULADO)))
					WHEN A.DESC_META_NORMALIZADA = 'No'
						THEN (A.VLR_LIMITE_SUPERIOR * A.PLAN_ACUMULADO)
					WHEN A.DESC_META_NORMALIZADA = 'Si'
						THEN (A.VLR_LIMITE_SUPERIOR * COALESCE(A.PLAN_ACUMULADO_NORMALIZADO, A.PLAN_ACUMULADO))
					ELSE NULL END AS VLR_LIMITE_SUPERIOR_ACUMULADO

			  , CASE WHEN A.VLR_LIMITE_INFERIOR IS NULL 
						THEN NULL
					WHEN COALESCE(A.PLAN_PERIODO_NORMALIZADO, A.PLAN_PERIODO) = 0 
						THEN NULL
					WHEN A.DESC_META_NORMALIZADA = 'No' AND (A.DESC_SENTIDO = 'Negativo' OR A.PLAN_PERIODO < 0) 
						THEN (A.PLAN_PERIODO + (1 - A.VLR_LIMITE_INFERIOR) * A.PLAN_PERIODO)
					WHEN A.DESC_META_NORMALIZADA = 'Si' AND (A.DESC_SENTIDO = 'Negativo' OR COALESCE(A.PLAN_PERIODO_NORMALIZADO, A.PLAN_PERIODO) < 0) 
						THEN (COALESCE(A.PLAN_PERIODO_NORMALIZADO, A.PLAN_PERIODO) + (1 - A.VLR_LIMITE_INFERIOR) * COALESCE(A.PLAN_PERIODO_NORMALIZADO, A.PLAN_PERIODO))
					WHEN A.DESC_META_NORMALIZADA = 'No' 
						THEN A.VLR_LIMITE_INFERIOR * A.PLAN_PERIODO
					WHEN A.DESC_META_NORMALIZADA = 'Si' 
						THEN A.VLR_LIMITE_INFERIOR * COALESCE(A.PLAN_PERIODO_NORMALIZADO, A.PLAN_PERIODO)
					END AS VLR_LIMITE_INFERIOR_PERIODO

			  , CASE WHEN A.VLR_LIMITE_SUPERIOR IS NULL
						THEN NULL 
					WHEN COALESCE(A.PLAN_PERIODO_NORMALIZADO,A.PLAN_PERIODO) = 0
						THEN NULL
					WHEN (A.DESC_SENTIDO = 'Positivo' AND (A.DESC_META_NORMALIZADA = 'No' AND A.PLAN_PERIODO < 0))
						THEN (A.PLAN_PERIODO + (1 - A.VLR_LIMITE_SUPERIOR) * A.PLAN_PERIODO)
					WHEN (A.DESC_SENTIDO = 'Positivo' AND (A.DESC_META_NORMALIZADA = 'Si' 
						    AND COALESCE(A.PLAN_PERIODO_NORMALIZADO,A.PLAN_PERIODO) < 0))
						THEN (COALESCE(A.PLAN_PERIODO_NORMALIZADO,A.PLAN_PERIODO) + (1 - A.VLR_LIMITE_SUPERIOR) * COALESCE(A.PLAN_PERIODO_NORMALIZADO,A.PLAN_PERIODO))
					WHEN A.DESC_META_NORMALIZADA = 'No' AND (A.DESC_SENTIDO = 'Negativo' OR A.PLAN_PERIODO < 0)
						THEN (A.PLAN_PERIODO + ((1 - A.VLR_LIMITE_SUPERIOR) * A.PLAN_PERIODO))
					WHEN A.DESC_META_NORMALIZADA = 'Si' AND (A.DESC_SENTIDO = 'Negativo' OR 
						 COALESCE(A.PLAN_PERIODO_NORMALIZADO, A.PLAN_PERIODO) < 0)
						THEN (COALESCE(A.PLAN_PERIODO_NORMALIZADO, A.PLAN_PERIODO) + ((1 - A.VLR_LIMITE_SUPERIOR) * COALESCE(A.PLAN_PERIODO_NORMALIZADO, A.PLAN_PERIODO)))
					WHEN A.DESC_META_NORMALIZADA = 'No'
						THEN (A.VLR_LIMITE_SUPERIOR * A.PLAN_PERIODO)
					WHEN A.DESC_META_NORMALIZADA = 'Si'
						THEN (A.VLR_LIMITE_SUPERIOR * COALESCE(A.PLAN_PERIODO_NORMALIZADO, A.PLAN_PERIODO))
					ELSE NULL END AS VLR_LIMITE_SUPERIOR_PERIODO

 		FROM SUBNIVEL1 A ),

  SUBNIVEL3
  AS ( SELECT A.*
			  , CASE WHEN (A.VLR_LIMITE_INFERIOR IS NULL)
						THEN NULL 
					 WHEN (A.META_ANNIO_FINAL = 0)
						THEN NULL
					 WHEN (A.DESC_META_NORMALIZADA = 'No' AND (A.DESC_SENTIDO = 'Negativo' OR A.META_ANNIO_FINAL < 0))
						THEN (A.META_ANNIO_FINAL + ((1 - A.VLR_LIMITE_INFERIOR) * A.META_ANNIO_FINAL))
					 WHEN (A.DESC_META_NORMALIZADA = 'Si' AND (A.DESC_SENTIDO = 'Negativo' OR A.META_ANNIO_FINAL < 0))
						THEN (A.META_ANNIO_FINAL + ((1 - A.VLR_LIMITE_INFERIOR) * A.META_ANNIO_FINAL))
					 WHEN (A.DESC_META_NORMALIZADA = 'No')
						THEN (A.VLR_LIMITE_INFERIOR * A.META_ANNIO_FINAL)
					 WHEN (A.DESC_META_NORMALIZADA = 'Si')
						THEN (A.VLR_LIMITE_INFERIOR * A.META_ANNIO_FINAL)
					ELSE NULL END AS VLR_LIMITE_INFERIOR_ANNIO

			  , CASE WHEN (A.VLR_LIMITE_SUPERIOR IS NULL )
						THEN NULL
					 WHEN (A.META_ANNIO_FINAL = 0)
						THEN NULL
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND A.META_ANNIO_FINAL < 0)
						THEN (A.META_ANNIO_FINAL + ((1 - A.VLR_LIMITE_SUPERIOR) * A.META_ANNIO_FINAL))
					 WHEN (A.DESC_META_NORMALIZADA = 'No' AND (A.DESC_SENTIDO = 'Negativo' OR A.META_ANNIO_FINAL < 0))
						THEN (A.META_ANNIO_FINAL + ((1 - A.VLR_LIMITE_SUPERIOR) * A.META_ANNIO_FINAL))
					 WHEN (A.DESC_META_NORMALIZADA = 'Si' AND (A.DESC_SENTIDO = 'Negativo' OR A.META_ANNIO_FINAL < 0))
						THEN (A.META_ANNIO_FINAL + ((1 - A.VLR_LIMITE_SUPERIOR) * A.META_ANNIO_FINAL))
					 WHEN (A.DESC_META_NORMALIZADA = 'No')
						THEN (A.VLR_LIMITE_SUPERIOR * A.META_ANNIO_FINAL)
					 WHEN (A.DESC_META_NORMALIZADA = 'Si')
						THEN (A.VLR_LIMITE_SUPERIOR * A.META_ANNIO_FINAL)
					 ELSE NULL END AS VLR_LIMITE_SUPERIOR_ANNIO
					
		FROM SUBNIVEL2 A),

  SUBNIVEL4  
  AS ( SELECT A.*
 			  , CASE WHEN (A.DESC_SENTIDO = 'Positivo' AND (A.REAL_ACUMULADO > A.VLR_LIMITE_INFERIOR_ANNIO) AND (A.REAL_ACUMULADO < A.META_ANNIO_FINAL))
						THEN 1
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND (A.REAL_ACUMULADO > A.META_ANNIO_FINAL) AND (A.REAL_ACUMULADO < A.VLR_LIMITE_SUPERIOR_ANNIO))
						THEN 2
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND (A.REAL_ACUMULADO < A.VLR_LIMITE_INFERIOR_ANNIO))
						THEN 3
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND (A.REAL_ACUMULADO > A.VLR_LIMITE_SUPERIOR_ANNIO))
						THEN 4
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND (A.REAL_ACUMULADO > A.META_ANNIO_FINAL AND A.REAL_ACUMULADO < A.VLR_LIMITE_INFERIOR_ANNIO))
						THEN 1
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND (A.REAL_ACUMULADO > A.VLR_LIMITE_SUPERIOR_ANNIO AND A.REAL_ACUMULADO < A.META_ANNIO_FINAL))
						THEN 2
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND (A.REAL_ACUMULADO > A.VLR_LIMITE_INFERIOR_ANNIO))
						THEN 5
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND (A.REAL_ACUMULADO < A.VLR_LIMITE_SUPERIOR_ANNIO))
						THEN 6
					 ELSE  NULL  END AS RECTA_ANNIO

 			  , CASE WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO > A.VLR_LIMITE_INFERIOR_ANNIO AND A.VLR_PROYECCION_ANNIO_ESC_BAJO < A.META_ANNIO_FINAL)
						THEN 1
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO > A.META_ANNIO_FINAL AND A.VLR_PROYECCION_ANNIO_ESC_BAJO < A.VLR_LIMITE_SUPERIOR_ANNIO)
						THEN 2
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO < A.VLR_LIMITE_INFERIOR_ANNIO)
						THEN 3
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO > A.VLR_LIMITE_SUPERIOR_ANNIO)
						THEN 4
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO > A.META_ANNIO_FINAL AND A.VLR_PROYECCION_ANNIO_ESC_BAJO < A.VLR_LIMITE_INFERIOR_ANNIO)
						THEN 1
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO > A.VLR_LIMITE_SUPERIOR_ANNIO AND A.VLR_PROYECCION_ANNIO_ESC_BAJO < A.META_ANNIO_FINAL)
						THEN 2
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO > A.VLR_LIMITE_INFERIOR_ANNIO)
						THEN 3
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO < A.VLR_LIMITE_SUPERIOR_ANNIO)
						THEN 4
					 ELSE NULL END AS RECTA_ANNIO_ESC_BAJO

 			  , CASE WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO > A.VLR_LIMITE_INFERIOR_ANNIO AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO < A.META_ANNIO_FINAL)
						THEN 1
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO > A.META_ANNIO_FINAL AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO < A.VLR_LIMITE_SUPERIOR_ANNIO)
						THEN 2
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO < A.VLR_LIMITE_INFERIOR_ANNIO)
						THEN 3
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO > A.VLR_LIMITE_SUPERIOR_ANNIO)
						THEN 4
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO > A.META_ANNIO_FINAL AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO < A.VLR_LIMITE_INFERIOR_ANNIO)
						THEN 1
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO > A.VLR_LIMITE_SUPERIOR_ANNIO AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO < A.META_ANNIO_FINAL)
						THEN 2
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO > A.VLR_LIMITE_INFERIOR_ANNIO)
						THEN 3
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO < A.VLR_LIMITE_SUPERIOR_ANNIO)
						THEN 4
					 ELSE NULL END AS RECTA_ANNIO_ESC_MEDIO
					 
 			  , CASE WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO > A.VLR_LIMITE_INFERIOR_ANNIO AND A.VLR_PROYECCION_ANNIO_ESC_ALTO < A.META_ANNIO_FINAL)
						THEN 1
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO > A.META_ANNIO_FINAL AND A.VLR_PROYECCION_ANNIO_ESC_ALTO < A.VLR_LIMITE_SUPERIOR_ANNIO)
						THEN 2
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO < A.VLR_LIMITE_INFERIOR_ANNIO)
						THEN 3
					 WHEN (A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO > A.VLR_LIMITE_SUPERIOR_ANNIO)
						THEN 4
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO > A.META_ANNIO_FINAL AND A.VLR_PROYECCION_ANNIO_ESC_ALTO < A.VLR_LIMITE_INFERIOR_ANNIO)
						THEN 1
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO > A.VLR_LIMITE_SUPERIOR_ANNIO AND A.VLR_PROYECCION_ANNIO_ESC_ALTO < A.META_ANNIO_FINAL)
						THEN 2
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO > A.VLR_LIMITE_INFERIOR_ANNIO)
						THEN 3
					 WHEN (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO < A.VLR_LIMITE_SUPERIOR_ANNIO)
						THEN 4
					 ELSE NULL END AS RECTA_ANNIO_ESC_ALTO
	  
		FROM SUBNIVEL3 A )

SELECT * INTO #TEMPCVC_DESEMPENO_TABLERO FROM SUBNIVEL4;
 
  WITH SUBNIVEL5  
	  AS ( SELECT A.*,
	                CASE WHEN A.MES <> 12
							THEN NULL
						 WHEN A.RECTA_ANNIO = 1 AND (A.PRC_LIMITE_INFERIOR_CVR IS NOT NULL) AND (A.PRC_META_CVR IS NOT NULL) 
						      AND (A.META_ANNIO_FINAL IS NOT NULL OR A.META_ANNIO_FINAL <> 0) AND (A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL)
							THEN ((A.PRC_META_CVR - A.PRC_LIMITE_INFERIOR_CVR) / NULLIF((A.META_ANNIO_FINAL - A.VLR_LIMITE_INFERIOR_ANNIO),0))
						 WHEN A.RECTA_ANNIO = 2 AND (A.PRC_LIMITE_SUPERIOR_CVR IS NOT NULL) AND (A.PRC_META_CVR IS NOT NULL) 
						      AND (A.VLR_LIMITE_SUPERIOR_ANNIO IS NOT NULL) AND (A.META_ANNIO_FINAL IS NOT NULL OR A.META_ANNIO_FINAL <> 0)
							THEN ((A.PRC_LIMITE_SUPERIOR_CVR - A.PRC_META_CVR) / NULLIF((A.VLR_LIMITE_SUPERIOR_ANNIO - A.META_ANNIO_FINAL),0))	 
						 ELSE NULL  END AS P_ANNIO
		

				  , CASE WHEN A.RECTA_ANNIO_ESC_BAJO = 1 AND (A.PRC_LIMITE_INFERIOR_CVR IS NOT NULL) AND (A.PRC_META_CVR IS NOT NULL) 
				              AND (A.META_ANNIO_FINAL IS NOT NULL OR A.META_ANNIO_FINAL <> 0) AND (A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL)
							THEN ((A.PRC_META_CVR - A.PRC_LIMITE_INFERIOR_CVR) / NULLIF((A.META_ANNIO_FINAL - A.VLR_LIMITE_INFERIOR_ANNIO),0))
					 WHEN A.RECTA_ANNIO_ESC_BAJO = 2 AND (A.PRC_LIMITE_SUPERIOR_CVR IS NOT NULL) AND (A.PRC_META_CVR IS NOT NULL) 
					     AND (A.META_ANNIO_FINAL IS NOT NULL OR A.META_ANNIO_FINAL <> 0) AND (A.VLR_LIMITE_SUPERIOR_ANNIO IS NOT NULL)
						THEN ((A.PRC_LIMITE_SUPERIOR_CVR - A.PRC_META_CVR) / NULLIF((A.VLR_LIMITE_SUPERIOR_ANNIO - A.META_ANNIO_FINAL),0))
						 ELSE NULL END AS P_ESC_BAJO

				  , CASE WHEN A.RECTA_ANNIO_ESC_MEDIO = 1 AND (A.PRC_LIMITE_INFERIOR_CVR IS NOT NULL) AND (A.PRC_META_CVR IS NOT NULL) 
				              AND (A.META_ANNIO_FINAL IS NOT NULL OR A.META_ANNIO_FINAL <> 0) AND (A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL)
							THEN ((A.PRC_META_CVR - A.PRC_LIMITE_INFERIOR_CVR) / NULLIF((A.META_ANNIO_FINAL - A.VLR_LIMITE_INFERIOR_ANNIO),0))
						 WHEN A.RECTA_ANNIO_ESC_MEDIO = 2 AND (A.PRC_LIMITE_SUPERIOR_CVR IS NOT NULL) AND (A.PRC_META_CVR IS NOT NULL) 
				              AND (A.META_ANNIO_FINAL IS NOT NULL OR A.META_ANNIO_FINAL <> 0) AND (A.VLR_LIMITE_SUPERIOR_ANNIO IS NOT NULL)
							THEN ((A.PRC_LIMITE_SUPERIOR_CVR - A.PRC_META_CVR) / NULLIF((A.VLR_LIMITE_SUPERIOR_ANNIO - A.META_ANNIO_FINAL),0))
						 ELSE NULL END AS P_ESC_MEDIO

				  , CASE WHEN A.RECTA_ANNIO_ESC_ALTO = 1 AND (A.PRC_LIMITE_INFERIOR_CVR IS NOT NULL) AND (A.PRC_META_CVR IS NOT NULL) 
				              AND (A.META_ANNIO_FINAL IS NOT NULL OR A.META_ANNIO_FINAL <> 0) AND (A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL)
							THEN ((A.PRC_META_CVR - A.PRC_LIMITE_INFERIOR_CVR) / NULLIF((A.META_ANNIO_FINAL - A.VLR_LIMITE_INFERIOR_ANNIO),0))
						 WHEN A.RECTA_ANNIO_ESC_ALTO = 2 AND (A.PRC_LIMITE_SUPERIOR_CVR IS NOT NULL)AND (A.PRC_META_CVR IS NOT NULL) 
				              AND (A.META_ANNIO_FINAL IS NOT NULL OR A.META_ANNIO_FINAL <> 0) AND (A.VLR_LIMITE_SUPERIOR_ANNIO IS NOT NULL)
							THEN ((A.PRC_LIMITE_SUPERIOR_CVR - A.PRC_META_CVR) / NULLIF((A.VLR_LIMITE_SUPERIOR_ANNIO - A.META_ANNIO_FINAL),0))
						 ELSE NULL END AS P_ESC_ALTO
						 
			FROM #TEMPCVC_DESEMPENO_TABLERO A ),

	  SUBNIVEL6
	  AS ( SELECT A.*
				  , CASE WHEN (A.P_ANNIO IS NULL)
							THEN NULL
						 ELSE (A.P_ANNIO * A.META_ANNIO_FINAL)
						 END AS PX_ANNIO

				  , CASE WHEN (A.P_ESC_BAJO IS NULL)
							THEN NULL
						 ELSE (A.P_ESC_BAJO * A.META_ANNIO_FINAL)
						 END AS PX_ESC_BAJO

				  , CASE WHEN (A.P_ESC_MEDIO IS NULL) 
							THEN NULL 
						 ELSE (A.P_ESC_MEDIO * A.META_ANNIO_FINAL)
						 END AS PX_ESC_MEDIO

				  , CASE WHEN (A.P_ESC_ALTO IS NULL)
							THEN NULL
						 ELSE (A.P_ESC_ALTO * A.META_ANNIO_FINAL)
						 END AS PX_ESC_ALTO

			FROM SUBNIVEL5 A ),
			
	  SUBNIVEL7 
	  AS ( SELECT A.*
				  ,(A.PRC_META_CVR - A.PX_ANNIO) AS  B_ANNIO

				  ,(A.PRC_META_CVR - A.PX_ESC_BAJO) AS B_ESC_BAJO

				  ,(A.PRC_META_CVR - A.PX_ESC_MEDIO) AS B_ESC_MEDIO

				  ,(A.PRC_META_CVR - A.PX_ESC_ALTO) AS 	B_ESC_ALTO	  

				  
			FROM SUBNIVEL6 A ),

	  SUBNIVEL8
	  AS ( SELECT A.*
	         
				  , CASE WHEN (A.MES <> 12)
				           THEN NULL
			            WHEN (A.REAL_ACUMULADO = 0 AND A.META_ANNIO_FINAL = 0 )
						   THEN 1					
						WHEN (((A.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND (A.REAL_ACUMULADO > A.META_ANNIO_FINAL) AND A.DESC_SENTIDO ='Positivo'))
						   THEN A.PRC_META_CVR						 
						WHEN (((A.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND (A.REAL_ACUMULADO < A.META_ANNIO_FINAL) AND A.DESC_SENTIDO ='Negativo'))
						   THEN A.PRC_META_CVR					
						WHEN (((A.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND (A.REAL_ACUMULADO < A.META_ANNIO_FINAL) AND A.DESC_SENTIDO ='Positivo'))
						   THEN 0
						WHEN (((A.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND (A.REAL_ACUMULADO > A.META_ANNIO_FINAL) AND A.DESC_SENTIDO ='Negativo')) 
						   THEN 0				
                        WHEN (A.VLR_LIMITE_SUPERIOR_ANNIO IS NOT NULL AND ((A.DESC_SENTIDO = 'Positivo' AND A.REAL_ACUMULADO >= A.VLR_LIMITE_SUPERIOR_ANNIO) 
                          OR (A.DESC_SENTIDO = 'Negativo' AND A.REAL_ACUMULADO <= A.VLR_LIMITE_SUPERIOR_ANNIO)))
					   	   THEN A.PRC_LIMITE_SUPERIOR_CVR	   
						WHEN (A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL AND ((A.DESC_SENTIDO = 'Positivo' AND A.REAL_ACUMULADO < A.VLR_LIMITE_INFERIOR_ANNIO)
                             OR (A.DESC_SENTIDO = 'Negativo' AND A.REAL_ACUMULADO > A.VLR_LIMITE_INFERIOR_ANNIO)))
						   THEN 0 
						WHEN (A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL AND (A.REAL_ACUMULADO = A.VLR_LIMITE_INFERIOR_ANNIO))
					       THEN A.PRC_LIMITE_INFERIOR_CVR  
                        WHEN (A.REAL_ACUMULADO = A.META_ANNIO_FINAL) 
						   THEN A.PRC_META_CVR
						ELSE ((A.P_ANNIO * A.REAL_ACUMULADO) + A.B_ANNIO) END AS CVR_ANNIO

				  , CASE WHEN (A.META_ANNIO_FINAL IS NULL) OR A.VLR_PROYECCION_ANNIO_ESC_BAJO IS NULL
			               THEN NULL
				         WHEN (A.VLR_PROYECCION_ANNIO_ESC_BAJO = 0 AND A.META_ANNIO_FINAL = 0)
							THEN 1
						 WHEN (((A.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_BAJO > A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Positivo'))	
							THEN A.PRC_META_CVR
						 WHEN (((A.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_BAJO < A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Negativo'))
							THEN A.PRC_META_CVR
						 WHEN (((A.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_BAJO < A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Positivo'))	
							THEN 0
						 WHEN (((A.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_BAJO > A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Negativo'))	
							THEN 0
						 WHEN (((A.VLR_LIMITE_SUPERIOR_ANNIO IS NOT NULL AND A.META_ANNIO_FINAL IS NOT NULL) AND ((A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO >= A.VLR_LIMITE_SUPERIOR_ANNIO) 
							 OR (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO <= A.VLR_LIMITE_SUPERIOR_ANNIO))))
							THEN A.PRC_LIMITE_SUPERIOR_CVR
						 WHEN (((A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL AND A.META_ANNIO_FINAL IS NOT NULL) AND ((A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO < A.VLR_LIMITE_INFERIOR_ANNIO) 
							 OR (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_BAJO > A.VLR_LIMITE_INFERIOR_ANNIO))))
							THEN 0
						 WHEN ((A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL AND A.META_ANNIO_FINAL IS NOT NULL) AND (A.VLR_PROYECCION_ANNIO_ESC_BAJO = A.VLR_LIMITE_INFERIOR_ANNIO))	   
							THEN A.PRC_LIMITE_INFERIOR_CVR
						 WHEN (A.VLR_PROYECCION_ANNIO_ESC_BAJO = A.META_ANNIO_FINAL)
							THEN A.PRC_META_CVR
						 ELSE ((A.P_ESC_BAJO * A.VLR_PROYECCION_ANNIO_ESC_BAJO) + A.B_ESC_BAJO) END AS CVR_ESC_BAJO

				  , CASE WHEN (A.META_ANNIO_FINAL IS NULL) OR A.VLR_PROYECCION_ANNIO_ESC_MEDIO IS NULL
			               THEN NULL
				         WHEN (A.VLR_PROYECCION_ANNIO_ESC_MEDIO = 0 AND A.META_ANNIO_FINAL = 0) 
							THEN 1
						 WHEN (((A.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO > A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Positivo'))
							THEN A.PRC_META_CVR
						 WHEN (((A.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO < A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Negativo'))	
							THEN A.PRC_META_CVR
						 WHEN (((A.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO < A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Positivo'))
							THEN 0
						 WHEN (((A.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO > A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Negativo'))
							THEN 0
						 WHEN (((A.VLR_LIMITE_SUPERIOR_ANNIO IS NOT NULL AND A.META_ANNIO_FINAL IS NOT NULL) AND ((A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO >= A.VLR_LIMITE_SUPERIOR_ANNIO) 
							 OR (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO <= A.VLR_LIMITE_SUPERIOR_ANNIO))))
							THEN A.PRC_LIMITE_SUPERIOR_CVR
						 WHEN (((A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL AND A.META_ANNIO_FINAL IS NOT NULL) AND ((A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO < A.VLR_LIMITE_INFERIOR_ANNIO) 
							 OR (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_MEDIO > A.VLR_LIMITE_INFERIOR_ANNIO))))
							THEN 0
						 WHEN ((A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL AND A.META_ANNIO_FINAL IS NOT NULL) AND (A.VLR_PROYECCION_ANNIO_ESC_MEDIO = A.VLR_LIMITE_INFERIOR_ANNIO))
							THEN A.PRC_LIMITE_INFERIOR_CVR
						 WHEN (A.VLR_PROYECCION_ANNIO_ESC_MEDIO = A.META_ANNIO_FINAL)
							THEN A.PRC_META_CVR
						 ELSE ((A.P_ESC_MEDIO * A.VLR_PROYECCION_ANNIO_ESC_MEDIO) + A.B_ESC_MEDIO) END AS  CVR_ESC_MEDIO

				  , CASE WHEN (A.META_ANNIO_FINAL IS NULL) OR A.VLR_PROYECCION_ANNIO_ESC_ALTO IS NULL
			                THEN NULL
				         WHEN (A.VLR_PROYECCION_ANNIO_ESC_ALTO = 0 AND A.META_ANNIO_FINAL = 0)
							THEN 1
						 WHEN (((A.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_ALTO > A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Positivo'))		
							THEN A.PRC_META_CVR
						 WHEN (((A.VLR_LIMITE_SUPERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_ALTO < A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Negativo'))	
							THEN A.PRC_META_CVR
						 WHEN (((A.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_ALTO < A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Positivo'))	
							THEN 0
						 WHEN (((A.VLR_LIMITE_INFERIOR_ANNIO IS NULL) AND A.VLR_PROYECCION_ANNIO_ESC_ALTO > A.META_ANNIO_FINAL AND A.DESC_SENTIDO = 'Negativo'))
							THEN 0
						 WHEN ((A.VLR_LIMITE_SUPERIOR_ANNIO IS NOT NULL) AND ((A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO >= A.VLR_LIMITE_SUPERIOR_ANNIO)
							 OR (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO <= A.VLR_LIMITE_SUPERIOR_ANNIO)) )
							THEN A.PRC_LIMITE_SUPERIOR_CVR
						 WHEN ((A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL) AND ((A.DESC_SENTIDO = 'Positivo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO < A.VLR_LIMITE_INFERIOR_ANNIO) 
							OR (A.DESC_SENTIDO = 'Negativo' AND A.VLR_PROYECCION_ANNIO_ESC_ALTO > A.VLR_LIMITE_INFERIOR_ANNIO)) )
							THEN 0
						 WHEN (A.VLR_LIMITE_INFERIOR_ANNIO IS NOT NULL) AND (A.VLR_PROYECCION_ANNIO_ESC_ALTO = A.VLR_LIMITE_INFERIOR_ANNIO)
							THEN A.PRC_LIMITE_INFERIOR_CVR
						 WHEN (A.VLR_PROYECCION_ANNIO_ESC_ALTO = A.META_ANNIO_FINAL)
							THEN A.PRC_META_CVR		
						 ELSE ((A.P_ESC_ALTO * A.VLR_PROYECCION_ANNIO_ESC_ALTO) + A.B_ESC_ALTO) END AS CVR_ESC_ALTO
				  
			FROM SUBNIVEL7 A  ),

	FINAL 
	  AS ( SELECT 
	     FK_PARAM_INDICADOR,
		 FK_INDICADOR,
		 FK_TABLERO,
		 FK_PERIODO,
		 DESC_PERIODO,
		 DESC_SENTIDO,
		 DESC_META_NORMALIZADA,
		 DESC_ACCIONES_DE_ASEGURAMIENTO,
		 DESC_PREMISAS_ESC_BAJO,
		 DESC_PREMISAS_ESC_MEDIO,
		 DESC_PREMISAS_ESC_ALTO,
		 DESC_CAUSAS_DESEMPENO_ACUM,
		 DESC_CAUSAS_DESEMPENO_PERIODO,
		 DESC_TBG,
		 DTM_FECHACARGA,
		 DESC_RESPONSABLE_MEDICION,
		 DESC_CARGO_RESPONSABLE_MEDICION,
		 DESC_CORREO_RESPONSABLE_MEDICION,
		 DESC_RESPONSABLE_MEDICION_2,
		 DESC_CARGO_RESPONSABLE_MEDICION_2,
		 DESC_CORREO_RESPONSABLE_MEDICION_2,
		 DESC_REFERENTE,
		 DESC_SECUENCIA_ORDEN,
		 DESC_CORTO_LARGO_PLAZO,
		 DESC_TIPO_TABLERO,
		 DESC_FRECUENCIA,
		 DESC_HITO_INDICADOR,
		 DESC_DETALLE_INDICADOR,
		 DESC_NOMBRE_INDICADOR,
		 DESC_OBJETIVO,
		 ID_INDICADOR,
		 DESC_VERSION,
		 TRY_CAST(NUM_ORDEN_PALANCA AS BIGINT) AS NUM_ORDEN_PALANCA,   
	     NUM_ORDEN_OBJETIVO,
		 DESC_EJE_PALANCA,
		 DESC_NIVEL,
		 DESC_SIGLA_AREA,
		 DESC_RUTINA,
		 DESC_GERENCIA,
		 DESC_UNIDAD_NEGOCIO_NVL_2,
		 DESC_UNIDAD_NEGOCIO_NVL_3,
		 DESC_SEGMENTO,
		 DESC_GRUPO_SEGMENTO,
		 DESC_VP_EJECUTIVA,
		 DESC_EMPRESA,
		 DESC_GRUPO,
		 DESC_TABLERO,
		 CANT_DECIMALES_CALCULO,
		 CANT_DECIMALES_REPORTE,
		 PRC_META_CVR,
		 PRC_LIMITE_SUPERIOR_CVR,
		 PRC_LIMITE_INFERIOR_CVR,
		 DESC_ESTANDAR,  
		 '' AS FK_CONFIG_TABLERO,
		 VLR_PESO_INDICADOR,
		 VLR_LIMITE_INFERIOR,
		 VLR_LIMITE_SUPERIOR,
		 DESC_ANNIO,
		 DESC_TABLERO_CVR, 
		 MES,
		 FECHA_CARGA_SYNAPSE,
		 FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
		 SUM(REAL_PERIODO) AS REAL_PERIODO,
		 SUM(REAL_ACUMULADO) AS REAL_ACUMULADO,
		 SUM(PLAN_PERIODO) AS PLAN_PERIODO,
		 SUM(PLAN_ACUMULADO) AS PLAN_ACUMULADO,
		 SUM(PLAN_PERIODO_NORMALIZADO) AS PLAN_PERIODO_NORMALIZADO,
		 SUM(PLAN_ACUMULADO_NORMALIZADO) AS PLAN_ACUMULADO_NORMALIZADO,
		 SUM(META_ANNIO) AS META_ANNIO,
		 SUM(META_ANNIO_NORMALIZADO) AS META_ANNIO_NORMALIZADO,
		 SUM(META_ANNIO_1) AS META_ANNIO_1,
		 SUM(META_ANNIO_2) AS META_ANNIO_2,
		 SUM(PROYECCION_PERIODO_1) AS PROYECCION_PERIODO_1,
		 SUM(PROYECCION_PERIODO_2) AS PROYECCION_PERIODO_2,
		 SUM(PROYECCION_PERIODO_3) AS PROYECCION_PERIODO_3,
		 VLR_PROYECCION_ANNIO_ESC_BAJO AS VLR_PROYECCION_ANNIO_ESC_BAJO,
		 VLR_PROYECCION_ANNIO_ESC_MEDIO AS VLR_PROYECCION_ANNIO_ESC_MEDIO,
		 VLR_PROYECCION_ANNIO_ESC_ALTO AS VLR_PROYECCION_ANNIO_ESC_ALTO,
		 SUM(PRC_CUMP_PERIODO) AS PRC_CUMP_PERIODO,
		 SUM(PRC_CUMP_ACUMULADO) AS PRC_CUMP_ACUMULADO,
		 SUM(PRC_CUMP_ANNIO_ESC_BAJO) AS PRC_CUMP_ANNIO_ESC_BAJO,
		 SUM(PRC_CUMP_ANNIO_ESC_MEDIO) AS PRC_CUMP_ANNIO_ESC_MEDIO,
		 SUM(PRC_CUMP_ANNIO_ESC_ALTO) AS PRC_CUMP_ANNIO_ESC_ALTO,
		 SUM(PRC_DESEMPENO_PERIODO) AS PRC_DESEMPENO_PERIODO,
		 SUM(PRC_DESEMPENO_ACUMULADO) AS PRC_DESEMPENO_ACUMULADO,
		 SUM(PRC_DESEMPENO_ANNIO_ESC_BAJO) AS PRC_DESEMPENO_ANNIO_ESC_BAJO,
		 SUM(PRC_DESEMPENO_ANNIO_ESC_MEDIO) AS PRC_DESEMPENO_ANNIO_ESC_MEDIO,
		 SUM(PRC_DESEMPENO_ANNIO_ESC_ALTO) AS PRC_DESEMPENO_ANNIO_ESC_ALTO,
		 SUM(VLR_LIMITE_INFERIOR_ANNIO) AS VLR_LIMITE_INFERIOR_ANNIO,
		 SUM(VLR_LIMITE_SUPERIOR_ANNIO) AS VLR_LIMITE_SUPERIOR_ANNIO,
		 SUM(VLR_LIMITE_INFERIOR_ACUMULADO) AS VLR_LIMITE_INFERIOR_ACUMULADO,
		 SUM(VLR_LIMITE_SUPERIOR_ACUMULADO) AS VLR_LIMITE_SUPERIOR_ACUMULADO,
		 SUM(VLR_LIMITE_INFERIOR_PERIODO) AS VLR_LIMITE_INFERIOR_PERIODO,
		 SUM(VLR_LIMITE_SUPERIOR_PERIODO) AS VLR_LIMITE_SUPERIOR_PERIODO,
		 SUM(META_ANNIO_FINAL) AS META_ANNIO_FINAL,
		 SUM(RECTA_ANNIO) AS RECTA_ANNIO,
		 SUM(RECTA_ANNIO_ESC_BAJO) AS RECTA_ANNIO_ESC_BAJO,
		 SUM(RECTA_ANNIO_ESC_MEDIO) AS RECTA_ANNIO_ESC_MEDIO,
		 SUM(RECTA_ANNIO_ESC_ALTO) AS RECTA_ANNIO_ESC_ALTO,
		 SUM(P_ANNIO) AS P_ANNIO,
		 SUM(PX_ANNIO) AS PX_ANNIO,
		 SUM(B_ANNIO) AS B_ANNIO,
		 SUM(CVR_ANNIO) AS CVR_ANNIO,
		 SUM(P_ESC_BAJO) AS P_ESC_BAJO,
		 SUM(PX_ESC_BAJO) AS PX_ESC_BAJO,
		 SUM(B_ESC_BAJO) AS B_ESC_BAJO,
		 SUM(CVR_ESC_BAJO) AS CVR_ESC_BAJO,
		 SUM(P_ESC_MEDIO) AS P_ESC_MEDIO,
		 SUM(PX_ESC_MEDIO) AS PX_ESC_MEDIO,
		 SUM(B_ESC_MEDIO) AS B_ESC_MEDIO,
		 SUM(CVR_ESC_MEDIO) AS CVR_ESC_MEDIO,
		 SUM(P_ESC_ALTO) AS P_ESC_ALTO,
		 SUM(PX_ESC_ALTO) AS PX_ESC_ALTO,
		 SUM(B_ESC_ALTO) AS B_ESC_ALTO,
		 SUM(CVR_ESC_ALTO) AS CVR_ESC_ALTO 

	FROM SUBNIVEL8
	GROUP BY FK_PARAM_INDICADOR,
		 FK_INDICADOR,
		 FK_TABLERO,
		 CAST(FK_PERIODO AS VARCHAR),
		 DESC_PERIODO,
		 DESC_SENTIDO,
		 DESC_META_NORMALIZADA,
		 DESC_ACCIONES_DE_ASEGURAMIENTO,
		 DESC_PREMISAS_ESC_BAJO,
		 DESC_PREMISAS_ESC_MEDIO,
		 DESC_PREMISAS_ESC_ALTO,
		 DESC_CAUSAS_DESEMPENO_ACUM,
		 DESC_CAUSAS_DESEMPENO_PERIODO,
		 DESC_TBG,
		 DTM_FECHACARGA,
		 DESC_RESPONSABLE_MEDICION,
		 DESC_CARGO_RESPONSABLE_MEDICION,
		 DESC_CORREO_RESPONSABLE_MEDICION,
		 DESC_RESPONSABLE_MEDICION_2,
		 DESC_CARGO_RESPONSABLE_MEDICION_2,
		 DESC_CORREO_RESPONSABLE_MEDICION_2,
		 DESC_REFERENTE,
		 DESC_SECUENCIA_ORDEN,
		 DESC_CORTO_LARGO_PLAZO,
		 DESC_TIPO_TABLERO,
		 DESC_FRECUENCIA,
		 DESC_HITO_INDICADOR,
		 DESC_DETALLE_INDICADOR,
		 DESC_NOMBRE_INDICADOR,
		 DESC_OBJETIVO,
		 ID_INDICADOR,
		 DESC_VERSION,
		 DESC_EJE_PALANCA,
		 NUM_ORDEN_PALANCA,   
	     NUM_ORDEN_OBJETIVO,
		 DESC_NIVEL,
		 DESC_SIGLA_AREA,
		 DESC_RUTINA,
		 DESC_GERENCIA,
		 DESC_UNIDAD_NEGOCIO_NVL_2,
		 DESC_UNIDAD_NEGOCIO_NVL_3,
		 DESC_SEGMENTO,
		 DESC_GRUPO_SEGMENTO,
		 DESC_VP_EJECUTIVA,
		 DESC_EMPRESA,
		 DESC_GRUPO,
		 DESC_TABLERO,
		 CANT_DECIMALES_CALCULO,
		 CANT_DECIMALES_REPORTE,
		 PRC_META_CVR,
		 PRC_LIMITE_SUPERIOR_CVR,
		 PRC_LIMITE_INFERIOR_CVR,
		 DESC_ESTANDAR,
		 VLR_PESO_INDICADOR,
		 VLR_LIMITE_INFERIOR,
		 VLR_LIMITE_SUPERIOR,
		 DESC_ANNIO,
		 DESC_TABLERO_CVR,
		 MES,
		 FECHA_CARGA_SYNAPSE,
		 FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
		 VLR_PROYECCION_ANNIO_ESC_BAJO,
		 VLR_PROYECCION_ANNIO_ESC_MEDIO,
		 VLR_PROYECCION_ANNIO_ESC_ALTO
	)

INSERT INTO ATOMO.TMP2CVC_DESEMPENO_TABLERO 
SELECT * FROM FINAL;

SET @sql = 'CREATE VIEW [ATOMO].[CVC_DESEMPENO_TABLERO]  AS SELECT * FROM [ATOMO].[TMP2CVC_DESEMPENO_TABLERO]';

EXEC [dbo].[sp_executesql] @sql;