-- =============================================
-- Author:      Alejandro Vargas Valbuena
-- Create Date: 2023-04-05
-- Description: Se crea el Store Procedure SP_FACT_HITO_INICIAL para el llenado inicial de la tabla ATOMO.DWH.FACT_HITO
CREATE PROC [ATOMO].[SP_FACT_HITO_INICIAL] AS 
 SET NOCOUNT ON;

	IF OBJECT_ID('tempdb..#UnionTablas') IS NOT NULL
    BEGIN
        DROP TABLE #UnionTablas
    END;

		IF OBJECT_ID('tempdb..#TablaTemporal') IS NOT NULL
    BEGIN
        DROP TABLE #TablaTemporal
    END;

		IF OBJECT_ID('tempdb..#FkHito') IS NOT NULL
    BEGIN
        DROP TABLE #FkHito
    END;

		IF OBJECT_ID('tempdb..#Unicos') IS NOT NULL
    BEGIN
        DROP TABLE #Unicos
    END;

		IF OBJECT_ID('tempdb..#TablaValoresFuera') IS NOT NULL
    BEGIN
        DROP TABLE #TablaValoresFuera
    END;

		IF OBJECT_ID('tempdb..#Final') IS NOT NULL
    BEGIN
        DROP TABLE #Final
    END;
CREATE TABLE #UnionTablas (FK_HITO VARCHAR(50),FK_PARAM_INDICADOR VARCHAR(50), FK_PERIODO VARCHAR(50), FK_TIEMPO VARCHAR(50),VLR_PLAN_HITO decimal(25,10),VLR_REAL_HITO decimal(25,10),PRC_CUMP_HITO decimal(25,10),VLR_PROY_ESC_BAJO decimal(25,10),VLR_PROY_ESC_MEDIO decimal(25,10),VLR_PROY_ESC_ALTO decimal(25,10),DESC_CORREO_USUARIO VARCHAR(250),DTM_FECHA_EVENTO_REGISTRO datetime,DTM_FECHACARGA datetime,DESC_ORIGEN VARCHAR(80),FK_TIPOSINCONSISTENCIA VARCHAR(50),FECHA_CARGA_SYNAPSE datetime,FECHA_PROXIMA_ACTUALIZA_SYNAPSE datetime,CM_RESUMEN Varchar(500) );
CREATE TABLE #TablaTemporal (FK_HITO VARCHAR(50), FK_PARAM_INDICADOR VARCHAR(50), FK_PERIODO VARCHAR(50));
CREATE TABLE #FkHito (FK_HITO VARCHAR(50),FK_PARAM_INDICADOR VARCHAR(50),ROW_NUM INT);
CREATE TABLE #Unicos (FK_HITO VARCHAR(50),FK_PARAM_INDICADOR VARCHAR(50));
CREATE TABLE #Final (FK_HITO VARCHAR(50),FK_PARAM_INDICADOR VARCHAR(50), FK_PERIODO VARCHAR(50), FK_TIEMPO VARCHAR(50),VLR_PLAN_HITO decimal(25,10),VLR_REAL_HITO decimal(25,10),PRC_CUMP_HITO decimal(25,10),VLR_PROY_ESC_BAJO decimal(25,10),VLR_PROY_ESC_MEDIO decimal(25,10),VLR_PROY_ESC_ALTO decimal(25,10),DESC_CORREO_USUARIO VARCHAR(250),DTM_FECHA_EVENTO_REGISTRO datetime,DTM_FECHACARGA datetime,DESC_ORIGEN VARCHAR(80),FK_TIPOSINCONSISTENCIA VARCHAR(50),FECHA_CARGA_SYNAPSE datetime,FECHA_PROXIMA_ACTUALIZA_SYNAPSE datetime,CM_RESUMEN Varchar(500) );

WITH TH_HITO AS(
  SELECT A.[FK_HITO]
      ,A.[FK_PARAM_INDICADOR]
      ,A.[FK_PERIODO]
	  ,CAST(CONCAT(CAST(A.[FK_PERIODO] AS Varchar),'01') AS BIGINT) AS FK_TIEMPO
      ,A.[VLR_PLAN_HITO]
      ,A.[VLR_REAL_HITO]
      ,A.[PRC_CUMP_HITO]
      ,A.[VLR_PROY_ESC_BAJO]
      ,A.[VLR_PROY_ESC_MEDIO]
      ,A.[VLR_PROY_ESC_ALTO]
      ,A.[DESC_CORREO_USUARIO]
      ,A.[DTM_FECHA_EVENTO_REGISTRO]
      ,A.[DTM_FECHACARGA]
      ,A.[DESC_ORIGEN]
      ,A.[FK_TIPOSINCONSISTENCIA]
      ,CAST(CONCAT(CAST(GETDATE() AS DATE),' ',DATEPART(HOUR, dateadd(hour, -7, GETDATE())),':00:00.000')AS DATETIME) AS FECHA_CARGA_SYNAPSE
      ,CAST(CONCAT(CAST(GETDATE() AS DATE),' ',DATEPART(HOUR, dateadd(hour, -5, GETDATE())),':00:00.000')AS DATETIME) AS FECHA_PROXIMA_ACTUALIZA_SYNAPSE
      ,B.[CM_RESUMEN]
FROM [ATOMO].[STG.TH_HITO] A
LEFT JOIN [ATOMO].[STG.TH_HITO_UX] B
		ON A.[FK_HITO] = B.[FK_HITO]
		AND A.[FK_PARAM_INDICADOR] = B.[FK_PARAM_INDICADOR]
		AND A.[FK_PERIODO] = B.[FK_PERIODO]
),

CONFIGURACION_TABLERO AS(
SELECT DISTINCT FK_PARAM_INDICADOR, FK_INDICADOR, DESC_ANNIO, DTM_FECHACARGA
FROM [ATOMO].[STG.DIM_CONFIGURACION_TABLERO_LOG]
WHERE DESC_HITO_INDICADOR='Hito' AND DESC_SIGLA_AREA='ILP'),

NO_EXISTENTES AS(
SELECT DISTINCT 
CT.FK_INDICADOR AS FK_HITO,
CT.FK_PARAM_INDICADOR,
CONCAT(DESC_ANNIO,'01') AS FK_PERIODO,
CONCAT(DESC_ANNIO,'01','01') AS FK_TIEMPO,
NULL AS VLR_PLAN_HITO,
NULL AS VLR_REAL_HITO,
NULL AS PRC_CUM_HITO,
NULL AS VLR_PROY_ESC_BAJO,
NULL AS VLR_PROY_ESC_MEDIO,
NULL AS VLR_PROY_ESC_ALTO,
NULL AS DESC_CORREO_USUARIO,
NULL AS DTM_FECHA_EVENTO_REGISTRO,
CAST(CONCAT(CAST(GETDATE() AS DATE),' ',DATEPART(HOUR, dateadd(hour, -5, GETDATE())),':00:00.000')AS DATETIME) AS DTM_FECHA_CARGA,
'STAGING HITO' AS DESC_ORIGEN,
0 AS FK_TIPOSINCOSISTENCIA,
CAST(CONCAT(CAST(GETDATE() AS DATE),' ',DATEPART(HOUR, dateadd(hour, -5, GETDATE())),':00:00.000')AS DATETIME) AS FECHA_CARGA_SYNAPSE,
CAST(CONCAT(CAST(GETDATE() AS DATE),' ',DATEPART(HOUR, dateadd(hour, -3, GETDATE())),':00:00.000')AS DATETIME) AS FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
NULL AS CM_RESUMEN
FROM CONFIGURACION_TABLERO CT
LEFT JOIN TH_HITO TH ON CT.FK_PARAM_INDICADOR=TH.FK_PARAM_INDICADOR
AND CT.FK_INDICADOR=TH.FK_HITO WHERE TH.FK_PARAM_INDICADOR IS NULL AND TH.FK_HITO IS NULL
),
UNION_TABLAS AS (
SELECT * FROM NO_EXISTENTES 
UNION ALL
SELECT * FROM TH_HITO
)
INSERT INTO #UnionTablas
SELECT * FROM UNION_TABLAS;

WITH FALTANTES AS(
SELECT FK_HITO, FK_PARAM_INDICADOR, COUNT(FK_PERIODO) AS CONTEO FROM #UnionTablas
GROUP BY FK_HITO, FK_PARAM_INDICADOR 
HAVING COUNT(FK_PERIODO)<12
),
HITOS_FALTANTES AS(
SELECT DISTINCT FT.FK_HITO, FT.FK_PARAM_INDICADOR,UT.FK_PERIODO FROM FALTANTES FT
LEFT JOIN #UnionTablas UT ON FT.FK_HITO=UT.FK_HITO AND FT.FK_PARAM_INDICADOR=UT.FK_PARAM_INDICADOR
)

INSERT INTO #TablaTemporal
SELECT * FROM HITOS_FALTANTES

INSERT INTO #Unicos
SELECT DISTINCT FK_HITO, FK_PARAM_INDICADOR FROM #TablaTemporal

INSERT INTO  #FkHito
SELECT DISTINCT FK_HITO, FK_PARAM_INDICADOR, ROW_NUMBER() OVER( ORDER BY FK_HITO ASC) 
AS ROW_NUM FROM #Unicos

			SELECT DISTINCT RIGHT(CONCAT('0',f1.MES),2) as MES,tt1.FK_HITO , tt1.FK_PARAM_INDICADOR
			INTO #TablaValoresFuera
			FROM  [ATOMO].[DWH.DIM_FECHA]  as f1
			inner join #TablaTemporal  as tt1
			on RIGHT(tt1.FK_PERIODO,2) =  RIGHT(CONCAT('0',f1.MES),2)
			inner join #Unicos as u1
			on tt1.FK_HITO=u1.FK_HITO  AND tt1.FK_PARAM_INDICADOR=u1.FK_PARAM_INDICADOR

DECLARE @count INT
DECLARE @rows INT
SELECT @rows = COUNT(*) FROM #FkHito
SET  @count = 1
IF @count <= @rows
	INSERT INTO #Final 
	SELECT 
	DF.FK_HITO,
	DF.FK_PARAM_INDICADOR,
	CONCAT(DF.FK_PERIODO,DF.MES) AS FK_PERIODO,
	CONCAT(DF.FK_PERIODO,DF.MES,'01') as FK_TIEMPO,
	NULL AS VLR_PLAN_HITO,
	NULL AS VLR_REAL_HITO,
	NULL AS PRC_CUM_HITO,
	NULL AS VLR_PROY_ESC_BAJO,
	NULL AS VLR_PROY_ESC_MEDIO,
	NULL AS VLR_PROY_ESC_ALTO,
	NULL AS DESC_CORREO_USUARIO,
	NULL AS DTM_FECHA_EVENTO_REGISTRO,
	CAST(CONCAT(CAST(GETDATE() AS DATE),' ',DATEPART(HOUR, dateadd(hour, -5, GETDATE())),':00:00.000')AS DATETIME) AS DTM_FECHA_CARGA,
	'STAGING HITO' AS DESC_ORIGEN,
	0 AS FK_TIPOSINCOSISTENCIA,
	CAST(CONCAT(CAST(GETDATE() AS DATE),' ',DATEPART(HOUR, dateadd(hour, -5, GETDATE())),':00:00.000')AS DATETIME) AS FECHA_CARGA_SYNAPSE,
	CAST(CONCAT(CAST(GETDATE() AS DATE),' ',DATEPART(HOUR, dateadd(hour, -3, GETDATE())),':00:00.000')AS DATETIME) AS FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
	NULL AS CM_RESUMEN
 FROM(
			SELECT DISTINCT RIGHT(CONCAT('0',f.MES),2) as MES, LEFT(tt.FK_PERIODO,4) as FK_PERIODO, u.FK_HITO , u.FK_PARAM_INDICADOR
			FROM  [ATOMO].[DWH.DIM_FECHA]  as f
			inner join #TablaTemporal  as tt
			on RIGHT(tt.FK_PERIODO,2) <>  RIGHT(CONCAT('0',f.MES),2)
			inner join #Unicos as u
			on tt.FK_HITO=u.FK_HITO  AND tt.FK_PARAM_INDICADOR=u.FK_PARAM_INDICADOR
			where f.MES NOT IN 
			(SELECT MES
			from #TablaValoresFuera 
			where FK_HITO=tt.FK_HITO and FK_PARAM_INDICADOR=tt.FK_PARAM_INDICADOR)
			) DF

SELECT * FROM #Final 
UNION ALL 
SELECT * FROM #UnionTablas
