
-- =============================================

-- Author:      Alejandra Delgado 
-- Update Date: 2023-05-16
-- Description: Se realiza ajuste para la creacion de la tabla temporal TMP2CVC_INDICADORES_ILP

-- =============================================

CREATE TABLE [ATOMO].[TMP2CVC_INDICADORES_ILP]
(
	[% Avance Acumulado ILP] [float] NULL,
	[% Avance ILP Años 1 2] [float] NULL,
	[% Avance ILP Año 1] [float] NULL,
	[% Cumplimiento Año 1] [float] NULL,
	[% Cumplimiento Año 2] [float] NULL,
	[% Cumplimiento Año 3] [float] NULL,
	[% Cumplimiento Años 1 2] [float] NULL,
	[% Cumplimiento Años 1 2 3] [float] NULL,
	[% Cumplimiento Acumulado] [float] NULL,
	[.CC Drill Through Detalle KPI Panel] [varchar](20) NOT NULL,
	[_CC Drill Through Detalle KPI] [varchar](15) NOT NULL,
	[_CC Hito/Ind] [varchar](500) NULL,
	[_CC Reporta Periodo] [int] NULL,
	[Año] [varchar](4) NULL,
	[Cargo Responsable de Medición] [varchar](500) NULL,
	[Cargo Responsable de Medición 2] [varchar](500) NULL,
	[Correo Responsable de Medición] [varchar](500) NULL,
	[Correo Responsable de Medición 2] [varchar](500) NULL,
	[Corto Plazo / Largo Plazo] [varchar](500) NULL,
	[Detalle Indicador] [varchar](500) NULL,
	[Eje o Palanca] [varchar](500) NULL,
	[Empresa] [varchar](500) NULL,
	[Fecha de Carga] [datetime] NULL,
	[FK Indicador] [bigint] NULL,
	[FK Parametrización Indicador] [bigint] NOT NULL,
	[FK Tablero] [bigint] NOT NULL,
	[Vigencia Tablero desde] [date] NULL,
	[Vigencia Tablero hasta] [date] NULL,
	[Frecuencia] [varchar](500) NULL,
	[Gerencia] [varchar](500) NULL,
	[Grupo] [varchar](500) NULL,
	[Grupo Segmento] [varchar](500) NULL,
	[Hito / Indicador] [varchar](501) NULL,
	[ID Indicador] [varchar](50) NULL,
	[Indicador Referente] [varchar](500) NULL,
	[Mes] [nvarchar](4000) NULL,
	[Nivel] [varchar](500) NULL,
	[Nombre Indicador] [varchar](4000) NULL,
	[Nombre Responsable de Medición] [varchar](500) NULL,
	[Nombre Responsable de Medición 2] [varchar](500) NULL,
	[Número de Decimales para el Cálculo] [int] NULL,
	[Objetivo] [varchar](500) NULL,
	[Periodo] [varchar](500) NULL,
	[Año Hito] [varchar](20) NULL,
	[Plan Acum Periodos] [varchar](15) NULL,
	[Periodo Año] [varchar](30) NULL,
	[Rutina] [varchar](500) NULL,
	[Secuencia / Orden] [varchar](8000) NULL,
	[Segmento] [varchar](500) NULL,
	[Sentido] [varchar](500) NULL,
	[Sigla Área] [varchar](500) NOT NULL,
	[Tablero] [varchar](500) NULL,
	[Tiempo] [int] NULL,
	[Tipo Tablero] [varchar](500) NULL,
	[UnidadMedida] [varchar](500) NULL,
	[Unidad de Negocio Nivel 2] [varchar](500) NULL,
	[Unidad de Negocio Nivel 3] [varchar](500) NULL,
	[Valor Peso Indicador] [decimal](25, 10) NULL,
	[Valor Meta Normalizada Año 1] [float] NULL,
	[Valor Meta Normalizada Año 2] [float] NULL,
	[Valor Meta Normalizada Año 3] [float] NULL,
	[Valor Meta Normalizada Años 1 2] [float] NULL,
	[Valor Meta Normalizada Años 1 2 3] [float] NULL,
	[Valor Plan Acumulado] [decimal](38, 10) NULL,
	[Valor Plan Acumulado Normalizada] [float] NULL,
	[Valor Meta Año 1] [float] NULL,
	[Valor Meta Año 2] [float] NULL,
	[Valor Meta Año 3] [float] NULL,
	[Valor Meta Años 1 2] [float] NULL,
	[Valor Meta Años 1 2 3] [float] NULL,
	[Valor Reto] [float] NULL,
	[Valor Proyección Año 1] [float] NULL,
	[Valor Proyección Año 2] [float] NULL,
	[Valor Proyección Año 3] [float] NULL,
	[Valor Proyección Años 1 2] [float] NULL,
	[Valor Proyección Años 1 2 3] [float] NULL,
	[Valor Real Año 1] [decimal](38, 10) NULL,
	[Valor Real Año 2] [decimal](38, 10) NULL,
	[Valor Real Año 3] [decimal](38, 10) NULL,
	[Valor Real Años 1 2] [decimal](38, 10) NULL,
	[Valor Real Años 1 2 3] [decimal](38, 10) NULL,
	[Valor Real Acumulado] [decimal](38, 10) NULL,
	[Valor Real Acumulado_Mes] [float] NULL,
	[Valor Real Proyectado Año 1] [float] NULL,
	[Valor Real Proyectado Año 2] [float] NULL,
	[Valor Real Proyectado Año 3] [float] NULL,
	[Valor Real Proyectado Años 1 2] [float] NULL,
	[Valor Real Proyectado Años 1 2 3] [float] NULL,
	[Versión] [varchar](500) NOT NULL,
	[VP Ejecutiva] [varchar](500) NULL,
	[FECHA_CARGA_SYNAPSE] [datetime] NULL,
	[FECHA_PROXIMA_ACTUALIZA_SYNAPSE] [datetime] NULL,
	[CM_RESUMEN] [varchar](500) NULL,
	[Premisas] [varchar](4000) NULL,
	[Mensaje clave indicador] [varchar](4000) NULL,
	[Hito/Ind Habilitador] [varchar](500) NULL,
	[.CC Nombre Indicador - Detalle] [varchar](4503) NULL,
	[Llave] [varchar](530) NULL,
	[_CC % Cumplimiento ILP Val] [float] NULL,
	[.CC % Cumplimiento tablero Ban] [float] NULL,
	[_CC Valor Brecha] [float] NULL,
	[CC Color Brecha] [varchar](5) NULL,
	[ActivoCumplimientoMin] [int] NULL,
	[CumplimientoMinimo] [numeric](30,10) NULL,
	[ReconocimientoMinimo] [numeric](30,10) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
