-- =============================================
-- Author:      Harold Lopez - Santiago Guzman
-- Create Date: 2022-08-18
-- Description: Se crea la vista CVD_CONFIGURACION_TABLERO_ILP la cual es un insumo para la iniciativba de ILP

-- Author:      Oscar Fabian Angel 
-- Update Date: 2023-03-15
-- Description: Se realiza ajustes para division de registros dependiendo de la vigencia 

-- Author:      Alejandro Vargas
-- Update Date: 2023-04-04
-- Description: Se realiza ajustes para inclusion del campo de fecha del HITO

-- Author:      Oscar Fabian Angel 
-- Update Date: 2023-10-06
-- Description: Se realiza ajustes para inclusion de los campos ACTIVOCUMPLIMIENTOMIN, CUMPLIMIENTOMINIMO, RECONOCIMIENTOMINIMO
-- =============================================

CREATE VIEW [ATOMO].[CVD_CONFIGURACION_TABLERO_ILP] AS 
SELECT LEFT(E.Periodo_Vigencia,4) AS DESC_ANNIO,
	 LEFT(E.Periodo_Vigencia,4) AS DESC_ANNIO_REGISTRO,
	 A.DESC_ANNIO AS DESC_ANNIO_HITO,
	 A.DESC_TABLERO_CVR,
     D.DESC_DETALLE_INDICADOR,
	 A.FK_PARAM_INDICADOR,
	 A.DESC_SIGLA_AREA,
	 E.DESC_TABLERO,
	 A.DESC_VERSION,
     B.DESC_GRUPO,
     B.DESC_EMPRESA,
     B.DESC_VP_EJECUTIVA,
     B.DESC_GRUPO_SEGMENTO,
     B.DESC_SEGMENTO,
     B.DESC_UNIDAD_NEGOCIO_NVL_2,
     B.DESC_UNIDAD_NEGOCIO_NVL_3,
     B.DESC_GERENCIA,
     B.DESC_RUTINA,
	 B.DESC_NIVEL,
	 F.DESC_EJE_PALANCA,
	 E.DESC_DESCRIP_TABLERO,
	 E.DESC_RESP_CONFIG_ATOMO,
	 E.DESC_BACK_RESP_CONFIG_ATOMO,
	 E.Periodo_Vigencia,
	 E.DTM_FECHA_VIGENCIA_DESDE AS VIGENCIA_TABLERO_DESDE,
	 E.DTM_FECHA_VIGENCIA_HASTA AS VIGENCIA_TABLERO_HASTA,
	 G.DESC_OBJETIVO,
	 C.ID_INDICADOR,
	 A.DESC_TBG,
	 A.FK_TABLERO,
     C.DESC_NOMBRE_INDICADOR,
	 C.DESC_FRECUENCIA,
	 A.VLR_PESO_INDICADOR,
	 A.DESC_HITO_INDICADOR,
	 A.DESC_TIPO_TABLERO,
	 A.DESC_SECUENCIA_ORDEN,
	 A.DESC_CORTO_LARGO_PLAZO,
     C.DESC_REFERENTE,
	 D.DESC_RESPONSABLE_MEDICION,
     D.DESC_CARGO_RESPONSABLE_MEDICION,
     D.DESC_CORREO_RESPONSABLE_MEDICION,
     D.DESC_RESPONSABLE_MEDICION_2,
     D.DESC_CARGO_RESPONSABLE_MEDICION_2,
     D.DESC_CORREO_RESPONSABLE_MEDICION_2,
	 A.DTM_FECHACARGA,
	 A.DESC_HITO_INDIC_HABILITADOR,
	 A.ACTIVOCUMPLIMIENTOMIN,
	 A.CUMPLIMIENTOMINIMO,
	 A.RECONOCIMIENTOMINIMO
	 
FROM [ATOMO].[DWH.FACT_CONFIGURACION_TABLERO] A
	LEFT JOIN [ATOMO].[DWH.DIM_ESTRUCTURA_DESPLIEGUE] B
		ON A.[DESC_SIGLA_AREA] = B.[DESC_SIGLA]
	LEFT JOIN [ATOMO].[CVD_INDICADOR] C
		ON A.[FK_INDICADOR] = C.[GK_INDICADOR]
	LEFT JOIN [ATOMO].[CVD_PARAMETRIZACION_INDICADOR] D
		ON A.[FK_PARAM_INDICADOR] = D.[GK_PARAM_INDICADOR] 

LEFT JOIN ( SELECT GK_TABLERO,
			  CONVERT(CHAR(6),DTM_FECHA_VIGENCIA_DESDE,112) AS Periodo_Vigencia,
			  DESC_TABLERO,
			  DESC_DESCRIP_TABLERO,
			  DESC_RESP_CONFIG_ATOMO,
			  DESC_BACK_RESP_CONFIG_ATOMO,
			  DTM_FECHA_VIGENCIA_DESDE,
			  DTM_FECHA_VIGENCIA_HASTA 

	   FROM [ATOMO].[DWH.DIM_TABLERO]

	   UNION 

	   SELECT GK_TABLERO,
			  CONVERT(CHAR(6),DATEADD(year,1,DTM_FECHA_VIGENCIA_DESDE),112) AS Periodo_Vigencia,
			  DESC_TABLERO,
		      DESC_DESCRIP_TABLERO,
			  DESC_RESP_CONFIG_ATOMO,
			  DESC_BACK_RESP_CONFIG_ATOMO,
			  DTM_FECHA_VIGENCIA_DESDE ,
			  DTM_FECHA_VIGENCIA_HASTA 

	   FROM [ATOMO].[DWH.DIM_TABLERO]
	   WHERE DATEADD(year,1,DTM_FECHA_VIGENCIA_DESDE) <= DTM_FECHA_VIGENCIA_HASTA

	   UNION 

	   SELECT GK_TABLERO,
			  CONVERT(CHAR(6),DTM_FECHA_VIGENCIA_HASTA,112) AS Periodo_Vigencia,
			  DESC_TABLERO,
			  DESC_DESCRIP_TABLERO,
			  DESC_RESP_CONFIG_ATOMO,
			  DESC_BACK_RESP_CONFIG_ATOMO,
			  DTM_FECHA_VIGENCIA_DESDE ,
			  DTM_FECHA_VIGENCIA_HASTA 

	   FROM [ATOMO].[DWH.DIM_TABLERO] ) E
		ON A.[FK_TABLERO] = E.[GK_TABLERO]

	LEFT JOIN [ATOMO].[DWH.DIM_EJE_PALANCA] F
		ON A.[FK_EJE_PALANCA] = F.[GK_EJE_PALANCA]
	LEFT JOIN [ATOMO].[DWH.DIM_OBJETIVO] G
		ON A.[FK_OBJETIVO] = G.[GK_OBJETIVO]

WHERE A.DESC_SIGLA_AREA = 'ILP';