
-- =============================================
-- Author:      Harold Lopez
-- Create Date: 2023-03-27
-- Description: Se crea la vista CVC_TH_HITO_ILP la cual es un insumo para el tablero de ILP
-- =============================================

CREATE VIEW [ATOMO].[CVC_TH_HITO_ILP]
AS SELECT C.FK_INDICADOR AS FK_HITO,
		  C.FK_PARAM_INDICADOR,
		  C.FK_TABLERO,
		  C.DESC_TABLERO_CVR,
		  C.FK_PERIODO,
		  D.DESC_CORREO_USUARIO,
		  D.DTM_FECHACARGA,
		  D.DTM_FECHA_EVENTO_REGISTRO,
		  D.VLR_PLAN_HITO,
		  D.VLR_REAL_HITO,
		  D.PRC_CUMP_HITO,
		  D.VLR_PROY_ESC_BAJO,
		  D.VLR_PROY_ESC_MEDIO,
		  D.VLR_PROY_ESC_ALTO,
		  D.FECHA_CARGA_SYNAPSE,
		  D.FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
		  CM_RESUMEN

FROM (
	  SELECT B.FK_INDICADOR ,
	         B.FK_PARAM_INDICADOR,
	         B.FK_TABLERO,
	         B.DESC_TABLERO_CVR,
	         A.FK_PERIODO,
	         B.DESC_ANNIO_REGISTRO 
	  FROM (
			SELECT CAST(COD_PERIODO AS INT) AS FK_PERIODO
			FROM [ATOMO].[CVD_AUX_TIEMPO_CARGA]
		   ) A
			
	  INNER JOIN (
				  SELECT Z.FK_PARAM_INDICADOR,
						 Z.FK_TABLERO,
						 Y.FK_INDICADOR,
						 Z.DESC_ANNIO_REGISTRO,
						 CASE WHEN (Z.DESC_TABLERO_CVR IS NULL) 
						        THEN 'No'
			                  ELSE Z.DESC_TABLERO_CVR END AS DESC_TABLERO_CVR
				  FROM [ATOMO].[CVD_CONFIGURACION_TABLERO_ILP] Z
					INNER JOIN [ATOMO].[CVD_PARAMETRIZACION_INDICADOR] Y
						ON Z.FK_PARAM_INDICADOR=Y.GK_PARAM_INDICADOR
				  WHERE UPPER(Z.DESC_HITO_INDICADOR) = 'HITO'
                 ) B 
		 ON LEFT(A.FK_PERIODO,4) = B.DESC_ANNIO_REGISTRO
     ) C
 INNER JOIN (
            SELECT FK_HITO,
				   FK_PARAM_INDICADOR,
				   FK_PERIODO,
				   DESC_CORREO_USUARIO,
				   DTM_FECHACARGA,
				   DTM_FECHA_EVENTO_REGISTRO,
				   VLR_PLAN_HITO,
				   VLR_REAL_HITO,
				   PRC_CUMP_HITO,
				   VLR_PROY_ESC_BAJO,
				   VLR_PROY_ESC_MEDIO,
				   VLR_PROY_ESC_ALTO,
				   FECHA_CARGA_SYNAPSE,
				   FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
				   CM_RESUMEN
            FROM [ATOMO].[DWH.FACT_HITO]
           ) AS D
	ON C.FK_PARAM_INDICADOR=D.FK_PARAM_INDICADOR
	AND C.FK_PERIODO = D.FK_PERIODO
	AND C.FK_INDICADOR = D.FK_HITO;