-- =============================================
-- Author:      Harold Lopez - Santiago Guzman
-- Create Date: 2022-08-18
-- Description: Se crea la vista CVC_HITO_INDICADOR_ILP la cual es un insumo para la iniciativba de ILP

-- Author:      Natalia Mendieta Marin 
-- Update Date: 2023-01-04
-- Description: Se realiza ajuste en el cruce con la vista [ATOMO].[CVD_PARAMETRIZACION_CVR]

-- Author:      Oscar Fabian Angel 
-- Update Date: 2023-03-27
-- Description: Se realiza adicion del campo CM_Resumen y ajuste de la fuente a CVC_TH_HITO_ILP

-- Author:      Alejandro Vargas
-- Update Date: 2023-04-04
-- Description: Se realiza adicion del campo DESC_ANNIO_HITO para traer la fecha dle HITO

-- Author:      Oscar Fabian Angel 
-- Update Date: 2023-10-06
-- Description: Se realiza ajustes para inclusion de los campos ACTIVOCUMPLIMIENTOMIN, CUMPLIMIENTOMINIMO, RECONOCIMIENTOMINIMO
-- =============================================

CREATE VIEW [ATOMO].[CVC_HITO_INDICADOR_ILP] AS 
SELECT  A.FK_TABLERO ,
        A.DESC_TABLERO_CVR ,
        A.DESC_TABLERO ,
        A.DESC_VERSION ,
		A.VIGENCIA_TABLERO_DESDE ,
		A.VIGENCIA_TABLERO_HASTA,
        A.DESC_GRUPO ,
        A.DESC_EMPRESA ,
        A.DESC_VP_EJECUTIVA ,
        A.DESC_GRUPO_SEGMENTO ,
        A.DESC_SEGMENTO ,
        A.DESC_UNIDAD_NEGOCIO_NVL_2 ,
        A.DESC_UNIDAD_NEGOCIO_NVL_3 ,
        A.DESC_GERENCIA ,
        A.DESC_RUTINA ,
        A.DESC_SIGLA_AREA ,
        A.DESC_NIVEL ,
        A.DESC_EJE_PALANCA  ,
        A.DESC_OBJETIVO ,
        B.GK_INDICADOR AS FK_INDICADOR ,
        A.ID_INDICADOR ,
        A.DESC_NOMBRE_INDICADOR ,
        A.FK_PARAM_INDICADOR ,
        A.DESC_DETALLE_INDICADOR ,
        A.DESC_HITO_INDICADOR ,
        A.DESC_FRECUENCIA ,
        A.VLR_PESO_INDICADOR ,
        A.DESC_TIPO_TABLERO ,
        A.DESC_CORTO_LARGO_PLAZO ,
        A.DESC_SECUENCIA_ORDEN ,
        A.DESC_REFERENTE ,
        A.DESC_RESPONSABLE_MEDICION ,
        A.DESC_CARGO_RESPONSABLE_MEDICION ,
        A.DESC_CORREO_RESPONSABLE_MEDICION ,
        A.DESC_RESPONSABLE_MEDICION_2 ,
        A.DESC_CARGO_RESPONSABLE_MEDICION_2 ,
        A.DESC_CORREO_RESPONSABLE_MEDICION_2,
        A.DTM_FECHACARGA ,
        LEFT(A.Periodo_Vigencia,4) AS DESC_ANNIO ,
		A.DESC_ANNIO_HITO,
        LEFT(A.Periodo_Vigencia,4) + B.MES AS FK_PERIODO ,
        LEFT(A.Periodo_Vigencia,4) + B.MES AS DESC_PERIODO ,
        B.MES ,
        B.DESC_MENSAJE_CLAVE_INDICADOR ,
        B.DESC_PREMISAS ,
        B.DESC_SENTIDO ,
        B.CANT_DECIMALES_CALCULO ,
        B.CANT_DECIMALES_REPORTE ,
		CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_ANNIO_1
             ELSE ROUND(B.VLR_REAL_ANNIO_1,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_ANNIO_1,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_ANNIO_2
             ELSE ROUND(B.VLR_REAL_ANNIO_2,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_ANNIO_2,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_ANNIO_3
             ELSE ROUND(B.VLR_REAL_ANNIO_3,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_ANNIO_3,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_ANNIO_12
             ELSE ROUND(B.VLR_REAL_ANNIO_12,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_ANNIO_12,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_ANNIO_123
             ELSE ROUND(B.VLR_REAL_ANNIO_123,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_ANNIO_123,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.PRC_CUMP_ANNO2
             ELSE ROUND(B.PRC_CUMP_ANNO2,CANT_DECIMALES_REPORTE)
             END AS PRC_CUMP_ANNO2,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.PRC_CUMP_ANNO3
             ELSE ROUND(B.PRC_CUMP_ANNO3,CANT_DECIMALES_REPORTE)
             END AS PRC_CUMP_ANNO3,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.PRC_CUMP_ANNO12
             ELSE ROUND(B.PRC_CUMP_ANNO12,CANT_DECIMALES_REPORTE)
             END AS PRC_CUMP_ANNO12,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.PRC_CUMP_ANNO123
             ELSE ROUND(B.PRC_CUMP_ANNO123,CANT_DECIMALES_REPORTE)
             END AS PRC_CUMP_ANNO123,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.PRC_AVAN_ACUM_ILP
             ELSE ROUND(B.PRC_AVAN_ACUM_ILP,CANT_DECIMALES_REPORTE)
             END AS PRC_AVAN_ACUM_ILP,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.PRC_AVAN_ILP_ANNO12
             ELSE ROUND(B.PRC_AVAN_ILP_ANNO12,CANT_DECIMALES_REPORTE)
             END AS PRC_AVAN_ILP_ANNO12,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.PRC_AVAN_ILP_ANNO1
             ELSE ROUND(B.PRC_AVAN_ILP_ANNO1,CANT_DECIMALES_REPORTE)
             END AS PRC_AVAN_ILP_ANNO1,		
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_RETO
             ELSE ROUND(B.VLR_RETO,CANT_DECIMALES_REPORTE)
             END AS VLR_RETO,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_PROY_ANNO1
             ELSE ROUND(B.VLR_REAL_PROY_ANNO1,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_PROY_ANNO1,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_PROY_ANNO2
             ELSE ROUND(B.VLR_REAL_PROY_ANNO2,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_PROY_ANNO2,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_PROY_ANNO3
             ELSE ROUND(B.VLR_REAL_PROY_ANNO3,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_PROY_ANNO3,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_PROY_ANNO12
             ELSE ROUND(B.VLR_REAL_PROY_ANNO12,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_PROY_ANNO12,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_PROY_ANNO123
             ELSE ROUND(B.VLR_REAL_PROY_ANNO123,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_PROY_ANNO123,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_REAL_ACUMULADO
             ELSE ROUND(B.VLR_REAL_ACUMULADO,CANT_DECIMALES_REPORTE)
             END AS VLR_REAL_ACUMULADO,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_PLAN_ACUMULADO
             ELSE ROUND(B.VLR_PLAN_ACUMULADO,CANT_DECIMALES_REPORTE)
             END AS VLR_PLAN_ACUMULADO,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_PLAN_ACUM_NORM
             ELSE ROUND(B.VLR_PLAN_ACUM_NORM,CANT_DECIMALES_REPORTE)
             END AS VLR_PLAN_ACUM_NORM,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_META_ANNIO_1
             ELSE ROUND(B.VLR_META_ANNIO_1,CANT_DECIMALES_REPORTE)
             END AS VLR_META_ANNIO_1,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_META_ANNIO_2
             ELSE ROUND(B.VLR_META_ANNIO_2,CANT_DECIMALES_REPORTE)
             END AS VLR_META_ANNIO_2,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_META_ANNIO_3
             ELSE ROUND(B.VLR_META_ANNIO_3,CANT_DECIMALES_REPORTE)
             END AS VLR_META_ANNIO_3,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_META_ANNIO_12
             ELSE ROUND(B.VLR_META_ANNIO_12,CANT_DECIMALES_REPORTE)
             END AS VLR_META_ANNIO_12,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_META_ANNIO_123
             ELSE ROUND(B.VLR_META_ANNIO_123,CANT_DECIMALES_REPORTE)
             END AS VLR_META_ANNIO_123,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_META_NORM_ANNIO_1
             ELSE ROUND(B.VLR_META_NORM_ANNIO_1,CANT_DECIMALES_REPORTE)
             END AS VLR_META_NORM_ANNIO_1,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_META_NORM_ANNIO_2
             ELSE ROUND(B.VLR_META_NORM_ANNIO_2,CANT_DECIMALES_REPORTE)
             END AS VLR_META_NORM_ANNIO_2,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_META_NORM_ANNIO_3
             ELSE ROUND(B.VLR_META_NORM_ANNIO_3,CANT_DECIMALES_REPORTE)
             END AS VLR_META_NORM_ANNIO_3,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_META_NORM_ANNIO_12
             ELSE ROUND(B.VLR_META_NORM_ANNIO_12,CANT_DECIMALES_REPORTE)
             END AS VLR_META_NORM_ANNIO_12,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_META_NORM_ANNIO_123
             ELSE ROUND(B.VLR_META_NORM_ANNIO_123,CANT_DECIMALES_REPORTE)
             END AS VLR_META_NORM_ANNIO_123,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_PROYECCION_ANNIO_1
             ELSE ROUND(B.VLR_PROYECCION_ANNIO_1,CANT_DECIMALES_REPORTE)
             END AS VLR_PROYECCION_ANNIO_1,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_PROYECCION_ANNIO_2
             ELSE ROUND(B.VLR_PROYECCION_ANNIO_2,CANT_DECIMALES_REPORTE)
             END AS VLR_PROYECCION_ANNIO_2,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_PROYECCION_ANNIO_3
             ELSE ROUND(B.VLR_PROYECCION_ANNIO_3,CANT_DECIMALES_REPORTE)
             END AS VLR_PROYECCION_ANNIO_3,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_PROYECCION_ANNIO_12
             ELSE ROUND(B.VLR_PROYECCION_ANNIO_12,CANT_DECIMALES_REPORTE)
             END AS VLR_PROYECCION_ANNIO_12,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_PROYECCION_ANNIO_123
             ELSE ROUND(B.VLR_PROYECCION_ANNIO_123,CANT_DECIMALES_REPORTE)
             END AS VLR_PROYECCION_ANNIO_123,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.VLR_PROYECCION_ANNIO_ESC_MEDIO
             ELSE ROUND(B.VLR_PROYECCION_ANNIO_ESC_MEDIO,CANT_DECIMALES_REPORTE)
             END AS VLR_PROYECCION_ANNIO_ESC_MEDIO,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.PRC_CUMP_ACUM
             ELSE ROUND(B.PRC_CUMP_ACUM*100,CANT_DECIMALES_REPORTE)/100
             END AS PRC_CUMP_ACUM,
        CASE WHEN B.CANT_DECIMALES_REPORTE IS NULL
               THEN B.PRC_CUMP_ANNIO_ESC_MEDIO
             ELSE ROUND(B.PRC_CUMP_ANNIO_ESC_MEDIO*100,CANT_DECIMALES_REPORTE)/100
             END AS PRC_CUMP_ANNIO_ESC_MEDIO  ,
        C.PRC_META_CVR   ,
        B.FECHA_CARGA_SYNAPSE ,
        B.FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
        A.DESC_HITO_INDIC_HABILITADOR,
		A.ACTIVOCUMPLIMIENTOMIN,
	    A.CUMPLIMIENTOMINIMO,
	    A.RECONOCIMIENTOMINIMO,
        B.CM_RESUMEN
		
FROM [ATOMO].[CVD_CONFIGURACION_TABLERO_ILP] A
INNER JOIN ( SELECT SUBSTRING(CAST(Z.FK_PERIODO AS VARCHAR(500)),1,4) AS DESC_ANNIO ,
                    Z.FK_PARAM_INDICADOR ,
                    Z.FK_TABLERO ,
                    Z.DESC_TABLERO_CVR ,
                    Y.GK_INDICADOR ,
                    Z.FK_PERIODO ,
                    CAST(Z.FK_PERIODO AS VARCHAR(500)) AS DESC_PERIODO ,
                    RIGHT(CAST(Z.FK_PERIODO AS VARCHAR(500)),2) AS MES ,
                    CAST(NULL AS VARCHAR(4000)) AS DESC_MENSAJE_CLAVE_INDICADOR ,
                    CAST(NULL AS VARCHAR(4000)) AS DESC_PREMISAS ,
                    Y.DESC_SENTIDO ,
                    Y.CANT_DECIMALES_CALCULO ,
                    Y.CANT_DECIMALES_REPORTE ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_REAL_ANNIO_1 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_REAL_ANNIO_2 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_REAL_ANNIO_3 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_REAL_ANNIO_12 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_REAL_ANNIO_123 ,
				    CAST(NULL AS DECIMAL(25,10)) AS VLR_RETO ,
				    CAST(NULL AS DECIMAL(25,10)) AS VLR_REAL_PROY_ANNO1 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_REAL_PROY_ANNO2 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_REAL_PROY_ANNO3 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_REAL_PROY_ANNO12 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_REAL_PROY_ANNO123 ,
                    CASE WHEN Z.VLR_REAL_HITO IS NULL
                           THEN NULL
                          ELSE Z.VLR_REAL_HITO * 100 
                          END AS VLR_REAL_ACUMULADO,
                    CASE WHEN Z.VLR_REAL_HITO IS NULL AND right(Z.FK_PERIODO,2)<>12
                           THEN NULL
                          ELSE CASE WHEN Z.VLR_PLAN_HITO IS NULL
                                      THEN CASE WHEN W.VLR_PLAN_HITO IS NULL
                                                  THEN NULL
                                                ELSE W.VLR_PLAN_HITO
                                           END
                                    ELSE Z.VLR_PLAN_HITO
                               END
                         END AS VLR_PLAN_ACUMULADO ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_PLAN_ACUM_NORM ,
                    CASE WHEN W.VLR_PLAN_HITO IS NULL
                           THEN NULL
                         ELSE W.VLR_PLAN_HITO
                         END AS VLR_META_ANNIO_1        ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_META_ANNIO_2 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_META_ANNIO_3 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_META_ANNIO_12 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_META_ANNIO_123 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_META_NORM_ANNIO_1 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_META_NORM_ANNIO_2 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_META_NORM_ANNIO_3 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_META_NORM_ANNIO_12 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_META_NORM_ANNIO_123 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_PROYECCION_ANNIO_1 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_PROYECCION_ANNIO_2 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_PROYECCION_ANNIO_3 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_PROYECCION_ANNIO_12 ,
                    CAST(NULL AS DECIMAL(25,10)) AS VLR_PROYECCION_ANNIO_123,
                    CASE WHEN Z.VLR_PROY_ESC_MEDIO IS NULL
                           THEN NULL
                         ELSE Z.VLR_PROY_ESC_MEDIO * 100
                         END AS VLR_PROYECCION_ANNIO_ESC_MEDIO,
                    CAST(NULL AS DECIMAL(25,10)) AS PRC_CUMP_ANNO1 ,
                    CAST(NULL AS DECIMAL(25,10)) AS PRC_CUMP_ANNO2 ,
                    CAST(NULL AS DECIMAL(25,10)) AS PRC_CUMP_ANNO3 ,
                    CAST(NULL AS DECIMAL(25,10)) AS PRC_CUMP_ANNO12 ,
                    CAST(NULL AS DECIMAL(25,10)) AS PRC_CUMP_ANNO123 ,
                    CAST(NULL AS DECIMAL(25,10)) AS PRC_AVAN_ACUM_ILP ,
                    CAST(NULL AS DECIMAL(25,10)) AS PRC_AVAN_ILP_ANNO12 ,
                    CAST(NULL AS DECIMAL(25,10)) AS PRC_AVAN_ILP_ANNO1 ,
                    CASE WHEN Z.PRC_CUMP_HITO IS NULL
                           THEN NULL 
                         ELSE Z.PRC_CUMP_HITO
                         END AS PRC_CUMP_ACUM,
                    CASE WHEN Z.VLR_PROY_ESC_MEDIO IS NULL
                           THEN NULL
                         ELSE Z.VLR_PROY_ESC_MEDIO
                        END AS PRC_CUMP_ANNIO_ESC_MEDIO,
                    Z.FECHA_CARGA_SYNAPSE ,
                    Z.FECHA_PROXIMA_ACTUALIZA_SYNAPSE,
					Z.CM_RESUMEN

             FROM [ATOMO].[CVC_TH_HITO_ILP] AS Z
                INNER JOIN [ATOMO].[DWH.DIM_INDICADOR] Y
					ON Z.FK_HITO=Y.GK_INDICADOR
                LEFT JOIN [ATOMO].[CVD_CONTEXTO_HITO] W
					ON Z.FK_PARAM_INDICADOR = W.FK_PARAM_INDICADOR
                    AND Z.FK_TABLERO = W.FK_TABLERO 
					
		   ) B

    ON A.FK_PARAM_INDICADOR = B.FK_PARAM_INDICADOR
    AND A.FK_TABLERO = B.FK_TABLERO

LEFT JOIN [ATOMO].[CVD_PARAMETRIZACION_CVR] AS C
    ON LEFT(A.DESC_VERSION,1) = C.DESC_VERSION
    AND A.DESC_ANNIO = CAST(C.DTM_VIGENCIA_DESDE AS VARCHAR(4));